### ISSUE TITLE
Issue with Item Sets Being Pulled

### ISSUE THREAD

**Issue by niclake** [dustinblackman/Championify#101]
5.18 - Looks like item sets are being pulled down weird; everyone starts with a ward in their final build, then junglers have the first upgrade + full item listed separate. 6th item usually doesn't get past boots for any champion.

**Comment by dustinblackman** [comment]
Looks like an issue on their end, seems they're having some odd aggregation issues. Joel is probably already on it!

http://champion.gg/champion/Nidalee
http://champion.gg/champion/Lux

**Comment by joel1st** [comment]
Yeah looking into this at the moment - I think there have been some changes to riots api, as I haven't changed anything on my side, will be fixed up within the next day or two!
