### ISSUE TITLE
Add skill priorities to sources that don't support it

### ISSUE THREAD

**Issue by dustinblackman** [dustinblackman/Championify#104]
Lolflavor at the moment doesn't support skill priorities. Consider using the ones from Championgg instead.

**Comment by secretdataz** [comment]
Some standard skill order for SR can be useless in ARAM. For example, Nasus.

**Comment by dustinblackman** [comment]
@secretdataz It was more for using Champion.gg's skill orders on Lolflavor SR item sets.

**Comment by dustinblackman** [comment]
Closing this for https://github.com/dustinblackman/Championify/issues/160 instead.
