### ISSUE TITLE
Garena SG/MY installation has different path.

### ISSUE THREAD

**Issue by BenMQ** [dustinblackman/Championify#105]
The config folder is found inside `GarenaLoL\GameData\Apps\LoL\Game` path in Windows for the SG/MY server.

I am not sure about other Garena installations, but this is needed to get SG/MY one to work. It is where `League of Legends.exe` reside. 

Finding `LoLLauncher.exe` puts the Config folder in the wrong place.

**Comment by dustinblackman** [comment]
Dup, It's on my list for 1.0. :) 
https://github.com/dustinblackman/Championify/issues/63
