### ISSUE TITLE
Random Timeout / unhandled error

### ISSUE THREAD

**Issue by rattenwahn** [dustinblackman/Championify#11]
```
events.js:85
    throw er; // Unhandled 'error' event
          ^
Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1000:19)
```
Happens randomly between after the 10th champion and the last. Couldn't figure out any reason.

**Comment by dustinblackman** [comment]
It's one of two things. Your internet connection dropping (most likely not), or Champion.gg possibly holding back on connections. I have a fix for it in the GUI version, it'll hopefully be done this week.

**Comment by dustinblackman** [comment]
Fixed in GUI release.
