### ISSUE TITLE
Metasrc / 3v3 Item Sets

### ISSUE THREAD

**Issue by dustinblackman** [dustinblackman/Championify#113]
- [ ] Summoners Rift
- [ ] Twisted Treeline
- [ ] ARAM

**Comment by dustinblackman** [comment]
MetaSrc uses percentages of items used instead of order. Not worth it.

**Comment by srs1978** [comment]
Can we get metasrcs for 5x5 and ARAM as well?

**Comment by dustinblackman** [comment]
I plan on putting everything when I can find the time to do it.

**Comment by Ka0tik** [comment]
Was this never implemented? I am new to your program and was about to suggest Metasrc since I only really play Twisted Treeline. Thanks!
