### ISSUE TITLE
Check and updated user contributed translations

### ISSUE THREAD

**Issue by dustinblackman** [dustinblackman/Championify#119]
- [ ] Change `Deutsche` to  `Deutsch`

**Comment by dwhwang** [comment]
I'm working on the Chinese Traditional translation. Do I report here or do I open a new issue?

**Comment by dustinblackman** [comment]
@dwhwang For translations just keep everything on Transifex please. :) https://github.com/dustinblackman/Championify/blob/master/CONTRIBUTE.md#translations

**Comment by dwhwang** [comment]
On my way :)
