### ISSUE TITLE
Windows admin test.

### ISSUE THREAD

**Issue by mkrjhnsn** [dustinblackman/Championify#12]
I just encountered a bug.  A fresh install of LOL doesn't have the Config/Champions folder created so the isWindowsAdmin always fails when trying to create test.txt.

Worked fine once I manually created the folder.

**Comment by dustinblackman** [comment]
Thanks! I've already fixed it in the GUI branch. Release will be shortly.

**Comment by dustinblackman** [comment]
Fixed in GUI release.
