### ISSUE TITLE
Add LeagueOfGraphs

### ISSUE THREAD

**Issue by dustinblackman** [dustinblackman/Championify#124]

**Comment by Nefari0uss** [comment]
How do you intend to show LoG data? Something like all items built ordered by popularity?

**Comment by dustinblackman** [comment]
@Nefari0uss 

At the moment, taking [this](http://www.leagueofgraphs.com/champions/items/annie/middle/platinum) as an example, I take the most popular starter and core items, 6 end game items, and 3 pairs of boots.  6 and 3 are so they fit well in game for those who have titles and descriptions enabled for items.
