### ISSUE TITLE
A JavaScript error occured in the browser process

### ISSUE THREAD

**Issue by EternaI** [dustinblackman/Championify#126]
![error](https://cloud.githubusercontent.com/assets/1097125/10395087/64b18924-6e9b-11e5-9cf6-3b43a4ab8d8a.png)

Theres a Screen of the Error after Launching the Application

**Comment by Wiary** [comment]
Hi!
This is old version of Championify.
Download manually newer version from there: 
https://github.com/dustinblackman/Championify/releases/tag/1.0.2

**Comment by dustinblackman** [comment]
Yep, @Wiary got it. Thanks!
