### ISSUE TITLE
Loading Loop

### ISSUE THREAD

**Issue by action-simon** [dustinblackman/Championify#127]
Hello,

I am running Championify on Windows 10. After installing it works like a charm but when I want to open Championify a second time it just crashes and starts again in a loop and I can do nothing but restart Windows.

Deleting appdata/championify does NOT solve the issue only uninstalling and installing again does.

If you need any logs or whatever tell me what and I will provide them of course. :)

**Comment by dustinblackman** [comment]
@action-simon Odd, I'll take logs for sure. :) You'll find it in the `appdata/Championify' folder called 'championify.log.txt'. Thanks!

**Comment by action-simon** [comment]
{"level":"info","message":"Saved preference file to C:\\Users\\Simon\\AppData\\Roaming\\Championify\\prefs.json","timestamp":"2015-10-09T00:59:47.467Z"}
{"level":"info","message":"Getting Champion.gg Version","timestamp":"2015-10-09T00:59:48.067Z"}
{"level":"info","message":"Getting LoL Version","timestamp":"2015-10-09T00:59:48.068Z"}
{"level":"info","message":"Downloading Champs from Riot","timestamp":"2015-10-09T00:59:48.246Z"}
{"level":"info","message":"Downloading ARAM Champs","timestamp":"2015-10-09T00:59:48.417Z"}
{"level":"info","message":"Processing Rift: Aatrox","timestamp":"2015-10-09T00:59:48.498Z"}
{"level":"info","message":"Processing Rift: Ahri","timestamp":"2015-10-09T00:59:48.504Z"}
{"level":"info","message":"Processing ARAM: Aatrox","timestamp":"2015-10-09T00:59:48.945Z"}
{"level":"info","message":"Processing ARAM: Ahri","timestamp":"2015-10-09T00:59:48.946Z"}
{"level":"info","message":"Processing ARAM: Akali","timestamp":"2015-10-09T00:59:48.948Z"}
{"level":"info","message":"Processing Rift: Akali","timestamp":"2015-10-09T00:59:49.207Z"}
{"level":"info","message":"Processing ARAM: Alistar","timestamp":"2015-10-09T00:59:49.380Z"}
{"level":"info","message":"Processing ARAM: Amumu","timestamp":"2015-10-09T00:59:49.389Z"}
{"level":"info","message":"Processing ARAM: Anivia","timestamp":"2015-10-09T00:59:49.396Z"}
{"level":"info","message":"Processing ARAM: Annie","timestamp":"2015-10-09T00:59:49.738Z"}
{"level":"info","message":"Processing Rift: Alistar","timestamp":"2015-10-09T00:59:49.837Z"}
{"level":"info","message":"Processing ARAM: Ashe","timestamp":"2015-10-09T00:59:49.841Z"}
{"level":"info","message":"Processing ARAM: Azir","timestamp":"2015-10-09T00:59:49.843Z"}
{"level":"info","message":"Processing ARAM: Bard","timestamp":"2015-10-09T00:59:50.182Z"}
{"level":"info","message":"Processing ARAM: Blitzcrank","timestamp":"2015-10-09T00:59:50.246Z"}
{"level":"info","message":"Processing ARAM: Brand","timestamp":"2015-10-09T00:59:50.249Z"}
{"level":"info","message":"Processing Rift: Amumu","timestamp":"2015-10-09T00:59:50.380Z"}
{"level":"info","message":"Processing Rift: Anivia","timestamp":"2015-10-09T00:59:50.545Z"}
{"level":"info","message":"Processing ARAM: Braum","timestamp":"2015-10-09T00:59:50.564Z"}
{"level":"info","message":"Processing ARAM: Caitlyn","timestamp":"2015-10-09T00:59:50.590Z"}
{"level":"info","message":"Processing ARAM: Cassiopeia","timestamp":"2015-10-09T00:59:50.594Z"}
{"level":"info","message":"Processing Rift: Annie","timestamp":"2015-10-09T00:59:50.841Z"}
{"level":"info","message":"Processing ARAM: Cho'Gath","timestamp":"2015-10-09T00:59:50.910Z"}
{"level":"info","message":"Processing ARAM: Corki","timestamp":"2015-10-09T00:59:50.938Z"}
{"level":"info","message":"Processing ARAM: Darius","timestamp":"2015-10-09T00:59:50.943Z"}
{"level":"info","message":"Processing Rift: Ashe","timestamp":"2015-10-09T00:59:50.983Z"}
{"level":"info","message":"Processing ARAM: Diana","timestamp":"2015-10-09T00:59:51.253Z"}
{"level":"info","message":"Processing ARAM: Dr. Mundo","timestamp":"2015-10-09T00:59:51.328Z"}
{"level":"info","message":"Processing ARAM: Draven","timestamp":"2015-10-09T00:59:51.335Z"}
{"level":"info","message":"Processing Rift: Azir","timestamp":"2015-10-09T00:59:51.441Z"}
{"level":"info","message":"Processing ARAM: Ekko","timestamp":"2015-10-09T00:59:51.639Z"}
{"level":"info","message":"Processing ARAM: Elise","timestamp":"2015-10-09T00:59:51.676Z"}
{"level":"info","message":"Processing ARAM: Evelynn","timestamp":"2015-10-09T00:59:51.684Z"}
{"level":"info","message":"Processing ARAM: Ezreal","timestamp":"2015-10-09T00:59:51.988Z"}
{"level":"info","message":"Processing ARAM: Fiddlesticks","timestamp":"2015-10-09T00:59:52.022Z"}
{"level":"info","message":"Processing Rift: Bard","timestamp":"2015-10-09T00:59:52.104Z"}
{"level":"info","message":"Processing ARAM: Fiora","timestamp":"2015-10-09T00:59:52.108Z"}
{"level":"info","message":"Processing Rift: Blitzcrank","timestamp":"2015-10-09T00:59:52.133Z"}
{"level":"info","message":"Processing ARAM: Fizz","timestamp":"2015-10-09T00:59:52.336Z"}
{"level":"info","message":"Processing ARAM: Galio","timestamp":"2015-10-09T00:59:52.371Z"}
{"level":"info","message":"Processing ARAM: Gangplank","timestamp":"2015-10-09T00:59:52.478Z"}
{"level":"info","message":"Processing ARAM: Garen","timestamp":"2015-10-09T00:59:52.689Z"}
{"level":"info","message":"Processing Rift: Brand","timestamp":"2015-10-09T00:59:52.775Z"}
{"level":"info","message":"Processing Rift: Braum","timestamp":"2015-10-09T00:59:52.807Z"}
{"level":"info","message":"Processing ARAM: Gnar","timestamp":"2015-10-09T00:59:52.808Z"}
{"level":"info","message":"Processing ARAM: Gragas","timestamp":"2015-10-09T00:59:52.825Z"}
{"level":"info","message":"Processing ARAM: Graves","timestamp":"2015-10-09T00:59:53.034Z"}
{"level":"info","message":"Processing ARAM: Hecarim","timestamp":"2015-10-09T00:59:53.154Z"}
{"level":"info","message":"Processing ARAM: Heimerdinger","timestamp":"2015-10-09T00:59:53.169Z"}
{"level":"info","message":"Processing Rift: Caitlyn","timestamp":"2015-10-09T00:59:53.263Z"}
{"level":"info","message":"Processing ARAM: Irelia","timestamp":"2015-10-09T00:59:53.383Z"}
{"level":"info","message":"Processing ARAM: Janna","timestamp":"2015-10-09T00:59:53.502Z"}
{"level":"info","message":"Processing ARAM: Jarvan IV","timestamp":"2015-10-09T00:59:53.525Z"}
{"level":"info","message":"Processing Rift: Cassiopeia","timestamp":"2015-10-09T00:59:53.607Z"}
{"level":"info","message":"Processing ARAM: Jax","timestamp":"2015-10-09T00:59:53.790Z"}
{"level":"info","message":"Processing Rift: Cho'Gath","timestamp":"2015-10-09T00:59:53.885Z"}
{"level":"info","message":"Processing ARAM: Jayce","timestamp":"2015-10-09T00:59:53.893Z"}
{"level":"info","message":"Processing ARAM: Jinx","timestamp":"2015-10-09T00:59:53.901Z"}
{"level":"info","message":"Processing ARAM: Kalista","timestamp":"2015-10-09T00:59:54.139Z"}
{"level":"info","message":"Processing ARAM: Karma","timestamp":"2015-10-09T00:59:54.265Z"}
{"level":"info","message":"Processing ARAM: Karthus","timestamp":"2015-10-09T00:59:54.277Z"}
{"level":"info","message":"Processing ARAM: Kassadin","timestamp":"2015-10-09T00:59:54.519Z"}
{"level":"info","message":"Processing ARAM: Katarina","timestamp":"2015-10-09T00:59:54.623Z"}
{"level":"info","message":"Processing ARAM: Kayle","timestamp":"2015-10-09T00:59:54.636Z"}
{"level":"info","message":"Processing Rift: Corki","timestamp":"2015-10-09T00:59:54.682Z"}
{"level":"info","message":"Processing Rift: Darius","timestamp":"2015-10-09T00:59:54.750Z"}
{"level":"info","message":"Processing ARAM: Kennen","timestamp":"2015-10-09T00:59:54.873Z"}
{"level":"info","message":"Processing ARAM: Kha'Zix","timestamp":"2015-10-09T00:59:54.979Z"}
{"level":"info","message":"Processing ARAM: Kog'Maw","timestamp":"2015-10-09T00:59:55.030Z"}
{"level":"info","message":"Processing ARAM: LeBlanc","timestamp":"2015-10-09T00:59:55.223Z"}
{"level":"info","message":"Processing Rift: Diana","timestamp":"2015-10-09T00:59:55.283Z"}
{"level":"info","message":"Processing Rift: Draven","timestamp":"2015-10-09T00:59:55.342Z"}
{"level":"info","message":"Processing ARAM: Lee Sin","timestamp":"2015-10-09T00:59:55.349Z"}
{"level":"info","message":"Processing ARAM: Leona","timestamp":"2015-10-09T00:59:55.382Z"}
{"level":"info","message":"Processing ARAM: Lissandra","timestamp":"2015-10-09T00:59:55.607Z"}
{"level":"info","message":"Processing ARAM: Lucian","timestamp":"2015-10-09T00:59:55.707Z"}
{"level":"info","message":"Processing ARAM: Lulu","timestamp":"2015-10-09T00:59:55.740Z"}
{"level":"info","message":"Processing Rift: Dr. Mundo","timestamp":"2015-10-09T00:59:55.783Z"}
{"level":"info","message":"Processing Rift: Ekko","timestamp":"2015-10-09T00:59:56.060Z"}
{"level":"info","message":"Processing ARAM: Lux","timestamp":"2015-10-09T00:59:56.063Z"}
{"level":"info","message":"Processing ARAM: Malphite","timestamp":"2015-10-09T00:59:56.066Z"}
{"level":"info","message":"Processing ARAM: Malzahar","timestamp":"2015-10-09T00:59:56.102Z"}
{"level":"info","message":"Processing ARAM: Maokai","timestamp":"2015-10-09T00:59:56.447Z"}
{"level":"info","message":"Processing ARAM: Master Yi","timestamp":"2015-10-09T00:59:56.452Z"}
{"level":"info","message":"Processing ARAM: Miss Fortune","timestamp":"2015-10-09T00:59:56.462Z"}
{"level":"info","message":"Processing Rift: Elise","timestamp":"2015-10-09T00:59:56.526Z"}
{"level":"info","message":"Processing ARAM: Wukong","timestamp":"2015-10-09T00:59:56.806Z"}
{"level":"info","message":"Processing ARAM: Mordekaiser","timestamp":"2015-10-09T00:59:56.810Z"}
{"level":"info","message":"Processing ARAM: Morgana","timestamp":"2015-10-09T00:59:56.815Z"}
{"level":"info","message":"Processing Rift: Evelynn","timestamp":"2015-10-09T00:59:56.842Z"}
{"level":"info","message":"Processing Rift: Ezreal","timestamp":"2015-10-09T00:59:57.011Z"}
{"level":"info","message":"Processing ARAM: Nami","timestamp":"2015-10-09T00:59:57.189Z"}
{"level":"info","message":"Processing ARAM: Nasus","timestamp":"2015-10-09T00:59:57.191Z"}
{"level":"info","message":"Processing ARAM: Nautilus","timestamp":"2015-10-09T00:59:57.193Z"}
{"level":"info","message":"Processing Rift: Fiddlesticks","timestamp":"2015-10-09T00:59:57.434Z"}
{"level":"info","message":"Processing Rift: Fiora","timestamp":"2015-10-09T00:59:57.482Z"}
{"level":"info","message":"Processing ARAM: Nidalee","timestamp":"2015-10-09T00:59:57.537Z"}
{"level":"info","message":"Processing ARAM: Nocturne","timestamp":"2015-10-09T00:59:57.541Z"}
{"level":"info","message":"Processing ARAM: Nunu","timestamp":"2015-10-09T00:59:57.546Z"}
{"level":"info","message":"Processing ARAM: Olaf","timestamp":"2015-10-09T00:59:57.942Z"}
{"level":"info","message":"Processing Rift: Fizz","timestamp":"2015-10-09T00:59:57.984Z"}
{"level":"info","message":"Processing ARAM: Orianna","timestamp":"2015-10-09T00:59:57.985Z"}
{"level":"info","message":"Processing ARAM: Pantheon","timestamp":"2015-10-09T00:59:57.987Z"}
{"level":"info","message":"Processing ARAM: Poppy","timestamp":"2015-10-09T00:59:58.342Z"}
{"level":"info","message":"Processing ARAM: Quinn","timestamp":"2015-10-09T00:59:58.348Z"}
{"level":"info","message":"Processing ARAM: Rammus","timestamp":"2015-10-09T00:59:58.361Z"}
{"level":"info","message":"Processing Rift: Galio","timestamp":"2015-10-09T00:59:58.622Z"}
{"level":"info","message":"Processing ARAM: Rek'Sai","timestamp":"2015-10-09T00:59:58.698Z"}
{"level":"info","message":"Processing ARAM: Renekton","timestamp":"2015-10-09T00:59:58.709Z"}
{"level":"info","message":"Processing ARAM: Rengar","timestamp":"2015-10-09T00:59:58.715Z"}
{"level":"info","message":"Processing Rift: Gangplank","timestamp":"2015-10-09T00:59:58.830Z"}
{"level":"info","message":"Processing ARAM: Riven","timestamp":"2015-10-09T00:59:59.057Z"}
{"level":"info","message":"Processing ARAM: Rumble","timestamp":"2015-10-09T00:59:59.061Z"}
{"level":"info","message":"Processing ARAM: Ryze","timestamp":"2015-10-09T00:59:59.063Z"}
{"level":"info","message":"Processing Rift: Garen","timestamp":"2015-10-09T00:59:59.510Z"}
{"level":"info","message":"Processing ARAM: Sejuani","timestamp":"2015-10-09T00:59:59.514Z"}
{"level":"info","message":"Processing ARAM: Shaco","timestamp":"2015-10-09T00:59:59.516Z"}
{"level":"info","message":"Processing ARAM: Shen","timestamp":"2015-10-09T00:59:59.517Z"}
{"level":"info","message":"Processing Rift: Gnar","timestamp":"2015-10-09T00:59:59.581Z"}
{"level":"info","message":"Processing ARAM: Shyvana","timestamp":"2015-10-09T00:59:59.866Z"}
{"level":"info","message":"Processing ARAM: Singed","timestamp":"2015-10-09T00:59:59.869Z"}
{"level":"info","message":"Processing ARAM: Sion","timestamp":"2015-10-09T00:59:59.873Z"}
{"level":"info","message":"Processing Rift: Gragas","timestamp":"2015-10-09T00:59:59.957Z"}
{"level":"info","message":"Processing Rift: Graves","timestamp":"2015-10-09T01:00:00.154Z"}
{"level":"info","message":"Processing ARAM: Sivir","timestamp":"2015-10-09T01:00:00.214Z"}
{"level":"info","message":"Processing ARAM: Skarner","timestamp":"2015-10-09T01:00:00.223Z"}
{"level":"info","message":"Processing ARAM: Sona","timestamp":"2015-10-09T01:00:00.229Z"}
{"level":"info","message":"Processing Rift: Hecarim","timestamp":"2015-10-09T01:00:00.379Z"}
{"level":"info","message":"Processing Rift: Heimerdinger","timestamp":"2015-10-09T01:00:00.614Z"}
{"level":"info","message":"Processing ARAM: Soraka","timestamp":"2015-10-09T01:00:00.619Z"}
{"level":"info","message":"Processing ARAM: Swain","timestamp":"2015-10-09T01:00:00.621Z"}
{"level":"info","message":"Processing ARAM: Syndra","timestamp":"2015-10-09T01:00:00.623Z"}
{"level":"info","message":"Processing ARAM: Tahm Kench","timestamp":"2015-10-09T01:00:00.979Z"}
{"level":"info","message":"Processing ARAM: Talon","timestamp":"2015-10-09T01:00:00.987Z"}
{"level":"info","message":"Processing ARAM: Taric","timestamp":"2015-10-09T01:00:00.990Z"}
{"level":"info","message":"Processing Rift: Irelia","timestamp":"2015-10-09T01:00:01.101Z"}
{"level":"info","message":"Processing ARAM: Teemo","timestamp":"2015-10-09T01:00:01.337Z"}
{"level":"info","message":"Processing ARAM: Thresh","timestamp":"2015-10-09T01:00:01.340Z"}
{"level":"info","message":"Processing ARAM: Tristana","timestamp":"2015-10-09T01:00:01.347Z"}
{"level":"info","message":"Processing Rift: Janna","timestamp":"2015-10-09T01:00:01.533Z"}
{"level":"info","message":"Processing Rift: Jarvan IV","timestamp":"2015-10-09T01:00:01.565Z"}
{"level":"info","message":"Processing ARAM: Trundle","timestamp":"2015-10-09T01:00:01.743Z"}
{"level":"info","message":"Processing ARAM: Tryndamere","timestamp":"2015-10-09T01:00:01.753Z"}
{"level":"info","message":"Processing ARAM: Twisted Fate","timestamp":"2015-10-09T01:00:01.764Z"}
{"level":"info","message":"Processing Rift: Jax","timestamp":"2015-10-09T01:00:01.894Z"}
{"level":"info","message":"Processing ARAM: Twitch","timestamp":"2015-10-09T01:00:02.099Z"}
{"level":"info","message":"Processing ARAM: Udyr","timestamp":"2015-10-09T01:00:02.112Z"}
{"level":"info","message":"Processing ARAM: Urgot","timestamp":"2015-10-09T01:00:02.123Z"}
{"level":"info","message":"Processing Rift: Jayce","timestamp":"2015-10-09T01:00:02.428Z"}
{"level":"info","message":"Processing ARAM: Varus","timestamp":"2015-10-09T01:00:02.448Z"}
{"level":"info","message":"Processing ARAM: Vayne","timestamp":"2015-10-09T01:00:02.511Z"}
{"level":"info","message":"Processing ARAM: Veigar","timestamp":"2015-10-09T01:00:02.513Z"}
{"level":"info","message":"Processing Rift: Jinx","timestamp":"2015-10-09T01:00:02.750Z"}
{"level":"info","message":"Processing ARAM: Vel'Koz","timestamp":"2015-10-09T01:00:02.801Z"}
{"level":"info","message":"Processing ARAM: Vi","timestamp":"2015-10-09T01:00:02.861Z"}
{"level":"info","message":"Processing ARAM: Viktor","timestamp":"2015-10-09T01:00:02.865Z"}
{"level":"info","message":"Processing ARAM: Vladimir","timestamp":"2015-10-09T01:00:03.150Z"}
{"level":"info","message":"Processing Rift: Kalista","timestamp":"2015-10-09T01:00:03.183Z"}
{"level":"info","message":"Processing ARAM: Volibear","timestamp":"2015-10-09T01:00:03.209Z"}
{"level":"info","message":"Processing ARAM: Warwick","timestamp":"2015-10-09T01:00:03.213Z"}
{"level":"info","message":"Processing Rift: Karma","timestamp":"2015-10-09T01:00:03.247Z"}
{"level":"info","message":"Processing Rift: Karthus","timestamp":"2015-10-09T01:00:03.505Z"}
{"level":"info","message":"Processing ARAM: Xerath","timestamp":"2015-10-09T01:00:03.510Z"}
{"level":"info","message":"Processing ARAM: Xin Zhao","timestamp":"2015-10-09T01:00:03.561Z"}
{"level":"info","message":"Processing ARAM: Yasuo","timestamp":"2015-10-09T01:00:03.563Z"}
{"level":"info","message":"Processing ARAM: Yorick","timestamp":"2015-10-09T01:00:03.889Z"}
{"level":"info","message":"Processing ARAM: Zac","timestamp":"2015-10-09T01:00:03.923Z"}
{"level":"info","message":"Processing ARAM: Zed","timestamp":"2015-10-09T01:00:03.925Z"}
{"level":"info","message":"Processing ARAM: Ziggs","timestamp":"2015-10-09T01:00:04.245Z"}
{"level":"info","message":"Processing ARAM: Zilean","timestamp":"2015-10-09T01:00:04.278Z"}
{"level":"info","message":"Processing ARAM: Zyra","timestamp":"2015-10-09T01:00:04.291Z"}
{"level":"info","message":"Processing Rift: Kassadin","timestamp":"2015-10-09T01:00:04.357Z"}
{"level":"info","message":"Processing Rift: Katarina","timestamp":"2015-10-09T01:00:04.497Z"}
{"level":"info","message":"Processing Rift: Kayle","timestamp":"2015-10-09T01:00:04.976Z"}
{"level":"info","message":"Processing Rift: Kennen","timestamp":"2015-10-09T01:00:05.403Z"}
{"level":"info","message":"Processing Rift: Kha'Zix","timestamp":"2015-10-09T01:00:05.978Z"}
{"level":"info","message":"Processing Rift: Kindred","timestamp":"2015-10-09T01:00:06.427Z"}
{"level":"info","message":"Processing Rift: Kog'Maw","timestamp":"2015-10-09T01:00:06.501Z"}
{"level":"info","message":"Processing Rift: LeBlanc","timestamp":"2015-10-09T01:00:06.734Z"}
{"level":"info","message":"Processing Rift: Lee Sin","timestamp":"2015-10-09T01:00:07.173Z"}
{"level":"info","message":"Processing Rift: Leona","timestamp":"2015-10-09T01:00:07.358Z"}
{"level":"info","message":"Processing Rift: Lissandra","timestamp":"2015-10-09T01:00:07.502Z"}
{"level":"info","message":"Processing Rift: Lucian","timestamp":"2015-10-09T01:00:07.780Z"}
{"level":"info","message":"Processing Rift: Lulu","timestamp":"2015-10-09T01:00:08.316Z"}
{"level":"info","message":"Processing Rift: Lux","timestamp":"2015-10-09T01:00:08.353Z"}
{"level":"info","message":"Processing Rift: Malphite","timestamp":"2015-10-09T01:00:08.846Z"}
{"level":"info","message":"Processing Rift: Malzahar","timestamp":"2015-10-09T01:00:09.304Z"}
{"level":"info","message":"Processing Rift: Maokai","timestamp":"2015-10-09T01:00:09.754Z"}
{"level":"info","message":"Processing Rift: Master Yi","timestamp":"2015-10-09T01:00:09.907Z"}
{"level":"info","message":"Processing Rift: Miss Fortune","timestamp":"2015-10-09T01:00:10.359Z"}
{"level":"info","message":"Processing Rift: Wukong","timestamp":"2015-10-09T01:00:10.632Z"}
{"level":"info","message":"Processing Rift: Mordekaiser","timestamp":"2015-10-09T01:00:10.783Z"}
{"level":"info","message":"Processing Rift: Morgana","timestamp":"2015-10-09T01:00:11.490Z"}
{"level":"info","message":"Processing Rift: Nami","timestamp":"2015-10-09T01:00:11.539Z"}
{"level":"info","message":"Processing Rift: Nasus","timestamp":"2015-10-09T01:00:11.982Z"}
{"level":"info","message":"Processing Rift: Nautilus","timestamp":"2015-10-09T01:00:12.268Z"}
{"level":"info","message":"Processing Rift: Nidalee","timestamp":"2015-10-09T01:00:12.417Z"}
{"level":"info","message":"Processing Rift: Nocturne","timestamp":"2015-10-09T01:00:12.867Z"}
{"level":"info","message":"Processing Rift: Nunu","timestamp":"2015-10-09T01:00:12.996Z"}
{"level":"info","message":"Processing Rift: Olaf","timestamp":"2015-10-09T01:00:13.301Z"}
{"level":"info","message":"Processing Rift: Orianna","timestamp":"2015-10-09T01:00:14.067Z"}
{"level":"info","message":"Processing Rift: Pantheon","timestamp":"2015-10-09T01:00:14.109Z"}
{"level":"info","message":"Processing Rift: Poppy","timestamp":"2015-10-09T01:00:14.545Z"}
{"level":"info","message":"Processing Rift: Quinn","timestamp":"2015-10-09T01:00:15.052Z"}
{"level":"info","message":"Processing Rift: Rammus","timestamp":"2015-10-09T01:00:15.365Z"}
{"level":"info","message":"Processing Rift: Rek'Sai","timestamp":"2015-10-09T01:00:15.809Z"}
{"level":"info","message":"Processing Rift: Renekton","timestamp":"2015-10-09T01:00:15.938Z"}
{"level":"info","message":"Processing Rift: Rengar","timestamp":"2015-10-09T01:00:16.225Z"}
{"level":"info","message":"Processing Rift: Riven","timestamp":"2015-10-09T01:00:16.349Z"}
{"level":"info","message":"Processing Rift: Rumble","timestamp":"2015-10-09T01:00:16.763Z"}
{"level":"info","message":"Processing Rift: Ryze","timestamp":"2015-10-09T01:00:17.080Z"}
{"level":"info","message":"Processing Rift: Sejuani","timestamp":"2015-10-09T01:00:17.178Z"}
{"level":"info","message":"Processing Rift: Shaco","timestamp":"2015-10-09T01:00:17.609Z"}
{"level":"info","message":"Processing Rift: Shen","timestamp":"2015-10-09T01:00:17.984Z"}
{"level":"info","message":"Processing Rift: Shyvana","timestamp":"2015-10-09T01:00:18.034Z"}
{"level":"info","message":"Processing Rift: Singed","timestamp":"2015-10-09T01:00:18.968Z"}
{"level":"info","message":"Processing Rift: Sion","timestamp":"2015-10-09T01:00:19.031Z"}
{"level":"info","message":"Processing Rift: Sivir","timestamp":"2015-10-09T01:00:19.473Z"}
{"level":"info","message":"Processing Rift: Skarner","timestamp":"2015-10-09T01:00:19.953Z"}
{"level":"info","message":"Processing Rift: Sona","timestamp":"2015-10-09T01:00:19.985Z"}
{"level":"info","message":"Processing Rift: Soraka","timestamp":"2015-10-09T01:00:20.438Z"}
{"level":"info","message":"Processing Rift: Swain","timestamp":"2015-10-09T01:00:20.473Z"}
{"level":"info","message":"Processing Rift: Syndra","timestamp":"2015-10-09T01:00:20.917Z"}
{"level":"info","message":"Processing Rift: Tahm Kench","timestamp":"2015-10-09T01:00:21.383Z"}
{"level":"info","message":"Processing Rift: Talon","timestamp":"2015-10-09T01:00:21.412Z"}
{"level":"info","message":"Processing Rift: Taric","timestamp":"2015-10-09T01:00:21.846Z"}
{"level":"info","message":"Processing Rift: Teemo","timestamp":"2015-10-09T01:00:22.332Z"}
{"level":"info","message":"Processing Rift: Thresh","timestamp":"2015-10-09T01:00:22.418Z"}
{"level":"info","message":"Processing Rift: Tristana","timestamp":"2015-10-09T01:00:22.852Z"}
{"level":"info","message":"Processing Rift: Trundle","timestamp":"2015-10-09T01:00:22.886Z"}
{"level":"info","message":"Processing Rift: Tryndamere","timestamp":"2015-10-09T01:00:23.344Z"}
{"level":"info","message":"Processing Rift: Twisted Fate","timestamp":"2015-10-09T01:00:23.865Z"}
{"level":"info","message":"Processing Rift: Twitch","timestamp":"2015-10-09T01:00:24.304Z"}
{"level":"info","message":"Processing Rift: Udyr","timestamp":"2015-10-09T01:00:24.344Z"}
{"level":"info","message":"Processing Rift: Urgot","timestamp":"2015-10-09T01:00:24.789Z"}
{"level":"info","message":"Processing Rift: Varus","timestamp":"2015-10-09T01:00:24.832Z"}
{"level":"info","message":"Processing Rift: Vayne","timestamp":"2015-10-09T01:00:25.693Z"}
{"level":"info","message":"Processing Rift: Veigar","timestamp":"2015-10-09T01:00:25.789Z"}
{"level":"info","message":"Processing Rift: Vel'Koz","timestamp":"2015-10-09T01:00:26.175Z"}
{"level":"info","message":"Processing Rift: Vi","timestamp":"2015-10-09T01:00:26.209Z"}
{"level":"info","message":"Processing Rift: Viktor","timestamp":"2015-10-09T01:00:26.672Z"}
{"level":"info","message":"Processing Rift: Vladimir","timestamp":"2015-10-09T01:00:27.118Z"}
{"level":"info","message":"Processing Rift: Volibear","timestamp":"2015-10-09T01:00:27.158Z"}
{"level":"info","message":"Processing Rift: Warwick","timestamp":"2015-10-09T01:00:28.084Z"}
{"level":"info","message":"Processing Rift: Xerath","timestamp":"2015-10-09T01:00:28.114Z"}
{"level":"info","message":"Processing Rift: Xin Zhao","timestamp":"2015-10-09T01:00:28.567Z"}
{"level":"info","message":"Processing Rift: Yasuo","timestamp":"2015-10-09T01:00:28.609Z"}
{"level":"info","message":"Processing Rift: Yorick","timestamp":"2015-10-09T01:00:29.046Z"}
{"level":"info","message":"Processing Rift: Zac","timestamp":"2015-10-09T01:00:29.528Z"}
{"level":"info","message":"Processing Rift: Zed","timestamp":"2015-10-09T01:00:29.558Z"}
{"level":"info","message":"Processing Rift: Ziggs","timestamp":"2015-10-09T01:00:30.077Z"}
{"level":"info","message":"Processing Rift: Zilean","timestamp":"2015-10-09T01:00:30.512Z"}
{"level":"info","message":"Processing Rift: Zyra","timestamp":"2015-10-09T01:00:30.546Z"}
{"level":"info","message":"Deleting Old Builds","timestamp":"2015-10-09T01:00:31.508Z"}
{"level":"info","message":"Saved preference file to C:\\Users\\Simon\\AppData\\Roaming\\Championify\\prefs.json","timestamp":"2015-10-09T01:00:32.839Z"}

**Comment by action-simon** [comment]
This was the old log and as I have written I have deleted the appdata/championify folder to test it again but sadly there was no new log file created.

**Comment by dustinblackman** [comment]
@action-simon That's the log produced when it's insta rebooting? There's no error in there at the moment. I have a feeling it may be something to do with writing the champ files. 

If you can, go in to your league folder, then config,  and delete the champions folder entirely and rerun Championify. Let me know if it auto reboots again.

**Comment by action-simon** [comment]
Nope, sadly this log is from the first start where I ad no errors.

And yes it is looping again after deledting the champions folder.

**Comment by dustinblackman** [comment]
@action-simon Damn... And it loops just after the import is supposed to finish, right?

**Comment by action-simon** [comment]
Nope before the program is starting at all :/

**Comment by guykisel** [comment]
I'm seeing the same behavior. Not seeing any useful logs being generated unfortunately.

**Comment by dustinblackman** [comment]
@action-simon @guykisel Found it. I was able to reproduce it on a slowed down Windows VM. Patch incoming.

**Comment by guykisel** [comment]
Just tested with your new release, can't reproduce the problem anymore. Thanks :+1:

**Comment by action-simon** [comment]
Can confirm working now.

**Comment by dustinblackman** [comment]
Thanks guys, apprecieate it. :)
