### ISSUE TITLE
COmputer crash

### ISSUE THREAD

**Issue by Meraxys** [dustinblackman/Championify#128]
I downloaded the 1.0.3 version yesterday and tried to run it. It didn't let me run it unless if I cleared the folder Championify in Roaming. The problem is that it made my computer crashed when Championify ran rightly. I have W8.1 64bit; it gave me the error "SYSTEM_SERVICE_EXCEPTION (NETIO.SYS)". Is this championify's fault or is it mine?

**Comment by nilesr** [comment]
It sounds like a network driver issue. Check to see if you have the right driver. Championify does not use NETIO.SYS, that's a kernel extension.

**Comment by dustinblackman** [comment]
@Meraxys Yep, @nilesr is right. This sounds unrelated. Also check your anti virus as some will tap in to kernel extensions to block applications.
