### ISSUE TITLE
LoL version incorrect (on Championify window)

### ISSUE THREAD

**Issue by rafaeldamasceno** [dustinblackman/Championify#134]
I'm not sure where Championify parses this info from, but it's wrong. It's currently reporting the version is 5.19.

**Comment by dustinblackman** [comment]
Huh, Riot forgot to update their endpoint. I'll give them a ping. Thanks!
https://ddragon.leagueoflegends.com/realms/na.json

**Comment by dustinblackman** [comment]
They updated it, looks good.
