### ISSUE TITLE
Things without translation

### ISSUE THREAD

**Issue by Warkratos** [dustinblackman/Championify#138]
Hey, there are some strings that I can't translate, like on ARAM, all strings are in english and in-game tabs like "Middle, Top, Jungle" is untranslated too, is there anything we can do to translate ?

**Comment by dustinblackman** [comment]
The ARAM strings are directly from Lolflavor. I haven't considered translating them myself, though I supposed I could replace them. And true I had forgotten to translate in game positions like `Middle` and `Top`. I'll add that to my list as well for 1.2.0.

Thanks!
