### ISSUE TITLE
Not getting champion.gg version error

### ISSUE THREAD

**Issue by SW1FT** [dustinblackman/Championify#144]
I can't seem to be able to update summoners rift builds via champion.gg anymore. It keeps getting errors either on getting champion.gg version or not fully downloading all the champion's builds in the end of the update. I've submitted a log yesterday regarding this issue.

**Comment by dustinblackman** [comment]
@SW1FT Mind posting the log here?

**Comment by SW1FT** [comment]
I can't open the log with the button on the program, but here it goes:

{"level":"info","message":"Getting Champion.gg Version","timestamp":"2015-11-21T08:38:42.620Z"}
{"level":"info","message":"Getting LoL Version","timestamp":"2015-11-21T08:38:42.621Z"}
{"level":"info","message":"Downloading Champs from Riot","timestamp":"2015-11-21T08:38:42.892Z"}
{"message":"Can't get Champion.GG Version","type":"RequestError","ua":"win32 10.0.10240","locale":"en","cause":{"code":"ECONNRESET"},"rootCause":{"code":"ECONNRESET"},"ownStack":"RequestError: Can't get Champion.GG Version\n    at D:\\Program Files (x86)\\Championify\\resources\\app.asar\\js\\sources\\championgg.js:40:19\n    at D:\\Program Files (x86)\\Championify\\resources\\app.asar\\js\\helpers.js:49:16\n    at D:\\Program Files (x86)\\Championify\\resources\\app.asar\\node_modules\\async\\lib\\async.js:647:51\n    at D:\\Program Files (x86)\\Championify\\resources\\app.asar\\node_modules\\async\\lib\\async.js:697:13\n    at D:\\Program Files (x86)\\Championify\\resources\\app.asar\\node_modules\\async\\lib\\async.js:52:16\n    at D:\\Program Files (x86)\\Championify\\resources\\app.asar\\node_modules\\async\\lib\\async.js:267:21\n    at D:\\Program Files (x86)\\Championify\\resources\\app.asar\\node_modules\\async\\lib\\async.js:44:16\n    at D:\\Program Files (x86)\\Championify\\resources\\app.asar\\node_modules\\async\\lib\\async.js:694:17\n    at D:\\Program Files (x86)\\Championify\\resources\\app.asar\\node_modules\\async\\lib\\async.js:173:37\n    at D:\\Program Files (x86)\\Championify\\resources\\app.asar\\node_modules\\async\\lib\\async.js:623:25","level":"error","timestamp":"2015-11-21T08:38:44.009Z"}

**Comment by dustinblackman** [comment]
Been having issues with Kaspersky as well. Glad you figured it out!
