### ISSUE TITLE
Championify no longer works due to server-side item builds in 5.23

### ISSUE THREAD

**Issue by Doeke** [dustinblackman/Championify#145]
First time you log into League with the new patch it will upload your saved item builds, but Championify is no longer able to update your builds. :(

Is there any way to change it to upload new builds to the server or is this project now dead?

**Comment by dustinblackman** [comment]
It was unrelated to server side item sets, thanks for the report though! https://www.reddit.com/r/leagueoflegends/comments/3u32jl/championify_121_were_not_dead/
