### ISSUE TITLE
Option to disable application updates

### ISSUE THREAD

**Issue by Cardridge** [dustinblackman/Championify#148]
Being forced to update every version just to get new translations I won't ever use is one thing. A whole different one would be the application calling home each time I'm starting it.

I understand that I could just not allow the connection in the first place but that's besides the point.

**Comment by dustinblackman** [comment]
Forced updates are on purpose. If Riot were to ever change something on their end that could potentially be breaking, then Championify could start causing havoc over your client. I'll consider making translation updates optional in the future.

**Comment by Cardridge** [comment]
>If Riot were to ever change something on their end that could potentially be breaking, then Championify **could** start causing havoc over your client.

Keyword being could and which would be resolved by simply removing the bunch of JSON files created by Championify. This is already an option in the application itself.

>Plus the updates are small,

Again, that's beside the point. Championify requesting updates from a server other than champion.gg without asking me first is my issue.

**Comment by dustinblackman** [comment]
You do know the update endpoint is Github right?

**Comment by Cardridge** [comment]
I do indeed.

**Comment by Cardridge** [comment]
I guess my concern is less about security but more about getting stuff bundled with the package I've never asked for in the first place.
A bad analogy would be going into a shop, selecting product A but getting told by the shopkeeper that I'm only able to purchase and use said product when it's bundled with product B (it is free as well!).
