### ISSUE TITLE
Update Readme for Mac Gatekeeper problems

### ISSUE THREAD

**Issue by dustinblackman** [dustinblackman/Championify#15]

**Comment by soofuzz** [comment]
you mean the unidentified developer box? yea that'll happen if you don't have dev certificates from apple. easy fix


1. go to System Preferences>Security & Privacy>General
2. Just press open anyways under allow apps downloaded from
2a. or just for everything in general just change the setting to allow from "anywhere" (not recommended)

**Comment by dustinblackman** [comment]
Yeah, but a lot of users aren't aware of it. I'm going to update the README to explain it.
