### ISSUE TITLE
Duplicate items

### ISSUE THREAD

**Issue by drorasaf** [dustinblackman/Championify#152]
Sometimes an item set have 2 boots(sorcerer's usually) although it is clear that is not the case.
The same sometimes happen with other unique passive items, that is easy be distinguished as a bug.
I believe the algorithm to create the item set creates statistics but does not ignore the order the location of the item.

**Comment by dustinblackman** [comment]
Dups and item positions are all done on [Champion.gg's end](http://champion.gg). You can hit up [geei](https://www.reddit.com/user/geei) from the TSM dev team if there's an issue there. Thanks!
