### ISSUE TITLE
Failed to write item set json file

### ISSUE THREAD

**Issue by marcopa92** [dustinblackman/Championify#153]
Hi all, since today i have this problem with championify, i can't load anymore the builds, i tried to uninstall and reinstall, of course i open it as administrator 
"Something broken - EPERM:  operation not permitted, open c/riot bla bla

I did also a restore of pc, but nothing. The problems still here.

**Comment by dustinblackman** [comment]
This happens when you try to import, or when the application loads?

**Comment by marcopa92** [comment]
When i import!

**Comment by marcopa92** [comment]
Problem solved, was a problem of security, not about the program. Thanks for the answer.
