### ISSUE TITLE
Pls Help

### ISSUE THREAD

**Issue by Xeron1007** [dustinblackman/Championify#154]
So my LoL was screwing up so i reinstalled it after that i couldnt use Championify for some reason which really pissed me off. This is what i see when i launch Championify. I hope someone can help me fix it. 
![pls help](https://cloud.githubusercontent.com/assets/17104031/12870238/7961e900-cd8b-11e5-80b6-79e190de75dd.JPG)

**Comment by dustinblackman** [comment]
Here you go.
https://github.com/dustinblackman/Championify#the-app-opens-with-a-white-box-infinite-loops-or-nothing-happens

I'll reopen the issue if you're still having trouble.
