### ISSUE TITLE
Suggestion: Linux port

### ISSUE THREAD

**Issue by fwinest-JediThug** [dustinblackman/Championify#155]
I don't know how to compile it under Xubuntu, I've never used Coffeescript.

**Comment by dustinblackman** [comment]
You play League on Linux?

**Comment by fwinest-JediThug** [comment]
Yup, works good enough with Wine.

**Comment by dustinblackman** [comment]
I'd have to rewrite quite a bit to get a compiler done for Linux, and tests to go with you. You'd probably be the only one to use it. :P 

Two suggestions, you can run `gulp dev` and it'll run on Linux just fine without needing to compile, or you can run Championify is wine as well. Both work. Good luck!
