### ISSUE TITLE
[Suggestion] League Of Legends Cleaner

### ISSUE THREAD

**Issue by ImmortaI** [dustinblackman/Championify#156]
Hey,

This is a bit unrelated to the program directly but at the moment there is a problem with lol where you have to manually remove logs and previous installations (that allow you to watch older demos) because after a while your install folder ends up being over 30+ GB.

I was wondering if it would be possible to have a tickbox in the Championify that would delete logs + previous installations whilst updating. 

Kind regards

38951

https://www.reddit.com/r/leagueoflegends/comments/46dlod/just_deleted_37gb_of_junk_from_my_lol_folder/

**Comment by dustinblackman** [comment]
I think that would honestly be done in another tool. I try to keep Championify just related to items. Sorry. :(
