### ISSUE TITLE
Patch 6.6: Error when importing data

### ISSUE THREAD

**Issue by Warkratos** [dustinblackman/Championify#159]
I keep getting this error when importing.

"Phrase doesn't exist for en: aurelion sol"

**Comment by Naitsrk** [comment]
Same here. It must scan all champion names and not have code for the new aurelion sol. I wish i knew coding i'm sure this is a simple fix.

**Comment by dustinblackman** [comment]
Riot seems to of made a mistake and were inconsistent with the IDs for Champions. I've pushed a workaround patch to https://github.com/dustinblackman/Championify/releases/tag/1.2.11. Thanks for the report!

**Comment by Naitsrk** [comment]
Thank you! Hopefully they don't patch their mistake lol

**Comment by dustinblackman** [comment]
Even if they do it'll support both cases.
