### ISSUE TITLE
Missing consumabels (potion)

### ISSUE THREAD

**Issue by envolta** [dustinblackman/Championify#163]
Refillable potion, Hunter potion and corrupting potion are missing under consumable. 

Could you please add them?

EDIT: It's items sets from lolflavor i'm talking about

Might be this lines missing in the consumable:

_{"count":1,"id":"2031"},
{"count":1,"id":"2032"},
{"count":1,"id":"2033"},_

In the "text-file" from lolfalvor they are listed under: _"blocks":[{"items":_

**Comment by envolta** [comment]
lolflavor

**Comment by dustinblackman** [comment]
Got a mass rewrite in progress, will get this out for version 1.3.0 when it's done. Thanks!

**Comment by envolta** [comment]
Awesome :D
