### ISSUE TITLE
Not accepting pull requests

### ISSUE THREAD

**Issue by dustinblackman** [dustinblackman/Championify#166]
A note for people wishing to contribute, I'm currently working on a full rewrite [here](https://github.com/dustinblackman/Championify/tree/rewrite) and won't be accepting pull requests until it's complete as the entire stack has changed. Afterwards you're more then welcome!

Progress can be tracked with my Zenhub board or [milestones](https://github.com/dustinblackman/Championify/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.3.0).

Thanks.

**Comment by iggyvolz** [comment]
That link seems to be a 404.  Have you not pushed it yet?

**Comment by dustinblackman** [comment]
Forgot to close this earlier. Thanks.
