### ISSUE TITLE
Item builds version flaw.

### ISSUE THREAD

**Issue by mkrjhnsn** [dustinblackman/Championify#17]
The version info used for the build labels uses data from RIOT even though the data from champion.gg hasn't been updated for the "live" patch yet.

For example the current live patch is 5.9.1 but the data on champion.gg is for patch 5.8.  This will lead to issues where the build says it is for the "live" version but the data will be from the previous patch(if the user updates before champion.gg has aggregated data for the "live" patch).

A better solution would be scraping the version info from champion.gg so the item build data will always be in sync with the label.  It would also be nice to have an indicator showing what patch version champion.gg has data from so the user knows when data for the new patch is available.

**Comment by dustinblackman** [comment]
That's a very good point. And this is actually the first time I've seen the Riot API replay with a version that isn't on production yet, so I wasn't expecting. Will have it fixed in the next release. Thanks!

**Comment by mkrjhnsn** [comment]
It isn't really an issue with Riot, their version info is correct.  The problem is champion.gg needs to take a couple days after a new patch to analyze enough games to generate reliable item builds.  So they are stuck on the previous patch for a couple days once a new patch is released.

If I understood Javascript I would send some pull requests.  Thanks for your work on this project, its really helpful.

**Comment by dustinblackman** [comment]
Don't worry about a PR, it's only a couple lines for me as the function already exists to do this. It's on my list. :)
