### ISSUE TITLE
Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by michaellcg** [dustinblackman/Championify#170]
Hey Dustin, loving Championify!
Quick thing - on latest 2 patches, I'm having difficulty in importing any new builds to League.

I'm getting the above error when I try on 1.3.1 and on 1.3.0 I was getting "Cannot read property 'getSr' of undefined"

Tried it in admin mode, allowed Championify through Firewall and my internet is definitely on. Can't open the log view either I'm afraid. Any advice?

**Comment by dustinblackman** [comment]
1.3.1 was meant to fix that issue and had for other users. When you load your app, all the tick boxes should be empty other then Consumables and Trinkets. Is it like that for you?

**Comment by michaellcg** [comment]
Yep!

**Comment by kellyj6** [comment]
I am having the same issue. I have never had trouble with championify before. I reinstalled twice trying to see if it was something I did, still doesn't work.

"cannot read property 'then' of undefined."

**Comment by dustinblackman** [comment]
That's odd. Do you mind sending me the logs, please? I'll take a look.

Windows: C:\Users\YOURNAME\AppData\Roaming\Championify\championify.log.txt
OSX: /Users/YOURNAME/Library/Application Support/Championify/championify.log.txt

**Comment by kellyj6** [comment]
[championify.log.txt](https://github.com/dustinblackman/Championify/files/207497/championify.log.txt)

**Comment by kellyj6** [comment]
thanks for responding btw

**Comment by dustinblackman** [comment]
Fixed in 1.3.2. Thanks!

**Comment by kellyj6** [comment]
Yeah, I had an idea that was the problem. I have championify in the D:/ drive. Thanks for the update!

**Comment by dustinblackman** [comment]
Yep. I wasnt catching it correctly.
