### ISSUE TITLE
False-positiv issue with Bitdefender Internet Security 2015

### ISSUE THREAD

**Issue by EThaNol2005** [dustinblackman/Championify#171]
Hello, i got any false-positiv with **Bitdefender** everytime when i start **Championify** or starting import.

![ss 2016-04-09 at 02 08 58](https://cloud.githubusercontent.com/assets/6765072/14400450/99ff0678-fdf8-11e5-8309-ce465e11e81f.png)
![ss 2016-04-09 at 02 09 12](https://cloud.githubusercontent.com/assets/6765072/14400451/99ff9502-fdf8-11e5-91e6-2bdd5a0d0b68.png)
![ss 2016-04-09 at 02 09 21](https://cloud.githubusercontent.com/assets/6765072/14400452/99ffe660-fdf8-11e5-9bca-ec7f408e34cf.png)
![ss 2016-04-09 at 02 09 27](https://cloud.githubusercontent.com/assets/6765072/14400454/9a005046-fdf8-11e5-91ac-7783a4db151d.png)
![ss 2016-04-09 at 02 09 31](https://cloud.githubusercontent.com/assets/6765072/14400453/9a0028f0-fdf8-11e5-8cb1-b943ee12d56a.png)

**Comment by dustinblackman** [comment]
I've contacted bitdefender support, and they have yet to whitelist lolflavor. Nothing much I can do unfortunately. 
https://github.com/dustinblackman/Championify/blob/master/FAQ.md#why-is-my-antivirus-complaining-about-lolflavor
