### ISSUE TITLE
Update next Appveyor build number

### ISSUE THREAD

**Issue by dustinblackman** [dustinblackman/Championify#173]
Update the next Appveyor build number at the end of every Travis build to avoid them going out of sync.

https://www.appveyor.com/docs/api/projects-builds#update-project-build-number

**Comment by ilanbiala** [comment]
@dustinblackman is this still in progress?

**Comment by dustinblackman** [comment]
It's manually set at the moment.

**Comment by dustinblackman** [comment]
This has been fixed on appveyors end.
