### ISSUE TITLE
Just seeing the background of the app

### ISSUE THREAD

**Issue by tempustasis** [dustinblackman/Championify#174]
The method on the FAQ doesn't seem to work for me (I have the Mac version) because my application support folder doesn't have a file/folder for Championify. What can I do? 

Thanks in advance!

**Comment by dustinblackman** [comment]
It does have one, you have to enable seeing hidden files. The app won't even show a window without that folder being created. 

http://www.macworld.co.uk/how-to/mac-software/how-show-hidden-files-in-mac-os-x-finder-funter-3520878/
