### ISSUE TITLE
"Windows cannot find"

### ISSUE THREAD

**Issue by GetReap** [dustinblackman/Championify#177]
Get an error while updating championify after giving password to get past a firewall. says "Windows cannot find "C:\Users\Admin\AppData\Roaming\Championify\update_major.bat" make sure you typed the name correctly and try again." How do i fix this?

**Comment by Nefari0uss** [comment]
This is just a guess but the location of some files might have changed with one of the updates. A full reinstall might solve the problem? @dustinblackman would know more than me.

**Comment by dustinblackman** [comment]
Delete the `C:\Users\Admin\AppData\Roaming\Championify\` folder and try again.

**Comment by dustinblackman** [comment]
Stale.
