### ISSUE TITLE
Mastery Pages from Champion.gg

### ISSUE THREAD

**Issue by soofuzz** [dustinblackman/Championify#18]
if this could be added to the LoLClient as like an overlay it would help some noobs like me and others that are new to league :P thanks for the awesome app thou! keep up the good work :D

**Comment by dustinblackman** [comment]
This could be interesting, but attempting to do an overlay with Electron will take a lot of work. I'll think on it and get back to this issue otherwise.

**Comment by dustinblackman** [comment]
If Riot ever adds supposed for imported masteries, I'll for sure take this up. Until then I'm going to close this.
