### ISSUE TITLE
Nothing loads

### ISSUE THREAD

**Issue by Papermaiden** [dustinblackman/Championify#180]
When I start it up in regular, or as admin, it only ever loads the background. I used to use this a lot, but now I can't, is it a problem with Windows 10? I had a computer running Windows 8 using it fine, then when I got my new gaming computer that came with Windows 10 installed, I can no longer use it. If there's anything on my end you need to help me, please let me know! I love this program!

**Comment by dustinblackman** [comment]
https://github.com/dustinblackman/Championify/blob/master/FAQ.md#the-app-opens-with-a-white-box-infinite-loops-i-just-see-the-background-or-nothing-happens

**Comment by Papermaiden** [comment]
I did so twice now, and it crashes my computer now. Don't know if you know the reason, whether something in the code, but most likely because im on Windows 10 as on my old laptop I did imports just fine with no problems. You've done a great service for this program, but it looks like I won't be able to use it for awhile now. Keep doing what you're doing mate :)

**Comment by dustinblackman** [comment]
Crashes your computer? o.O

**Comment by Papermaiden** [comment]
It gets to around 8 to 40% randomly in between the last five tries, and I guess the closest thing is almost a blue screen. My computer crashes and starts gathering data then resets itself

**Comment by hezanathos** [comment]
I have exactly the same issue. the bluesceen spcifies that netio stopped working.

**Comment by Rollingkeyboard** [comment]
I got same issue and I tried to reinstall network card driver but it still cause blue screen that netio stopped working.
