### ISSUE TITLE
No item sets sources

### ISSUE THREAD

**Issue by SH4ZZY** [dustinblackman/Championify#182]
http://prntscr.com/b1e21n

**Comment by dustinblackman** [comment]
That's a first, thanks for the report. 

Temp fix should work for now until I figure it what happened. https://github.com/dustinblackman/Championify/blob/master/FAQ.md#the-app-opens-with-a-white-box-infinite-loops-i-just-see-the-background-or-nothing-happens

**Comment by SH4ZZY** [comment]
still not working

**Comment by dustinblackman** [comment]
Stale.
