### ISSUE TITLE
Item source drop down menu buggy

### ISSUE THREAD

**Issue by ahng1996** [dustinblackman/Championify#183]
Sometimes when clicking on the textfield of the item source combo box, it sometimes glitches out and the dropdown box goes crazy for a couple of seconds it can be annoying at times.

**Comment by dustinblackman** [comment]
What OS?

**Comment by ahng1996** [comment]
Windows 10

**Comment by dustinblackman** [comment]
I shall see if I can reproduce, I haven't come across it. Thanks!
