### ISSUE TITLE
"Lolflavor Version: Unknown"

### ISSUE THREAD

**Issue by MonkPreston** [dustinblackman/Championify#185]
I don't know if LolFlavor updated their website (I never looked at it before this started) but since patch 6.9 Championify has been unable to download the ARAM builds from LolFlavor.

**Comment by dustinblackman** [comment]
Lolflavor builds are still working on the few systems I test with. Make sure your [antivirus](https://github.com/dustinblackman/Championify/blob/master/FAQ.md#why-is-my-antivirus-complaining-about-lolflavor) or your network isn't blocking it.
