### ISSUE TITLE
Uknown bug

### ISSUE THREAD

**Issue by Elchaco** [dustinblackman/Championify#187]
Hey 
Championify was well working on my computer but then a bug appeared; when i wanted to upload it for patch 6.9 of league of legend, it shut down my pc and then if i  reboot it i see this (pictures linked)
I tried to uninstall and install back championify but it doesn't work 
Any idea ? thany you
![snip_20160513102038](https://cloud.githubusercontent.com/assets/19342409/15242220/36b7ae72-18f5-11e6-9c96-7deefc233d03.png)
![snip_20160513102447](https://cloud.githubusercontent.com/assets/19342409/15242228/3d52571e-18f5-11e6-9fce-7244a3f1de8b.png)

**Comment by dustinblackman** [comment]
Looks like a bad install, try this and it should fix it for now. I have a patch coming up in the next minor release for it. https://github.com/dustinblackman/Championify/blob/master/FAQ.md#the-app-opens-with-a-white-box-infinite-loops-i-just-see-the-background-or-nothing-happens
