### ISSUE TITLE
Can't access Github package.json

### ISSUE THREAD

**Issue by furysense** [dustinblackman/Championify#188]
http://prntscr.com/b4urt2 after few min
http://prntscr.com/b4ugul
i few problems like dat
Can't access Github package.json
or
something like Can't find lol version

**Comment by furysense** [comment]
http://prntscr.com/b4ulp4

**Comment by dustinblackman** [comment]
Your firewall or router (such as within schools) is blocking access to Github, and Riot's API servers. After fixing that, you'll be good to go.

**Comment by Capu-Johann** [comment]
http://prntscr.com/dt4t07
this did nothing :(

**Comment by dustinblackman** [comment]
This issue is old. See here. https://github.com/dustinblackman/Championify/issues/248
