### ISSUE TITLE
LoL Version detected stuck in 6.9

### ISSUE THREAD

**Issue by julian-poidevin** [dustinblackman/Championify#189]
The application is detecting a **6.9** Lol version while my LoL version is : **6.10.16_05_13_13_53**

I'm on Mac 10.11.5 with MBP 15inch Mid 2010.
![capture d ecran 2016-05-19 a 18 59 25](https://cloud.githubusercontent.com/assets/8756421/15402310/d7b4c618-1df3-11e6-949c-5dd366c36321.png)

![capture d ecran 2016-05-19 a 19 00 01](https://cloud.githubusercontent.com/assets/8756421/15402330/f1029e2e-1df3-11e6-934c-b86b81c95e83.png)

**Comment by ilanbiala** [comment]
I have the same issue.

**Comment by iggyvolz** [comment]
Same here, also on Mac (10.9.5).

**Comment by dustinblackman** [comment]
Yes, the issue is on Riot's end, they've forgotten to update the realms endpoint which is where Championify gets the LoL version from. This has happened once before, and they should have it updated within the next two days.

**Comment by iggyvolz** [comment]
Does this affect Championify's functionality other than just displaying the wrong version?

**Comment by dustinblackman** [comment]
Nope!
