### ISSUE TITLE
Championify will open, but won't display anything. 

### ISSUE THREAD

**Issue by LeviBeck** [dustinblackman/Championify#190]
Hi I need help, I really love Championify, but ever since patch 6.8 I haven't been able to use it.

It was working just fine and then when I tried to open it up to update to patch 6.8 it didn't work.

I tried uninstalling and reinstalling, tried running the program as administrator,I tried using the zip version instead of the windows setup; I looked on her to see if anyone else was having the issue but I couldn't find anything. 

Here's a picture of what it looks like when I open the program: 

![champ](https://cloud.githubusercontent.com/assets/19600044/15594233/a481a49e-2368-11e6-9402-533494d9c9c0.jpg)

**Comment by dustinblackman** [comment]
This will fix it. https://github.com/dustinblackman/Championify/blob/master/FAQ.md#the-app-opens-with-a-white-box-infinite-loops-i-just-see-the-background-or-nothing-happens
