### ISSUE TITLE
Keep getting 6.1 builds

### ISSUE THREAD

**Issue by ilanbiala** [dustinblackman/Championify#191]
I keep getting 6.1 builds instead of 6.10, this also happened for 6.9. I uninstalled and reinstalled League and Championify so I'm not sure what's the issue.

**Comment by dustinblackman** [comment]
Run Championify as an admin, and then hit delete, are your builds ingame gone? Then import again.

**Comment by ilanbiala** [comment]
Still didn't fix it.

**Comment by dustinblackman** [comment]
@ilanbiala You didn't answer my question though. When you hit delete are the ingame builds gone?

**Comment by ilanbiala** [comment]
Yes.

**Comment by ilanbiala** [comment]
When I restarted League, I get just Top 6.1 again, I'm not sure why.

**Comment by dustinblackman** [comment]
I have a theory. Go to C:\Riot Games\League of Legends\Configs\Config\Champions\Ahri\Recommended and drag/drop any of the summoners rift JSON files found there.

**Comment by ilanbiala** [comment]
I'm on Mac, so the path is different, but these are the files I found. GitHub doesn't allow JSON files, so I just uploaded a zip of all of them.

[Archive.zip](https://github.com/dustinblackman/Championify/files/296394/Archive.zip)

**Comment by dustinblackman** [comment]
These are all 6.10 item sets. Your screen is too small and it's cutting off the 0.

**Comment by ilanbiala** [comment]
I'm positive it's not that because my screen is big enough and when I remove and add item sets and then start Leage fresh I get 6.10, but at some point in the future after enough League exits and starts, I will get 6.1. I'm positive the item set is different because the items are different, and all those JSON files don't show up in the item set dropdown.

**Comment by dustinblackman** [comment]
Championify simply has to be pointing to the correct `.app` in whatever directory, other then that it shouldn't matter.

**Comment by ilanbiala** [comment]
What else could be wrong?

**Comment by ilanbiala** [comment]
Okay, well I'll see if it happens again.

**Comment by ilanbiala** [comment]
@dustinblackman I actually still have this issue and it happens whenever I restart LoL after the first time it has Championify. Please tell me how I can fix this, because it means I can never close LoL without running Championify again.
