### ISSUE TITLE
Add op.gg

### ISSUE THREAD

**Issue by corylulu** [dustinblackman/Championify#192]
Would probably have to get a bit creative on this since it shows 3 item "core builds" in one group and individual items pick/win rate in another group. 

You could probably combine "core builds" that have 2 matching items or something. Perhaps combining OP.gg with Champion.gg might be a posibility as well, just needs some brainstorming. 

If I have time in the future, I'll see if I can help contribute to this.

**Comment by jfily** [comment]
+1

**Comment by ilanbiala** [comment]
@corylulu +1, any progress on this?

**Comment by SmoresTiger** [comment]
would also like to see lolmasters.net added

**Comment by dustinblackman** [comment]
Made a separate for lolmasters. PRs are welcome. https://github.com/dustinblackman/Championify/issues/201
