### ISSUE TITLE
Championify for Mac keeps Loading

### ISSUE THREAD

**Issue by Emolus** [dustinblackman/Championify#194]
When opening in stays in the Loading stage on both Champion.gg and KoreanBuilds. Also Lolflavor appears as unknown. What can I do about this?

Thanks!

**Comment by dustinblackman** [comment]
Do you have something like LittleSnitch installed that's blocking Championify?

**Comment by Emolus** [comment]
No I have not installed anything like that, it was working last patch, anything I can do to check?

On 07/06/2016, at 8:02 p.m., Dustin Blackman <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you have something like LittleSnitch installed that's blocking Championify?

-

**Comment by dustinblackman** [comment]
Not that I know of in all honestly. If everything is saying unknown then Championify can't access any of the websites.

**Comment by Emolus** [comment]
Damn, I've been using Championify since its beginning :(. I've tried disabling the firewall and stuff and still doesn't work. Will keep trying

**Comment by dustinblackman** [comment]
Open a terminal and run `rm -rf ~/Library/Application\ Support/Championify/`. This will delete the Championify config folder. After try running and let me know if it works.

**Comment by Emolus** [comment]
Tried it out, didn't work :(. I noticed that for a split second Lolflavor version said "Loading..." too then changed to "Unknown", the other 2 keep on "Loading". Even "Item Sets Version" is in "Unknown". 
![screen shot 2016-06-09 at 6 41 11 pm](https://cloud.githubusercontent.com/assets/12462224/15950134/c4221f40-2e71-11e6-908d-c46e055137be.png)

**Comment by dustinblackman** [comment]
There isn't much else I can help with unfortunately. What you did was the equivalent of a full reinstall. Something on your Mac or network is blocking those domains or the app itself.
