### ISSUE TITLE
Something just broke 

### ISSUE THREAD

**Issue by TimeToFlash** [dustinblackman/Championify#195]
![screenshot_49](https://cloud.githubusercontent.com/assets/19855654/15962254/fb1dc786-2f09-11e6-9d3a-7b4f19d51dd2.png)
I have problem i tried to reinstall league but it doesnt works...
Help me pls!

**Comment by dustinblackman** [comment]
Looks like something broke mid update. Network maybe. Either way this will fix it.

https://github.com/dustinblackman/Championify/blob/master/FAQ.md#the-app-opens-with-a-white-box-infinite-loops-i-just-see-the-background-or-nothing-happens
