### ISSUE TITLE
the launcher doesn't work

### ISSUE THREAD

**Issue by Thrmal** [dustinblackman/Championify#196]
![f910138b4c1d4641839ccfa1e469d298](https://cloud.githubusercontent.com/assets/19973718/16114846/bf1c90b4-33c3-11e6-9698-5014d5296a3b.png)
Hi, This is what happened when i tried to run championify (btw sorry for my bad english im french^^)

**Comment by dustinblackman** [comment]
Odd, something went wrong with your installation. Give this a shot, otherwise reinstall.

https://github.com/dustinblackman/Championify/blob/master/FAQ.md#the-app-opens-with-a-white-box-infinite-loops-i-just-see-the-background-or-nothing-happens

**Comment by xFaith17** [comment]
I also get this error : 
![screenshot_1](https://cloud.githubusercontent.com/assets/20399923/16732335/e868ce16-477c-11e6-98bc-2f5a3481a184.png)

I tried deleting the appdata files and tried reinstalling. I tried everything. I still get this error.
I also can't delete older Item sets - i still have Patch 6.4 Itemsets and I can't get rid of them. any solution on this?

**Comment by dustinblackman** [comment]
You can delete old item sets manually by removing them in the League directory. As for this error it looks like something went wrong during installation as files are missing.
