### ISSUE TITLE
Blankscreen after i load it up

### ISSUE THREAD

**Issue by Aolynk69** [dustinblackman/Championify#197]
https://gyazo.com/2201d5a756744c95b0630d8b0ce3c009 
This is the screen i get everytime i load the new update and nothing seems to help it ive removed the program from my computer and tryed a fresh install but nothing works and even going back to a older version it is still the same

**Comment by dustinblackman** [comment]
https://github.com/dustinblackman/Championify/blob/master/FAQ.md#the-app-opens-with-a-white-box-infinite-loops-i-just-see-the-background-or-nothing-happens
