### ISSUE TITLE
Create 2 separeted items sets

### ISSUE THREAD

**Issue by philippsander** [dustinblackman/Championify#2]
I'd like it more if there would be one for the highest winrate, and one for the most common build.

good work tho :-) I'll try to contribute

**Comment by dustinblackman** [comment]
Do you mean instead of having two starters and two builds, just one of each?

**Comment by arunsakthi** [comment]
I agree with the issue, if you can have 2 separate item lists for every champ. In that case, it'll have seperate itemsets that I can see in Items section in LOL launcher. Right now, I use mac and cant see your itemset's there. Are you just updating the recommended builds ?.

**Comment by dustinblackman** [comment]
You two still have me lost. There currently IS TWO item sets. Most Win Rate AND Frequent. And yes I'm just updating Recommended builds as builds within the launcher are encoded and stored elsewhere.

**Comment by arunsakthi** [comment]
My bad, i just saw it for in game. It works fine even in same itemset for me. Is there a reason why we cant see your itemsets outside, in case if we wanna edit it ?.

**Comment by dustinblackman** [comment]
Unfortunately it's a Riot thing. It used to be possible back in the day but have since then restricted it.

**Comment by arunsakthi** [comment]
Thx, nice to know.

**Comment by dustinblackman** [comment]
Fixed in GUI release.
