### ISSUE TITLE
Launching Championify causes it to spawn mulitple processes of itself

### ISSUE THREAD

**Issue by Nefari0uss** [dustinblackman/Championify#205]
I believe it has to do with the fact that there's a new update for Championify? It attempts to download it and then it creates more and more processes of itself (recursively?). 

Manually installing the latest version over the previous results in the application working. 

I'm running Windows 10 for what it's worth.

**Comment by dustinblackman** [comment]
This is a problem I've had a hard time recreating. It has something to do with incorrect permissions on the Windows system if I'm right. Could you mention what AV you have installed as well, please?

**Comment by Nefari0uss** [comment]
I have Panda AV but there's some weird bug I've got where it thinks it's disabled. 

Could you elaborate a bit more about what you think is the problem and what might cause it. I was opening with administrative privileges so it in theory has executable permissions.

**Comment by Nefari0uss** [comment]
Also, I can try again with 1.3.5 after work today.

**Comment by dustinblackman** [comment]
The current (and a tad dirty) implementation for updating Championify on Windows is executing a batch script that moves files and then restarts the app. The correct permissions are verified before hand, and I have a feeling the script believes it has the correct permissions, reboots, doesn't have them and tries over and over to get them again.

**Comment by Nefari0uss** [comment]
That might be it. It does spawn a cmd window and attempts to run something. It seems like it fails and then tries again.

**Comment by dustinblackman** [comment]
I've planned to write a very small Go application that I can build for OSX and Windows that'll handle updating Championify files, but haven't found the time to do it yet.

**Comment by Nefari0uss** [comment]
[Imgur Link](https://imgur.com/a/Ghb9r)

It very much reminds me of a forkbomb... This happened while trying to update to 1.3.5 from 1.3.4.

**Comment by Radifog** [comment]
I have the same problem right now and I have no idea how to fix it, any ideas? :C

**Comment by dustinblackman** [comment]
@Radifog https://github.com/dustinblackman/Championify/blob/master/FAQ.md#the-app-opens-with-a-white-box-infinite-loops-i-just-see-the-background-or-nothing-happens

**Comment by Radifog** [comment]
@dustinblackman Aw damn, I got over that! Thanks a lot for the reply and for the help, I will try to fix it. Have a nice one! c:

**Comment by dustinblackman** [comment]
Fixed in 2.0.0
