### ISSUE TITLE
Replace update scripts with Go process

### ISSUE THREAD

**Issue by dustinblackman** [dustinblackman/Championify#208]
Replace the current batch and bash update scripts on OSX and Windows with a Golang process to handle the tasks. This should help improve the issues some users experiencing usually concerning permission problems.

**Comment by Nefari0uss** [comment]
Wouldn't this require people to have Go installed or can it be self-bundled?

**Comment by dustinblackman** [comment]
@Nefari0uss Compiles down to a binary, would be bundled in with the application.

**Comment by srs1978** [comment]
@Nefari0uss Go binaries are basically ALWAYS self contained.  This was a central "solution" to the problems Go Lang was solving.

**Comment by Nefari0uss** [comment]
@srs1978 @dustinblackman Ahh, cool! Learned something new.

**Comment by dustinblackman** [comment]
Closing this in favour of http://electron.atom.io/docs/api/auto-updater/
