### ISSUE TITLE
Duplicated Folders

### ISSUE THREAD

**Issue by hermondy** [dustinblackman/Championify#211]
Some champions have 2 folders. Whenever i update the builds it creates a secondary folder just for the Korean builds. If i leave it i wont load the korean build for that champion. I have to move the korean file (.json) to the original folder, the one with no spaces between names. Is it just me ?

**Comment by hermondy** [comment]
![championify_settings](https://cloud.githubusercontent.com/assets/22242037/19963915/eac36bd4-a1a5-11e6-950e-85cb4f219360.jpg)
![riot_champions_folder](https://cloud.githubusercontent.com/assets/22242037/19963914/eac1a1d2-a1a5-11e6-8035-21684b54e570.jpg)

**Comment by dustinblackman** [comment]
Good catch, thanks!

**Comment by hermondy** [comment]
Awesome job Dustin, thanks a lot.
Just updated my builds and its fixed but theres just one more thing. Korean
builds for MonkeyKing sometimes creates a folder named "Wukong". Most of
the times the folder for his Korean build is " Monkey King" but a few times
it is "Wukong".

Just tested and this time it created the folder "Wukong" for the Korean
build. Sorry for not mentioning this before.

2016-11-03 11:54 GMT-02:00 Dustin Blackman <notifications@github.com>:
