### ISSUE TITLE
Add lolalytics.com

### ISSUE THREAD

**Issue by NIDOKING** [dustinblackman/Championify#212]
Hi there!

Could it be possible to add lolalytics.com as a source? Not only they update faster than champion.gg but they also seem to be able to track more regions and offer a little bit more options, all of them under the Platinum+ range. Take Ezreal, the most picked champion in 6.19 according to the site as an example:

http://current.lolalytics.com/champion/Ezreal/

How easy would it be to code and arrange something using that data? Hope it's possible, since the site is quite good.

Keep up the good work!

**Comment by NIDOKING** [comment]
How can someone help without knowledge of programming whatsoever?

**Comment by dustinblackman** [comment]
@NIDOKING To get this task done? Nothing unfortunately.

**Comment by NIDOKING** [comment]
Ah, shame then. Guess I'll only be helpful if there's something minor to save you some time. I'll be around.

**Comment by dustinblackman** [comment]
Appreciated!

**Comment by WereGoingOcean** [comment]
Looking at how lolalytics gives their build data. Would you want to keep all the rows (i.e. first item, second item, third item, etc.) and basically have two of each where one is sorted by popularity and the other by win rate? 

I'm working on getting all the data parsed from the champion page right now and just trying to figure out how it will be formatted in the final build.

**Comment by dustinblackman** [comment]
Yep that sounds right to me, so it's similar to how Champion.gg works!

**Comment by WereGoingOcean** [comment]
How should missing translations be handled? Example is block titles from lolalytics like 'First item', 'Second item', etc.

**Comment by dustinblackman** [comment]
@WereGoingOcean Hmm, this should be something I should have in the contribution doc, but simply enter entries for `i18n/_source.json` and `i18n/en.json`, and I'll translate after merging the PR. Don't worry about the keys being in order, the translation scripts will handle it afterwards.

**Comment by NIDOKING** [comment]
I'll drop a comment to say I'm extremely happy to see this is being worked on. So again, since I can't offer anything but support, have another cheering from my side!
