### ISSUE TITLE
Talon has no item set in-game

### ISSUE THREAD

**Issue by bmahler0406** [dustinblackman/Championify#214]
After using Championify, when I check the Riot Games\League of Legends\Config\Champions for Talon the Recommended folder is empty.

**Comment by dustinblackman** [comment]
I just did a fresh import this morning and Talon's builds generated just fine. No errors come up while importing?

**Comment by bmahler0406** [comment]
None. I'm using KoreanBuilds. During the download/processing phase, under status, it says Processing Koreanbuilds for every champion except Talon.

**Comment by dustinblackman** [comment]
Ah, I had done the test against Champion.gg. That makes sense. :)
