### ISSUE TITLE
[Request] Mobafire.com service

### ISSUE THREAD

**Issue by Gelo3D** [dustinblackman/Championify#218]
In my opinion mobafire is really good service with build and tips for champ, playing etc. 
Pls add support mobafire thx a lot !

**Comment by dustinblackman** [comment]
The issue with mobafire is the guides aren't standardize as they're all created by people, meaning scraping for them is very, very hard. If someone wishes to attempt it, they're more then welcome and I'll gladly accept the PR, but I'm not putting this on the roadmap. Sorry.
