### ISSUE TITLE
PC Crash when importing itemset.

### ISSUE THREAD

**Issue by Redapel** [dustinblackman/Championify#219]
**Using :**

- Windows 10
- Garena 
- Championify 1.3.8

![capture](https://cloud.githubusercontent.com/assets/23622466/20468597/124a5c04-afd3-11e6-9819-e5e922ec27c0.PNG)

**Comment by dustinblackman** [comment]
Crash? As in shuts down completely just be pressing import? That would be a first as the app is simply doing http requests and parsing.

**Comment by Redapel** [comment]
Yes, my computer shutdowns when championify is processing. 
Though, sometimes it works fine but not often.

**Comment by dustinblackman** [comment]
@Redapel That sounds more like something is wrong with your computer more then Championify. Championify is making a lot of requests at once, especially if you have more then one source selected. If you're getting some form of a blue screen, I'd suggest looking in to that more to see if you're having network card or network driver issues.
