### ISSUE TITLE
A JavaScript Error occurred in the main process.

### ISSUE THREAD

**Issue by KilogramHours** [dustinblackman/Championify#220]
I can't open Championify. Every time I try I get this JavaScript Error. I tried uninstalling it and using the ZIP file on windows to no avail.
 
http://i.imgur.com/34Gpard.png

I blacked out my name for privacy reasons of course.

**Comment by dustinblackman** [comment]
@KilogramHours This happens on boot? Not during an import or anything like that? And you're using the zip of the latest version (1.3.8)?

**Comment by KilogramHours** [comment]
Yep. It happens when I boot Championify and I did download the latest version.

**Comment by dustinblackman** [comment]
@KilogramHours I just did tested the latest builds again on a fresh windows 10 system and am not seeing the problem. What AV are you running?

**Comment by sephtin** [comment]
I have no issues on Win10.
What version of Java are you using?
Have you tried updating or reinstalling Java?

The only other thing that stands out to me are the apostrophe's (') in the path.
If you move the directory from downloads to your C drive, do you still get the error? (I keep mine in a folder called C:\Apps\).

**Comment by dustinblackman** [comment]
Java? O.o There's no Java here. The application is in Javascript and is completely self contained, it doesn't require dependencies.

**Comment by sephtin** [comment]
My bad.  Over thinking... I was thinking of conflicts or version issues, not the case then!

**Comment by InfamousKing13** [comment]
im having the same issues as him https://gyazo.com/59497d3650bc9e31dbcfab3c31201c17

**Comment by InfamousKing13** [comment]
ive reinstalled everything also deleted and reinstalled nothing fixes it and ive reinstalled java as well

**Comment by KilogramHours** [comment]
Yeah I've uninstalled League of Legends and JavaScript and it still doesn't work. So I don't know what to do. But I was wondering if there was a way to delete the outdated Item Sets from my client? Because I can't seem to remove them since they are tied to my account.

**Comment by Nefari0uss** [comment]
@dustinblackman - [This](http://stackoverflow.com/questions/26117752/errno-34-code-enoent) stack over flow link seems to say that the error indicates a path doesn't exist. 

@InfamousKing13 @KilogramHours Have you tried running the application as an administrator? Don't quite think it'll fix anything but I figure it can't hurt to rule it out.

**Comment by dustinblackman** [comment]
I already have it patched, it'll be fixed in the next version. Item sets can be deleted from C:\League of Legends\Config\Champions if I remember right

**Comment by Nefari0uss** [comment]
Oh cool. What was the fix?

**Comment by dustinblackman** [comment]
@Nefari0uss I added a external dependancy to elevate Championify when needed. See the change log. https://github.com/dustinblackman/Championify/blob/master/CHANGELOG.md#200-december-21st-2016
