### ISSUE TITLE
Add compile instructions for node-6-rework

### ISSUE THREAD

**Issue by LuaTenshi** [dustinblackman/Championify#225]
Would it be possible to add some instructions on how to compile and run the node-6-rework for testing?
So that people can start giving feedback without the risk of giving the wrong info because they didn't compile/run it correctly.

I also really want to try the latest version and see how it works out. :)

**Comment by dustinblackman** [comment]
@LuaTenshi Works the same as master branch, other then you use node 6 instead. 

```
nvm install 6
nvm use 6
npm i
npm run dev
```
