### ISSUE TITLE
Reinstalled LoL to new Drive, now Championify crashes when I try to update.

### ISSUE THREAD

**Issue by xAlfakynx** [dustinblackman/Championify#227]
I set the the directory to D:\Riot Games\League of Legends but now it can't install the item sets

**Comment by xAlfakynx** [comment]
It quickly shows ":'( Can't get Riot Version"

**Comment by dustinblackman** [comment]
Riot's API has expired certs, causing anything using their API to break. You can monitor status here. https://developer.riotgames.com/discussion/community-discussion/show/oJli5iPR
