### ISSUE TITLE
My championify is not running

### ISSUE THREAD

**Issue by Thrmal** [dustinblackman/Championify#235]
Hello, the app opens with the background image but this is it, i don't see the others features in it, thank you for your answer.
![7be862df332d469aaa446f89bbe46cd2](https://cloud.githubusercontent.com/assets/19973718/21427591/aca77b16-c855-11e6-82af-3141176f4877.png)

**Comment by dustinblackman** [comment]
You haven't upgraded yet I'm assuming? See breaking changes. https://github.com/dustinblackman/Championify/releases/tag/2.0.0
