### ISSUE TITLE
Transformed items not reverted to regular items

### ISSUE THREAD

**Issue by Apfelmann** [dustinblackman/Championify#238]
Some user reported to me on koreansbuilds.net that items like Serph's Embrace or Muramana are not transformed back into their untransformed verision and therefore do not show up in the ingame builds created by championify

**Comment by dustinblackman** [comment]
@Apfelmann If I understand correctly digging around, Seraphs Embrace and Muramana are the only two items that transform?

**Comment by Apfelmann** [comment]
@dustinblackman that is indeed correct

**Comment by funnymanpatrick** [comment]
Poacher's Dirk also transforms now.

**Comment by Nefari0uss** [comment]
Honest question - is this really an issue? For any completed item you'd click on the item then buy the components on the right hand side. This would do the same wouldn't it? Click on Seraph's Embrace or Muramana and it'll show the full build on the right hand side including the transformed item itself?

**Comment by dustinblackman** [comment]
Same issue happens with Molten's Edge.
