### ISSUE TITLE
Make main championify.exe take command line arguments

### ISSUE THREAD

**Issue by festinuz** [dustinblackman/Championify#240]
Currently, if you try to pass command line arguments to the `...\Championify\championify.exe`, nothing happens, and in order to use command line arguments you need to call 
`...\Championify\app-LATEST\championify.exe` with desired command line arguments.

From my understanding, the first one is considered a main one, which calls the later one. I assume this since shortucts created by installation target main _.exe_ file.

I suggest passing command line arguments from the main _.exe_ to the version _.exe_, so users could edit a shortcut once instead of fixing it with every new version of the program.

**Comment by dustinblackman** [comment]
The main exe is created by Squirrels. Issues are open to add support for it, but isn't done yet.

**Comment by festinuz** [comment]
It was made clear to me that the issue comes from a _Squirrels_ library, on which this program is built upon. Hopefuly the devs of _Squirrels_ will fix it some time soon.

Thanks for a prompt reply.

**Comment by dustinblackman** [comment]
@festinuz I went digging through Squirrels source code and found a solution, I've updated the docs.

**Comment by festinuz** [comment]
Superbly done! Thank you for your work!
