### ISSUE TITLE
ETimedout while trying to add all Builds.

### ISSUE THREAD

**Issue by Brelvor** [dustinblackman/Championify#241]
Hey like one of the last Issues here reported, i also have the Problem that i get the ETIMEDOUT message after a certain Percentage (Around 30-40%). I tried already everything: i even deactivated my avira and my firewall, with no success. Here is a example screen.

![image](https://cloud.githubusercontent.com/assets/24763028/21470977/3098a3d6-caa0-11e6-8ab3-ea35561aee8c.png)
![image](https://cloud.githubusercontent.com/assets/24763028/21470978/43b45690-caa0-11e6-828c-44e7b13bc010.png)
I also sent you my whole log, maybe you can find something out. I think it would work if i don't add all ressources at one time but i would love to see a fix for this. 
I hope you can help me with this Problem and sorry for my bad english.
[championify.log.txt](https://github.com/dustinblackman/Championify/files/672171/championify.log.txt)

**Comment by dustinblackman** [comment]
Dup https://github.com/dustinblackman/Championify/issues/237
