### ISSUE TITLE
Norton keeps deleting the "node.dll"

### ISSUE THREAD

**Issue by Yo0o** [dustinblackman/Championify#242]
title says it all :) I try to start the championify.exe and Norton instantly deletes my node.dll

**Comment by dustinblackman** [comment]
@Yo0o What happens if you were to download Electron (what Championify is built on top of)?  `node.dll` is from that. https://github.com/electron/electron/releases/download/v1.4.13/electron-v1.4.13-win32-ia32.zip

**Comment by Yo0o** [comment]
Norton's deleting it aswell as soon as I run the .exe

**Comment by Ra1d3n** [comment]
Avira does this as well.

**Comment by dustinblackman** [comment]
I'll find time to download Norton over the holiday and see what comes up and report it back to the Electron team. Avira I have no plans on trying to fix, that AV is more trouble then it's worth.

**Comment by Ra1d3n** [comment]
Avira is detecting the packer with a generic pattern it seems.

The pattern reported is "TR/Crypt.ZPACK.Gen". If anybody is interested.

![avcenter_2016-12-28_22-11-32](https://cloud.githubusercontent.com/assets/1708378/21531730/a802864c-cd4a-11e6-9688-2179f14acf71.png)

**Comment by dustinblackman** [comment]
False positive from Squirrels.

**Comment by dustinblackman** [comment]
Stale, closing.
