### ISSUE TITLE
"Can't access Github package.json" error suddenly appeared and unable to open log

### ISSUE THREAD

**Issue by Anarchly** [dustinblackman/Championify#243]
After using Championify for a few months I recently started receiving this error everytime I run the application immediately making it completely impossible to update the program or my builds.

https://gyazo.com/e30f9f2b65151e9080660ced72da1462

In addition to this clicking "open log" provides no response and I'm unable to do anything else.

My internet has been running fine, I've also tried entirely disabling my antivirus and running the program as administrator and reinstalling the program. Any help would be appreciated.

**Comment by limtindsay** [comment]
I am also getting this issue out of the blue, would appreciate some input. My firewall is not blocking it!

**Comment by dustinblackman** [comment]
Not a bug. See breaking changes in the 2.0.0 change log and download the latest release. https://github.com/dustinblackman/Championify/blob/master/CHANGELOG.md#200-december-21st-2016
