### ISSUE TITLE
Virustotal flagging for PUA.Shopper on Windows 2.0.1 setup file

### ISSUE THREAD

**Issue by dimino** [dustinblackman/Championify#244]
https://www.virustotal.com/en/file/0a87c74f9c731ab523056e3db2063ee56ae00560c6e6c58266c902238b2004c6/analysis/

Also, link is broken in README.md.

Both things together seem pretty fishy...

**Comment by dustinblackman** [comment]
I fixed the link in on the release page, there was a new line in it by accident. And that's a false positive, which are expected.

**Comment by dimino** [comment]
Why is PUA.Shopper expected?

**Comment by dustinblackman** [comment]
@dimino False positives are expected.

**Comment by dimino** [comment]
What is it flagging, though?

**Comment by dustinblackman** [comment]
Something in Squirrels.

**Comment by dimino** [comment]
Looks like you need to do this to stop triggering the false positive:

https://github.com/Squirrel/Squirrel.Windows/issues/786#issuecomment-237299772

**Comment by dustinblackman** [comment]
@dimino The installers are signed, you can check on Windows by right clicking on the executable you can look at digital signatures. If they weren't signed VirusTotal would go something like 10/52.

**Comment by dimino** [comment]
You could fix the singular false positive, is what I'm trying to get across.
