### ISSUE TITLE
Unable to find a valid app

### ISSUE THREAD

**Issue by Karpfador** [dustinblackman/Championify#246]
Got 1.2.10 from the archive and tried running it. When it starts updating I immediately get the following error
Edit: Same with setup version
![image](https://cloud.githubusercontent.com/assets/24807827/21519366/d0af561e-ccec-11e6-93bd-cb9fd791c966.png)

**Comment by dustinblackman** [comment]
What? `1.2.10`? Were at `2.0.1` now. https://github.com/dustinblackman/Championify/releases
