### ISSUE TITLE
One time error: "Cannot call function 'setProgressBar'"

### ISSUE THREAD

**Issue by jblanchard1** [dustinblackman/Championify#247]
I ran Championify just now and experienced this error, which I did not experience when I attempted to run the program again. I was downloading from every source, with every option checked except "Enable Consumables" and "Lock Summoner's Rift Item Sets To Map", which were unchecked. 

In the middle of processing, the error message came up. The error written in the log file was displayed in the window, with a link to the log file. This is the relevant portion of the log file: 

> 2017-01-02T11:04:58.437Z - info: Processing Lolflavor Jungle: Talon
> 2017-01-02T11:04:58.439Z - info: Processing Lolflavor Jungle: Taliyah
> 2017-01-02T11:04:58.517Z - info: Processing Champion.gg: Aurelion Sol
> 2017-01-02T11:04:58.532Z - info: Processing ProBuilds: Zac
> 2017-01-02T11:04:58.534Z - info: Processing Lolflavor Support: Trundle
> 2017-01-02T11:04:58.613Z - info: Processing Lolflavor Support: Thresh
> 2017-01-02T11:04:58.634Z - error:  Error: Cannot call function 'setProgressBar' on missing remote object 6
> Error: Cannot call function 'setProgressBar' on missing remote object 6
>     at throwRPCError (C:\Users\jonathan-run\AppData\Local\Championify\app-2.0.1\resources\electron.asar\browser\rpc-server.js:143:17)
>     at EventEmitter.<anonymous> (C:\Users\jonathan-run\AppData\Local\Championify\app-2.0.1\resources\electron.asar\browser\rpc-server.js:339:7)
>     at emitMany (events.js:127:13)
>     at EventEmitter.emit (events.js:201:7)
>     at WebContents.<anonymous> (C:\Users\jonathan-run\AppData\Local\Championify\app-2.0.1\resources\electron.asar\browser\api\web-contents.js:231:13)
>     at emitTwo (events.js:106:13)
>     at WebContents.emit (events.js:191:7)
>     at metaToValue (C:\Users\jonathan-run\AppData\Local\Championify\app-2.0.1\resources\electron.asar\renderer\api\remote.js:217:13)
>     at remoteMemberFunction (C:\Users\jonathan-run\AppData\Local\Championify\app-2.0.1\resources\electron.asar\renderer\api\remote.js:113:18)
>     at ProgressBar.incr (C:\Users\jonathan-run\AppData\Local\Championify\app-2.0.1\resources\app.asar\js\progressbar.js:50:43)
>     at ProgressBar.incrChamp (C:\Users\jonathan-run\AppData\Local\Championify\app-2.0.1\resources\app.asar\js\progressbar.js:67:10)
>     at _bluebird2.default.join.spread (C:\Users\jonathan-run\AppData\Local\Championify\app-2.0.1\resources\app.asar\js\sources\probuilds.js:117:27)
>     at tryCatcher (C:\Users\jonathan-run\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
>     at Promise._settlePromiseFromHandler (C:\Users\jonathan-run\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\bluebird\js\release\promise.js:507:35)
>     at Promise._settlePromise (C:\Users\jonathan-run\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\bluebird\js\release\promise.js:567:18)
>     at Promise._settlePromise0 (C:\Users\jonathan-run\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\bluebird\js\release\promise.js:612:10)
>     at Promise._settlePromises (C:\Users\jonathan-run\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\bluebird\js\release\promise.js:691:18)
>     at Promise._fulfill (C:\Users\jonathan-run\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\bluebird\js\release\promise.js:636:18)
>     at PromiseArray._resolve (C:\Users\jonathan-run\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\bluebird\js\release\promise_array.js:125:19)
>     at PromiseArray._promiseFulfilled (C:\Users\jonathan-run\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\bluebird\js\release\promise_array.js:143:14)
>     at PromiseArray._iterate (C:\Users\jonathan-run\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\bluebird\js\release\promise_array.js:113:31)
>     at PromiseArray.init [as _init] (C:\Users\jonathan-run\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\bluebird\js\release\promise_array.js:77:10)
>     at Promise._settlePromise (C:\Users\jonathan-run\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\bluebird\js\release\promise.js:564:21)
> 2017-01-02T11:04:58.656Z - info: Processing Lolflavor Jungle: Tahm Kench
> 2017-01-02T11:04:58.659Z - info: Processing Lolflavor Jungle: Syndra
> 2017-01-02T11:04:58.681Z - info: Processing Champion.gg: Azir
> 2017-01-02T11:04:58.722Z - info: Processing Champion.gg: Bard
> 2017-01-02T11:04:58.724Z - info: Processing Lolflavor Support: Teemo
> 2017-01-02T11:04:58.725Z - info: Processing Lolflavor Jungle: Skarner
> 2017-01-02T11:04:58.727Z - info: Processing Lolflavor ARAM: Tristana
> 2017-01-02T11:04:58.728Z - info: Processing Lolflavor Lane: Twisted Fate
> 2017-01-02T11:04:58.742Z - info: Processing Lolmasters: Yasuo

As you can see, processing continued after the error message appeared, However, it was invisible. The error message remained on the screen while processing continued in the background and apparently completed successfully afterward. 

I have not seen this error before or since, but thought I might submit it just in case.

**Comment by dustinblackman** [comment]
Can't find the commit that had patched this, but it was fixed quite a bit ago and left the issue open by mistake.
