### ISSUE TITLE
Can't access Github package.json

### ISSUE THREAD

**Issue by cupe87** [dustinblackman/Championify#248]
As the title say, after opening championify, it cannot start download the builds but resend me the message this message error. How can i resolve it?
<img width="444" alt="schermata 2017-01-03 alle 12 09 11" src="https://cloud.githubusercontent.com/assets/24892377/21606135/cc1efba2-d1ad-11e6-9ddc-3ed92de1e67f.png">

**Comment by julian-poidevin** [comment]
Hello,

As you can see in the [CHANGELOG](https://github.com/dustinblackman/Championify/releases), starting from release [2.0.0](https://github.com/dustinblackman/Championify/releases/tag/2.0.0), a **manual reinstallation** is required to get Championify working (#205).

I suggest you to download the last version of Championify here : [![Downloads](https://img.shields.io/github/downloads/dustinblackman/Championify/latest/total.svg)](https://github.com/dustinblackman/Championify/releases/latest) and reinstall the program.

**Comment by julian-poidevin** [comment]
@cupe87 is this ok for your so @dustinblackman can close the issue ?
Thanks.

**Comment by dustinblackman** [comment]
Thanks @julian-poidevin !

**Comment by cupe87** [comment]
Yes, sorry, i’ve solide the issue
Thanks again
Marco Meloni


Il giorno 06 gen 2017, alle ore 15:41, Dustin Blackman <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Thanks @julian-poidevin<https://github.com/julian-poidevin> !
