### ISSUE TITLE
Make the item set title be accurate

### ISSUE THREAD

**Issue by rafaeldamasceno** [dustinblackman/Championify#25]
First, I don't know why it is called 5.x.1. Why is there the .1 there? Second, I'm playing 5.9, but the builds are from 5.8 and should be labelled correctly (I think it should be rather easy to scrape the patch version from champion.gg too).

**Comment by rafaeldamasceno** [comment]
While you're at it, capitalize ADC. Adc just feels wrong...

**Comment by dustinblackman** [comment]
Version number will be fixed in https://github.com/dustinblackman/Championify/issues/17
ADC formatting I shall add to new versioin.
