### ISSUE TITLE
Avira automatically delete the program

### ISSUE THREAD

**Issue by skizz98** [dustinblackman/Championify#250]
I have Avira Free updated with the latest patch and with Championify 2.0.1 I can only download builds one time and then Championify , even if I had it to the ignore list, gets deleted

**Comment by julian-poidevin** [comment]
Hello,

I just submitted to Avira a request of **Suspected False Positive**.

You can track the status of the request here : https://analysis.avira.com/en/status?uniqueid=3mbVVH4E5FIhSdtnrX9WD1HFNxEyfO6L&incidentid=2124494

**Comment by skizz98** [comment]
Didn't know I can submit false positive to them. Thank you..I feel stupid now :c

**Comment by dustinblackman** [comment]
Thanks for the submission. I'm half tempted to add it to my release flow to auto submit.

**Comment by dustinblackman** [comment]
@julian-poidevin Do you know if Avira whitelists the application in all their clients after submission? Their list must be massive so I slightly doubt it, but I've never had the experience before.

**Comment by julian-poidevin** [comment]
@dustinblackman I have no clue... I sent a tweet to Avira Support to get more information.

Also I found [this thread](https://answers.avira.com/en/question/what-should-i-do-in-case-of-a-confirmed-false-positive-from-avira-10266?sh=true) on their online support plateform which tells 
> But because Avira software treats the respective file as it were a real virus __**(until the next update)**__

This probably means the database is continually updated with false positive reports.

**Comment by julian-poidevin** [comment]
Avira support just answered me, if a file is detected as "clean" it will be added to their whitelist :

>![capture d ecran 2017-01-06 a 22 28 03](https://cloud.githubusercontent.com/assets/8756421/21733620/bda444a6-d45f-11e6-8f78-afb4b5ec86a1.png)

Not sure if you need to submit every new release executable of Championify though :confused:.

**Comment by dustinblackman** [comment]
Wow, you're brilliant, thanks for that! And I most likely will. I'm assuming they're doing a checksum, meaning anytime I change anything the checksum will change. I don't mind submitting every release, I'll just automate it. Most AVs get daily updates, so a very small amount of users would be effected with false positive warnings.

**Comment by Nefari0uss** [comment]
Might be worth doing a [VirusTotal](https://www.virustotal.com/) upload and report and attaching one to each release. If there are any more false positives, you'll know much earlier.

**Comment by dustinblackman** [comment]
@Nefari0uss Every release has virus total reports. They've been there for roughly the last year.

**Comment by Nefari0uss** [comment]
*checks again*

Oops. How did I miss them. My bad.

**Comment by julian-poidevin** [comment]
@dustinblackman I tried to get more information from Avira Support, apparently you only need to submit the file once :smiley: :

>![capture d ecran 2017-01-07 a 12 43 56](https://cloud.githubusercontent.com/assets/8756421/21741477/1f50be74-d4d7-11e6-8602-25d8468d9eb0.png)

I think the issue can be closed then.

**Comment by dustinblackman** [comment]
So it's not checksums... That's weird, I have no idea how they're doing it, but I suppose we'll wait and see after I push another release. If Avira pops up with more false positives, I'll add it to the release flow. 

Closing this, thanks all.
