### ISSUE TITLE
Every time the program starts it crashes and needs to be manually reinstalled.

### ISSUE THREAD

**Issue by GijonDev** [dustinblackman/Championify#251]
Needs to be reinstalled after every PC restart or shows a white screen.

**Comment by julian-poidevin** [comment]
To have more information : can you please post the log file : `championify.log.txt` ?

**Comment by dustinblackman** [comment]
The log can be found in C:/Users/YOURNAME/AppData/Roaming/Championify

**Comment by GijonDev** [comment]
[championify.log.txt](https://github.com/dustinblackman/Championify/files/699610/championify.log.txt)
Note that this only happens when talking about .zip version (works fluently on installed version) (32bit)

**Comment by dustinblackman** [comment]
@GijonDev That log seems to of been generated after you run the installed version then. Can you boot the zipped version and then pass me the log? It should be longer then that.

**Comment by GijonDev** [comment]
I deleted the \Roaming\Championify folder and only this files were generated when running the zip version: 

- GPUCache
- Preferences

**Comment by dustinblackman** [comment]
After running it the log should end up there as well.

**Comment by dustinblackman** [comment]
@GijonDev Still having issues?

**Comment by GijonDev** [comment]
deleted zip and using fluently installed version. but you can i've already posted another issue :/

https://github.com/dustinblackman/Championify/issues/289
