### ISSUE TITLE
runas.node not found

### ISSUE THREAD

**Issue by InfamousKing13** [dustinblackman/Championify#253]
When last updated the app opens and it shows like this and it does the same thing reintstalled or ran as admin and I am unable to use it https://gyazo.com/20c969d2ce293dad96897cc7e93bfafe

**Comment by dustinblackman** [comment]
@InfamousKing13 Can you paste your log here, please? You can find it in `C:/Users/YOURNAME/AppData/Roaming/Championify/championify.log.txt`

**Comment by InfamousKing13** [comment]
2017-01-09T23:40:53.781Z - error:  UncaughtException
    at Log.exitOnError (C:\Users\Leo\AppData\Local\Championify\app-2.0.1\resources\app.asar\js\logger.js:57:9)
    at Logger._uncaughtException (C:\Users\Leo\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\winston\lib\winston\logger.js:645:12)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at window.onerror (C:\Users\Leo\AppData\Local\Championify\app-2.0.1\resources\electron.asar\renderer\init.js:120:22)
Cause: Error: ENOENT, node_modules\runas\build\Release\runas.node not found in C:\Users\Leo\AppData\Local\Championify\app-2.0.1\resources\app.asar
    at notFoundError (ELECTRON_ASAR.js:115:19)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:183:9)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Leo\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\runas\lib\runas.js:4:11)
    at Object.<anonymous> (C:\Users\Leo\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\runas\lib\runas.js:47:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
2017-01-09T23:40:53.784Z - error: uncaughtException: ENOENT, node_modules\runas\build\Release\runas.node not found in C:\Users\Leo\AppData\Local\Championify\app-2.0.1\resources\app.asar 
{ date: 'Mon Jan 09 2017 17:40:53 GMT-0600 (Central Standard Time)',
  process: 
   { pid: 14568,
     uid: null,
     gid: null,
     cwd: 'C:\\Users\\Leo\\AppData\\Local\\Championify\\app-2.0.1',
     execPath: 'C:\\Users\\Leo\\AppData\\Local\\Championify\\app-2.0.1\\championify.exe',
     version: 'v6.5.0',
     argv: 
      [ 'C:\\Users\\Leo\\AppData\\Local\\Championify\\app-2.0.1\\championify.exe',
        '--type=renderer',
        '--no-sandbox',
        '--primordial-pipe-token=68E191CEEB0E30E6AC6C3D09A29B173D',
        '--lang=en-US',
        '--app-user-model-id=com.squirrel.Championify.championify',
        '--node-integration=true',
        '--hidden-page',
        '--enable-pinch',
        '--device-scale-factor=1',
        '--num-raster-threads=2',
        '--content-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553',
        '--video-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553',
        '--mojo-channel-token=6FBA84FD717882A19407BA909ABE2A0F',
        '--mojo-application-channel-token=68E191CEEB0E30E6AC6C3D09A29B173D',
        '--channel=10888.1.1481660371\\1164836236',
        '--mojo-platform-channel-handle=1772',
        '/prefetch:1' ],
     memoryUsage: { rss: 83275776, heapTotal: 42688512, heapUsed: 26720600 } },
  os: { loadavg: [ 0, 0, 0 ], uptime: 438970.0335005 },
  trace: 
   [ { column: 19,
       file: 'ELECTRON_ASAR.js',
       function: 'notFoundError',
       line: 115,
       method: null,
       native: false },
     { column: 9,
       file: 'ELECTRON_ASAR.js',
       function: 'Object.module.(anonymous function) [as .node]',
       line: 183,
       method: 'module.(anonymous function) [as .node]',
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module.load',
       line: 473,
       method: 'load',
       native: false },
     { column: 12,
       file: 'module.js',
       function: 'tryModuleLoad',
       line: 432,
       method: null,
       native: false },
     { column: 3,
       file: 'module.js',
       function: 'Function.Module._load',
       line: 424,
       method: 'Module._load',
       native: false },
     { column: 17,
       file: 'module.js',
       function: 'Module.require',
       line: 483,
       method: 'require',
       native: false },
     { column: 19,
       file: 'internal/module.js',
       function: 'require',
       line: 20,
       method: null,
       native: false },
     { column: 11,
       file: 'C:\\Users\\Leo\\AppData\\Local\\Championify\\app-2.0.1\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js',
       function: '',
       line: 4,
       method: null,
       native: false },
     { column: 4,
       file: 'C:\\Users\\Leo\\AppData\\Local\\Championify\\app-2.0.1\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js',
       function: '',
       line: 47,
       method: null,
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module._compile',
       line: 556,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Object.Module._extensions..js',
       line: 565,
       method: 'Module._extensions..js',
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module.load',
       line: 473,
       method: 'load',
       native: false },
     { column: 12,
       file: 'module.js',
       function: 'tryModuleLoad',
       line: 432,
       method: null,
       native: false },
     { column: 3,
       file: 'module.js',
       function: 'Function.Module._load',
       line: 424,
       method: 'Module._load',
       native: false },
     { column: 17,
       file: 'module.js',
       function: 'Module.require',
       line: 483,
       method: 'require',
       native: false },
     { column: 19,
       file: 'internal/module.js',
       function: 'require',
       line: 20,
       method: null,
       native: false } ],
  stack: 
   [ 'Error: ENOENT, node_modules\\runas\\build\\Release\\runas.node not found in C:\\Users\\Leo\\AppData\\Local\\Championify\\app-2.0.1\\resources\\app.asar',
     '    at notFoundError (ELECTRON_ASAR.js:115:19)',
     '    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:183:9)',
     '    at Module.load (module.js:473:32)',
     '    at tryModuleLoad (module.js:432:12)',
     '    at Function.Module._load (module.js:424:3)',
     '    at Module.require (module.js:483:17)',
     '    at require (internal/module.js:20:19)',
     '    at Object.<anonymous> (C:\\Users\\Leo\\AppData\\Local\\Championify\\app-2.0.1\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js:4:11)',
     '    at Object.<anonymous> (C:\\Users\\Leo\\AppData\\Local\\Championify\\app-2.0.1\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js:47:4)',
     '    at Module._compile (module.js:556:32)',
     '    at Object.Module._extensions..js (module.js:565:10)',
     '    at Module.load (module.js:473:32)',
     '    at tryModuleLoad (module.js:432:12)',
     '    at Function.Module._load (module.js:424:3)',
     '    at Module.require (module.js:483:17)',
     '    at require (internal/module.js:20:19)' ] }

**Comment by dustinblackman** [comment]
What OS? Windows 10 64 bit?

**Comment by InfamousKing13** [comment]
yes

**Comment by dustinblackman** [comment]
This issue was solved with https://github.com/dustinblackman/Championify/issues/220, but I unfortunately reintroduced in https://github.com/dustinblackman/Championify/issues/239. I haven't been able to replicate it locally. However I'll attempt again.

**Comment by InfamousKing13** [comment]
dam sounds like i wont be able to use it for a while than fml lol

**Comment by dustinblackman** [comment]
@InfamousKing13 @KilogramHours What AV are you running? I have a feeling it's deleting the file.

**Comment by KilogramHours** [comment]
I just have Windows Defender.

**Comment by dustinblackman** [comment]
Weird. I've tested a fully updated Windows Defender running on Windows 10, and I still can't reproduce. I'll have to keep trying.

**Comment by KilogramHours** [comment]
I'm still having the issue where Championify starts, but it is a blank page with the gray background with Jinx and Vi. 

I've tried to reinstall Championify, even the new version, and also completely erased and reinstalled League of Legends itself and it hasn't worked. Also tried to Run as Administrator and also nothing.

Can't figure out for the life of me why it is happening. Without the updated Item Sets that Championify gives me the game just feels worse.

**Comment by dustinblackman** [comment]
@KilogramHours If you're experiencing a blank background, please open a new issue with your log file output.

**Comment by InfamousKing13** [comment]
has this been fixed or no?

**Comment by KilogramHours** [comment]
Nope it still isn't fixed, at least for me. Sucks because I really liked the application and it was really useful for staying up to date on the recent builds.

**Comment by KilogramHours** [comment]
Yep. Even after two new updates I still have the issue of it not starting, only showing the blank screen. I feel like I'm never going to be able to use Championify again, which really sucks.

**Comment by dustinblackman** [comment]
Closing as stale, a good amount has changed for elevation since this issue. Those still having the issue can open a new one if they're still experiencing issues.
