### ISSUE TITLE
When I open Championify only the picture of Jinx and Vi appears with nothing else.

### ISSUE THREAD

**Issue by KilogramHours** [dustinblackman/Championify#255]
When I open Championify this image just pops up after 5 seconds or so, and nothing happens. I don't know what to do. I reinstalled it four times by using the exe and zip versions for Windows and it hasn't worked. 

I'm on Windows 10 if that matters.

http://i.imgur.com/G5BgD0l.png

**Comment by julian-poidevin** [comment]
As reported in [FAQ.md](https://github.com/dustinblackman/Championify/blob/master/FAQ.md) :
 > #### The app opens with a white box, infinite loops, I just see the background, or nothing happens
>I'm a bit lost why this is happening on some system, as I haven't found any real way to track it or recreate it myself. Delete the following folders depending on your operating system, and then try Championify again.
>__Windows:__ `C:\Users\YOURNAME\AppData\Roaming\Championify`
>__OSX:__ `/Users/YOURNAME/Library/Application Support/Championify`

**Comment by dustinblackman** [comment]
Can you post your log please? You can find it in C:/Users/YOURNAME/AppData/Roaming/Championify/championify.log.txt

**Comment by KilogramHours** [comment]
2017-01-14T21:21:08.964Z - error:  UncaughtException
    at Log.exitOnError (C:\Users\Kegan Huntley\Desktop\Kegan's Folder\Kegan's Downloads\Championify\resources\app.asar\js\logger.js:57:9)
    at Logger._uncaughtException (C:\Users\Kegan Huntley\Desktop\Kegan's Folder\Kegan's Downloads\Championify\resources\app.asar\node_modules\winston\lib\winston\logger.js:645:12)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at window.onerror (C:\Users\Kegan Huntley\Desktop\Kegan's Folder\Kegan's Downloads\Championify\resources\electron.asar\renderer\init.js:120:22)
Cause: Error: ENOENT, node_modules\runas\build\Release\runas.node not found in C:\Users\Kegan Huntley\Desktop\Kegan's Folder\Kegan's Downloads\Championify\resources\app.asar
    at notFoundError (ELECTRON_ASAR.js:115:19)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:183:9)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Kegan Huntley\Desktop\Kegan's Folder\Kegan's Downloads\Championify\resources\app.asar\node_modules\runas\lib\runas.js:4:11)
    at Object.<anonymous> (C:\Users\Kegan Huntley\Desktop\Kegan's Folder\Kegan's Downloads\Championify\resources\app.asar\node_modules\runas\lib\runas.js:47:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
2017-01-14T21:21:08.970Z - error: uncaughtException: ENOENT, node_modules\runas\build\Release\runas.node not found in C:\Users\Kegan Huntley\Desktop\Kegan's Folder\Kegan's Downloads\Championify\resources\app.asar 
{ date: 'Sat Jan 14 2017 15:21:08 GMT-0600 (Central Standard Time)',
  process: 
   { pid: 10888,
     uid: null,
     gid: null,
     cwd: 'C:\\Users\\Kegan Huntley\\Desktop\\Kegan\'s Folder\\Kegan\'s Downloads\\Championify',
     execPath: 'C:\\Users\\Kegan Huntley\\Desktop\\Kegan\'s Folder\\Kegan\'s Downloads\\Championify\\championify.exe',
     version: 'v6.5.0',
     argv: 
      [ 'C:\\Users\\Kegan Huntley\\Desktop\\Kegan\'s Folder\\Kegan\'s Downloads\\Championify\\championify.exe',
        '--type=renderer',
        '--no-sandbox',
        '--primordial-pipe-token=5B21B773F40E33F23D2841EFA80976BB',
        '--lang=en-US',
        '--node-integration=true',
        '--hidden-page',
        '--enable-pinch',
        '--device-scale-factor=1',
        '--num-raster-threads=3',
        '--content-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553',
        '--video-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553',
        '--mojo-channel-token=0C6AB551377AA53EE240D6B778BAB65B',
        '--mojo-application-channel-token=5B21B773F40E33F23D2841EFA80976BB',
        '--channel=2864.1.159640783\\1389632509',
        '--mojo-platform-channel-handle=1768',
        '/prefetch:1' ],
     memoryUsage: { rss: 82837504, heapTotal: 41639936, heapUsed: 29557044 } },
  os: { loadavg: [ 0, 0, 0 ], uptime: 296093.0609838 },
  trace: 
   [ { column: 19,
       file: 'ELECTRON_ASAR.js',
       function: 'notFoundError',
       line: 115,
       method: null,
       native: false },
     { column: 9,
       file: 'ELECTRON_ASAR.js',
       function: 'Object.module.(anonymous function) [as .node]',
       line: 183,
       method: 'module.(anonymous function) [as .node]',
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module.load',
       line: 473,
       method: 'load',
       native: false },
     { column: 12,
       file: 'module.js',
       function: 'tryModuleLoad',
       line: 432,
       method: null,
       native: false },
     { column: 3,
       file: 'module.js',
       function: 'Function.Module._load',
       line: 424,
       method: 'Module._load',
       native: false },
     { column: 17,
       file: 'module.js',
       function: 'Module.require',
       line: 483,
       method: 'require',
       native: false },
     { column: 19,
       file: 'internal/module.js',
       function: 'require',
       line: 20,
       method: null,
       native: false },
     { column: 11,
       file: 'Downloads\\Championify\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js',
       function: 'Object.<anonymous> (C:\\Users\\Kegan Huntley\\Desktop\\Kegan\'s Folder\\Kegan\'s',
       line: 4,
       method: '<anonymous> (C:\\Users\\Kegan Huntley\\Desktop\\Kegan\'s Folder\\Kegan\'s',
       native: false },
     { column: 4,
       file: 'Downloads\\Championify\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js',
       function: 'Object.<anonymous> (C:\\Users\\Kegan Huntley\\Desktop\\Kegan\'s Folder\\Kegan\'s',
       line: 47,
       method: '<anonymous> (C:\\Users\\Kegan Huntley\\Desktop\\Kegan\'s Folder\\Kegan\'s',
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module._compile',
       line: 556,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Object.Module._extensions..js',
       line: 565,
       method: 'Module._extensions..js',
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module.load',
       line: 473,
       method: 'load',
       native: false },
     { column: 12,
       file: 'module.js',
       function: 'tryModuleLoad',
       line: 432,
       method: null,
       native: false },
     { column: 3,
       file: 'module.js',
       function: 'Function.Module._load',
       line: 424,
       method: 'Module._load',
       native: false },
     { column: 17,
       file: 'module.js',
       function: 'Module.require',
       line: 483,
       method: 'require',
       native: false },
     { column: 19,
       file: 'internal/module.js',
       function: 'require',
       line: 20,
       method: null,
       native: false } ],
  stack: 
   [ 'Error: ENOENT, node_modules\\runas\\build\\Release\\runas.node not found in C:\\Users\\Kegan Huntley\\Desktop\\Kegan\'s Folder\\Kegan\'s Downloads\\Championify\\resources\\app.asar',
     '    at notFoundError (ELECTRON_ASAR.js:115:19)',
     '    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:183:9)',
     '    at Module.load (module.js:473:32)',
     '    at tryModuleLoad (module.js:432:12)',
     '    at Function.Module._load (module.js:424:3)',
     '    at Module.require (module.js:483:17)',
     '    at require (internal/module.js:20:19)',
     '    at Object.<anonymous> (C:\\Users\\Kegan Huntley\\Desktop\\Kegan\'s Folder\\Kegan\'s Downloads\\Championify\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js:4:11)',
     '    at Object.<anonymous> (C:\\Users\\Kegan Huntley\\Desktop\\Kegan\'s Folder\\Kegan\'s Downloads\\Championify\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js:47:4)',
     '    at Module._compile (module.js:556:32)',
     '    at Object.Module._extensions..js (module.js:565:10)',
     '    at Module.load (module.js:473:32)',
     '    at tryModuleLoad (module.js:432:12)',
     '    at Function.Module._load (module.js:424:3)',
     '    at Module.require (module.js:483:17)',
     '    at require (internal/module.js:20:19)' ] }

**Comment by dustinblackman** [comment]
Dup. https://github.com/dustinblackman/Championify/issues/253
