### ISSUE TITLE
Championify 2 not supported in Mac 10.7.5

### ISSUE THREAD

**Issue by Emolus** [dustinblackman/Championify#26]
An error pops out when trying to open it saying:

"You can't use this version of the application Championify 2 with this version of Mac OS X.

You have Mac OS X 10.7.5 The application requires Mac OS X 10.8 or later."

Is there a way of fixing this? Thanks

**Comment by dustinblackman** [comment]
Good chance there won't be, but I'll take a look.
https://github.com/atom/atom/issues/1967
