### ISSUE TITLE
Most used ItemSet source

### ISSUE THREAD

**Issue by Raydor** [dustinblackman/Championify#260]
There must be people like me that doesn't know much about these itemset websites and which one is better for use.

In my opinion, it would be nice to have a way to see what people choose the most (I tried to import every itemset source but that's a bit crazy) or a way to rate a itemset source so other people can see the total rate of it.

**Comment by dustinblackman** [comment]
While this idea is good, I'm not down to add tracking to Championify in order to produce those stats at the moment. Possibly in the future.
