### ISSUE TITLE
When running the setup all that shows up is this.

### ISSUE THREAD

**Issue by kevin165** [dustinblackman/Championify#263]
Whenever I run the setup or just the actual file i just see an application with no options to click. It is shown here. https://gyazo.com/b421195e063ef1e094bba8b8ca6408cb

**Comment by julian-poidevin** [comment]
Seems like a Dup of #253.

**Comment by kevin165** [comment]
When i run an older version of the software it works for a bit until it finishes updating to the newest version.

**Comment by dustinblackman** [comment]
Can you post your log please? It's located at C:/Users/YOURNAME/AppData/Roaming/Championify/championify.log.txt

**Comment by kevin165** [comment]
I looked for the logs but i dont see anything as the program never finished installing or anything?
Not sure where they would be other than that location.

**Comment by dustinblackman** [comment]
@kevin165 Your screenshot shows that installation was successful. The log should be there as it's done on initialization before the window even shows up.

**Comment by kevin165** [comment]
Attached is a screenshot of my User Folder I dont have a AppData Folder
https://gyazo.com/f75f0061441635440f4729de6e16a4dd

**Comment by kevin165** [comment]
Here is the log.
2017-01-29T06:24:29.236Z - error:  UncaughtException
    at Log.exitOnError (C:\Users\Kevin Flynn\AppData\Local\Championify\app-2.0.1\resources\app.asar\js\logger.js:57:9)
    at Logger._uncaughtException (C:\Users\Kevin Flynn\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\winston\lib\winston\logger.js:645:12)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at window.onerror (C:\Users\Kevin Flynn\AppData\Local\Championify\app-2.0.1\resources\electron.asar\renderer\init.js:120:22)
Cause: Error: Access is denied.
\\?\C:\Users\Kevin Flynn\AppData\Local\Temp\C34A.tmp.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Kevin Flynn\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\runas\lib\runas.js:4:11)
    at Object.<anonymous> (C:\Users\Kevin Flynn\AppData\Local\Championify\app-2.0.1\resources\app.asar\node_modules\runas\lib\runas.js:47:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
2017-01-29T06:24:29.239Z - error: uncaughtException: Access is denied.
\\?\C:\Users\Kevin Flynn\AppData\Local\Temp\C34A.tmp.node 
{ date: 'Sat Jan 28 2017 23:24:29 GMT-0700 (US Mountain Standard Time)',
  process: 
   { pid: 3444,
     uid: null,
     gid: null,
     cwd: 'C:\\Users\\Kevin Flynn\\AppData\\Local\\Championify\\app-2.0.1',
     execPath: 'C:\\Users\\Kevin Flynn\\AppData\\Local\\Championify\\app-2.0.1\\championify.exe',
     version: 'v6.5.0',
     argv: 
      [ 'C:\\Users\\Kevin Flynn\\AppData\\Local\\Championify\\app-2.0.1\\championify.exe',
        '--type=renderer',
        '--no-sandbox',
        '--primordial-pipe-token=4C0B36D602F8247807FB708FBE54D844',
        '--lang=en-US',
        '--app-user-model-id=com.squirrel.Championify.championify',
        '--node-integration=true',
        '--hidden-page',
        '--enable-pinch',
        '--device-scale-factor=1',
        '--num-raster-threads=2',
        '--content-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553',
        '--video-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553',
        '--mojo-channel-token=E1BE879DB9447E07849411E95216DF6D',
        '--mojo-application-channel-token=4C0B36D602F8247807FB708FBE54D844',
        '--channel=5188.1.1181263896\\1174650575',
        '--mojo-platform-channel-handle=1740',
        '/prefetch:1' ],
     memoryUsage: { rss: 82411520, heapTotal: 41639936, heapUsed: 29985712 } },
  os: { loadavg: [ 0, 0, 0 ], uptime: 770.7334356 },
  trace: 
   [ { column: null,
       file: null,
       function: 'Error',
       line: null,
       method: null,
       native: true },
     { column: 20,
       file: 'ELECTRON_ASAR.js',
       function: 'process.module.(anonymous function) [as dlopen]',
       line: 173,
       method: 'module.(anonymous function) [as dlopen]',
       native: false },
     { column: 18,
       file: 'module.js',
       function: 'Object.Module._extensions..node',
       line: 583,
       method: 'Module._extensions..node',
       native: false },
     { column: 18,
       file: 'ELECTRON_ASAR.js',
       function: 'Object.module.(anonymous function) [as .node]',
       line: 187,
       method: 'module.(anonymous function) [as .node]',
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module.load',
       line: 473,
       method: 'load',
       native: false },
     { column: 12,
       file: 'module.js',
       function: 'tryModuleLoad',
       line: 432,
       method: null,
       native: false },
     { column: 3,
       file: 'module.js',
       function: 'Function.Module._load',
       line: 424,
       method: 'Module._load',
       native: false },
     { column: 17,
       file: 'module.js',
       function: 'Module.require',
       line: 483,
       method: 'require',
       native: false },
     { column: 19,
       file: 'internal/module.js',
       function: 'require',
       line: 20,
       method: null,
       native: false },
     { column: 11,
       file: 'Flynn\\AppData\\Local\\Championify\\app-2.0.1\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js',
       function: 'Object.<anonymous> (C:\\Users\\Kevin',
       line: 4,
       method: '<anonymous> (C:\\Users\\Kevin',
       native: false },
     { column: 4,
       file: 'Flynn\\AppData\\Local\\Championify\\app-2.0.1\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js',
       function: 'Object.<anonymous> (C:\\Users\\Kevin',
       line: 47,
       method: '<anonymous> (C:\\Users\\Kevin',
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module._compile',
       line: 556,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Object.Module._extensions..js',
       line: 565,
       method: 'Module._extensions..js',
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module.load',
       line: 473,
       method: 'load',
       native: false },
     { column: 12,
       file: 'module.js',
       function: 'tryModuleLoad',
       line: 432,
       method: null,
       native: false },
     { column: 3,
       file: 'module.js',
       function: 'Function.Module._load',
       line: 424,
       method: 'Module._load',
       native: false } ],
  stack: 
   [ 'Error: Access is denied.\r',
     '\\\\?\\C:\\Users\\Kevin Flynn\\AppData\\Local\\Temp\\C34A.tmp.node',
     '    at Error (native)',
     '    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)',
     '    at Object.Module._extensions..node (module.js:583:18)',
     '    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)',
     '    at Module.load (module.js:473:32)',
     '    at tryModuleLoad (module.js:432:12)',
     '    at Function.Module._load (module.js:424:3)',
     '    at Module.require (module.js:483:17)',
     '    at require (internal/module.js:20:19)',
     '    at Object.<anonymous> (C:\\Users\\Kevin Flynn\\AppData\\Local\\Championify\\app-2.0.1\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js:4:11)',
     '    at Object.<anonymous> (C:\\Users\\Kevin Flynn\\AppData\\Local\\Championify\\app-2.0.1\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js:47:4)',
     '    at Module._compile (module.js:556:32)',
     '    at Object.Module._extensions..js (module.js:565:10)',
     '    at Module.load (module.js:473:32)',
     '    at tryModuleLoad (module.js:432:12)',
     '    at Function.Module._load (module.js:424:3)' ] }

**Comment by kevin165** [comment]
@dustinblackman I solved the issue by choosing a different login which seems to have higher credentials. You can close this issue or delete it. Thank You for the help.

**Comment by KilogramHours** [comment]
@kevin165 How do you do this exactly? I'm having the same issue for weeks, but I don't understand what you mean by choosing a different login to have higher credentials.
