### ISSUE TITLE
numerous (maybe network) issues on mac

### ISSUE THREAD

**Issue by cs117x** [dustinblackman/Championify#264]
Launching championify initially, can't find package.json on github and I should run as admin or disabled firewall, neither worked so I reinstalled and got this far: https://puu.sh/tFa09/11183b6dd3.png

**Comment by dustinblackman** [comment]
Can you submit your log please? It's located at C:/Users/YOURNAME/AppData/Roaming/Championify/championify.log.txt

**Comment by cs117x** [comment]
What about mac directory, I can't find it in application support?

**Comment by dustinblackman** [comment]
`/Users/USER/Library/Application\ Support/Championify/championify.log.txt`

**Comment by cs117x** [comment]
looks like it has been fixed
