### ISSUE TITLE
Freezing on Update

### ISSUE THREAD

**Issue by 4th-Amendment** [dustinblackman/Championify#266]
Update won't go past 66%. Tried running as administrator and re-downloading as well. I've also let it run for 10-15 minutes twice and it didn't finish or crash. It just stayed at 66%.

Here's a Pastbin of the logs I saw you request in another post.
[Roaming Logs](http://pastebin.com/ptFt0EYz)

[Picture of where it stops every time.](https://i.imgur.com/zLMZwSm.png)

Hope a solution comes soon!

**Comment by unseen18** [comment]
I'm having the same issue and it seems to be related to op.gg.Everything else seems to be working fine but it freezes right before processing item sets from op.gg

**Comment by dustinblackman** [comment]
Fixed in https://github.com/dustinblackman/Championify/commit/d2b43460fb30a5548403bd30a7f858fd406ff5b5
