### ISSUE TITLE
Blank Page when Opened

### ISSUE THREAD

**Issue by KilogramHours** [dustinblackman/Championify#270]
Championify Opens, but it is Just a Blank Page with Jinx and Vi in the background. This has been happening for weeks and I haven't been able to figure out the cause of this.

LOG:

{"message":"","stack":"UncaughtException\n    at Log.exitOnError (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify-WIN-2.0.2\\Championify\\resources\\app.asar\\js\\logger.js:57:9)\n    at Logger._uncaughtException (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify-WIN-2.0.2\\Championify\\resources\\app.asar\\node_modules\\winston\\lib\\winston\\logger.js:645:12)\n    at emitOne (events.js:96:13)\n    at process.emit (events.js:188:7)\n    at window.onerror (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify-WIN-2.0.2\\Championify\\resources\\electron.asar\\renderer\\init.js:120:22)\nCause: Error: ENOENT, node_modules\\runas\\build\\Release\\runas.node not found in C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify-WIN-2.0.2\\Championify\\resources\\app.asar\n    at notFoundError (ELECTRON_ASAR.js:115:19)\n    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:183:9)\n    at Module.load (module.js:473:32)\n    at tryModuleLoad (module.js:432:12)\n    at Function.Module._load (module.js:424:3)\n    at Module.require (module.js:483:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify-WIN-2.0.2\\Championify\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js:4:11)\n    at Object.<anonymous> (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify-WIN-2.0.2\\Championify\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js:47:4)\n    at Module._compile (module.js:556:32)\n    at Object.Module._extensions..js (module.js:565:10)\n    at Module.load (module.js:473:32)\n    at tryModuleLoad (module.js:432:12)\n    at Function.Module._load (module.js:424:3)\n    at Module.require (module.js:483:17)\n    at require (internal/module.js:20:19)","type":"UncaughtException","ua":"win32 10.0.14393","locale":"en","cause":{"code":"ENOENT","errno":-2},"rootCause":{"code":"ENOENT","errno":-2},"ownStack":"UncaughtException\n    at Log.exitOnError (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify-WIN-2.0.2\\Championify\\resources\\app.asar\\js\\logger.js:57:9)\n    at Logger._uncaughtException (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify-WIN-2.0.2\\Championify\\resources\\app.asar\\node_modules\\winston\\lib\\winston\\logger.js:645:12)\n    at emitOne (events.js:96:13)\n    at process.emit (events.js:188:7)\n    at window.onerror (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify-WIN-2.0.2\\Championify\\resources\\electron.asar\\renderer\\init.js:120:22)","level":"error","timestamp":"2017-02-05T08:37:49.507Z"}
{"date":"Sun Feb 05 2017 02:37:49 GMT-0600 (Central Standard Time)","process":{"pid":12612,"uid":null,"gid":null,"cwd":"C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify-WIN-2.0.2\\Championify","execPath":"C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify-WIN-2.0.2\\Championify\\championify.exe","version":"v6.5.0","argv":["C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify-WIN-2.0.2\\Championify\\championify.exe","--type=renderer","--no-sandbox","--primordial-pipe-token=47F6C956E256995DAAC77E4B40116668","--lang=en-US","--node-integration=true","--hidden-page","--enable-pinch","--device-scale-factor=1","--num-raster-threads=3","--content-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553","--video-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553","--mojo-channel-token=34E1721FF69E2269C1EE10C7C506CA05","--mojo-application-channel-token=47F6C956E256995DAAC77E4B40116668","--channel=1912.1.130724992\\1594344761","--mojo-platform-channel-handle=1744","/prefetch:1"],"memoryUsage":{"rss":83857408,"heapTotal":42688512,"heapUsed":24346160}},"os":{"loadavg":[0,0,0],"uptime":1073141.5362542},"trace":[{"column":19,"file":"ELECTRON_ASAR.js","function":"notFoundError","line":115,"method":null,"native":false},{"column":9,"file":"ELECTRON_ASAR.js","function":"Object.module.(anonymous function) [as .node]","line":183,"method":"module.(anonymous function) [as .node]","native":false},{"column":32,"file":"module.js","function":"Module.load","line":473,"method":"load","native":false},{"column":12,"file":"module.js","function":"tryModuleLoad","line":432,"method":null,"native":false},{"column":3,"file":"module.js","function":"Function.Module._load","line":424,"method":"Module._load","native":false},{"column":17,"file":"module.js","function":"Module.require","line":483,"method":"require","native":false},{"column":19,"file":"internal/module.js","function":"require","line":20,"method":null,"native":false},{"column":11,"file":"Downloads\\Championify-WIN-2.0.2\\Championify\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js","function":"Object.<anonymous> (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's","line":4,"method":"<anonymous> (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's","native":false},{"column":4,"file":"Downloads\\Championify-WIN-2.0.2\\Championify\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js","function":"Object.<anonymous> (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's","line":47,"method":"<anonymous> (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's","native":false},{"column":32,"file":"module.js","function":"Module._compile","line":556,"method":"_compile","native":false},{"column":10,"file":"module.js","function":"Object.Module._extensions..js","line":565,"method":"Module._extensions..js","native":false},{"column":32,"file":"module.js","function":"Module.load","line":473,"method":"load","native":false},{"column":12,"file":"module.js","function":"tryModuleLoad","line":432,"method":null,"native":false},{"column":3,"file":"module.js","function":"Function.Module._load","line":424,"method":"Module._load","native":false},{"column":17,"file":"module.js","function":"Module.require","line":483,"method":"require","native":false},{"column":19,"file":"internal/module.js","function":"require","line":20,"method":null,"native":false}],"stack":["Error: ENOENT, node_modules\\runas\\build\\Release\\runas.node not found in C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify-WIN-2.0.2\\Championify\\resources\\app.asar","    at notFoundError (ELECTRON_ASAR.js:115:19)","    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:183:9)","    at Module.load (module.js:473:32)","    at tryModuleLoad (module.js:432:12)","    at Function.Module._load (module.js:424:3)","    at Module.require (module.js:483:17)","    at require (internal/module.js:20:19)","    at Object.<anonymous> (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify-WIN-2.0.2\\Championify\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js:4:11)","    at Object.<anonymous> (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify-WIN-2.0.2\\Championify\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js:47:4)","    at Module._compile (module.js:556:32)","    at Object.Module._extensions..js (module.js:565:10)","    at Module.load (module.js:473:32)","    at tryModuleLoad (module.js:432:12)","    at Function.Module._load (module.js:424:3)","    at Module.require (module.js:483:17)","    at require (internal/module.js:20:19)"],"level":"error","message":"uncaughtException: ENOENT, node_modules\\runas\\build\\Release\\runas.node not found in C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify-WIN-2.0.2\\Championify\\resources\\app.asar","timestamp":"2017-02-05T08:37:49.520Z"}

**Comment by dustinblackman** [comment]
Dup. https://github.com/dustinblackman/Championify/issues/253
