### ISSUE TITLE
LoL Version: Loading...

### ISSUE THREAD

**Issue by elseani0** [dustinblackman/Championify#271]
[championify.log.txt](https://github.com/dustinblackman/Championify/files/754772/championify.log.txt)

I've attached the error file if I click Import while it says 'LoL Version: Loading...'

In short, I load Championify as administrator. It gets the versions for all of the item sets I use but never gets the LoL Version. Seems stuck on LoL Version: Loading...

Heres a picture of what I'm seeing.

![image](https://cloud.githubusercontent.com/assets/25586903/22649986/3012c792-ec75-11e6-88dd-e1f74f548397.png)

Any thoughts?

**Comment by dustinblackman** [comment]
Looks like Riot's API endpoint went down for that time as it was 503ing, nothing I can do on my end unfortunately. And glad you like!
