### ISSUE TITLE
Set Items new client

### ISSUE THREAD

**Issue by neojalg** [dustinblackman/Championify#273]
Hey bro.  Do you could create an application look like Championify but customizable for us, since in the new client this isnt implemented by Riot. (Old client "ITEM SETS" funtion isnt available now)

Thanks & sorry for my poor English.

**Comment by julian-poidevin** [comment]
In my opinion, it's not worth developing an application. RIOT will provide the item editor in the client anytime soon.

**Comment by dustinblackman** [comment]
Dup. https://github.com/dustinblackman/Championify/issues/86
