### ISSUE TITLE
Add support for Champion.gg Beta Builds

### ISSUE THREAD

**Issue by complexitydev** [dustinblackman/Championify#274]
The beta builds are updated to current patch a lot faster than the non-beta. Support for these should be nice. Make it an option if champion.gg is selected to have a checkbox "Beta?"

**Comment by dustinblackman** [comment]
The beta stuff looks nice, but I'd rather wait until it's out of beta before integrating it to avoid possible breaking changes being made on Champion.gg's side. I'll keep this issue open for record.

**Comment by evasconcelos** [comment]
@dustinblackman  its officially out : https://www.facebook.com/championgg/posts/703398076486237

**Comment by dustinblackman** [comment]
Looks like Championify supports it out of the box. Champion.gg didn't make any UI changes that broke Championify. This is good to go.
