### ISSUE TITLE
Troubles whit the Process.

### ISSUE THREAD

**Issue by MrMisteriousGuy** [dustinblackman/Championify#279]
I got some problems whit the program.

I loaded "champions.gg" and pressed "import" then, the loading bar has stopped on 50% and said "something broke" "cant get champions.gg version" I tried repeating like 5 times and nothing worked.

**Comment by dustinblackman** [comment]
Could you post your log please? You can find it at C:\Users\YOURNAME\AppData\Roaming\Championify\championify.log.txt

**Comment by MrMisteriousGuy** [comment]
{"level":"info","message":"Version: 2.0.2","timestamp":"2017-03-02T19:49:35.260Z"}
{"level":"info","message":"Checking for updates","timestamp":"2017-03-02T19:49:37.334Z"}
{"level":"info","message":"No updates found","timestamp":"2017-03-02T19:49:38.103Z"}
{"message":"Can't get Champion.GG Version","stack":"RequestError: Can't get Champion.GG Version\n    at then.catch.err (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\js\\sources\\championgg.js:80:11)\n    at tryCatcher (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)\nCause: Error: ETIMEDOUT\n    at C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\request\\request.js:762:15","code":"Can't get Champion.GG Version","type":"RequestError","ua":"win32 10.0.14393","locale":"en","cause":{"cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"code":"ETIMEDOUT","connect":false},"rootCause":{"cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"code":"ETIMEDOUT","connect":false},"ownStack":"RequestError: Can't get Champion.GG Version\n    at then.catch.err (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\js\\sources\\championgg.js:80:11)\n    at tryCatcher (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)","level":"warn","timestamp":"2017-03-02T19:50:07.335Z"}
{"message":"ETIMEDOUT","name":"Error","cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"stack":"Error: ETIMEDOUT\n    at C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\request\\request.js:762:15","code":"ETIMEDOUT","connect":false,"level":"warn","timestamp":"2017-03-02T19:50:07.338Z"}

**Comment by MrMisteriousGuy** [comment]
sorry, its a bit long.

**Comment by MrMisteriousGuy** [comment]
{"level":"info","message":"Version: 2.0.2","timestamp":"2017-03-02T19:49:35.260Z"}
{"level":"info","message":"Checking for updates","timestamp":"2017-03-02T19:49:37.334Z"}
{"level":"info","message":"No updates found","timestamp":"2017-03-02T19:49:38.103Z"}
{"message":"Can't get Champion.GG Version","stack":"RequestError: Can't get Champion.GG Version\n    at then.catch.err (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\js\\sources\\championgg.js:80:11)\n    at tryCatcher (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)\nCause: Error: ETIMEDOUT\n    at C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\request\\request.js:762:15","code":"Can't get Champion.GG Version","type":"RequestError","ua":"win32 10.0.14393","locale":"en","cause":{"cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"code":"ETIMEDOUT","connect":false},"rootCause":{"cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"code":"ETIMEDOUT","connect":false},"ownStack":"RequestError: Can't get Champion.GG Version\n    at then.catch.err (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\js\\sources\\championgg.js:80:11)\n    at tryCatcher (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)","level":"warn","timestamp":"2017-03-02T19:50:07.335Z"}
{"message":"ETIMEDOUT","name":"Error","cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"stack":"Error: ETIMEDOUT\n    at C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\request\\request.js:762:15","code":"ETIMEDOUT","connect":false,"level":"warn","timestamp":"2017-03-02T19:50:07.338Z"}
{"level":"info","message":"Locale: en","timestamp":"2017-03-02T19:54:16.750Z"}
{"level":"info","message":"Saved preference file to C:\\Users\\user\\AppData\\Roaming\\Championify\\prefs.json","timestamp":"2017-03-02T19:54:16.777Z"}
{"level":"info","message":"Getting LoL Version","timestamp":"2017-03-02T19:54:16.932Z"}
{"level":"info","message":"Downloading Champs from Riot","timestamp":"2017-03-02T19:54:17.547Z"}
{"level":"info","message":"Downloading ARAM Champs","timestamp":"2017-03-02T19:54:18.657Z"}
{"level":"info","message":"Getting Champion.gg Version","timestamp":"2017-03-02T19:54:18.657Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Aatrox","timestamp":"2017-03-02T19:54:19.306Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Ahri","timestamp":"2017-03-02T19:54:19.309Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Akali","timestamp":"2017-03-02T19:54:19.311Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Zyra","timestamp":"2017-03-02T19:54:19.796Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Zilean","timestamp":"2017-03-02T19:54:19.814Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Ziggs","timestamp":"2017-03-02T19:54:19.825Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Zed","timestamp":"2017-03-02T19:54:20.243Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Zac","timestamp":"2017-03-02T19:54:20.268Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Yorick","timestamp":"2017-03-02T19:54:20.299Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Yasuo","timestamp":"2017-03-02T19:54:20.677Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Xin Zhao","timestamp":"2017-03-02T19:54:20.706Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Xerath","timestamp":"2017-03-02T19:54:20.725Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Warwick","timestamp":"2017-03-02T19:54:21.109Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Volibear","timestamp":"2017-03-02T19:54:21.140Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Vladimir","timestamp":"2017-03-02T19:54:21.156Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Viktor","timestamp":"2017-03-02T19:54:21.572Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Vi","timestamp":"2017-03-02T19:54:21.603Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Vel'Koz","timestamp":"2017-03-02T19:54:21.613Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Veigar","timestamp":"2017-03-02T19:54:22.060Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Vayne","timestamp":"2017-03-02T19:54:22.071Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Varus","timestamp":"2017-03-02T19:54:22.086Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Urgot","timestamp":"2017-03-02T19:54:22.539Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Udyr","timestamp":"2017-03-02T19:54:22.553Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Twitch","timestamp":"2017-03-02T19:54:22.564Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Twisted Fate","timestamp":"2017-03-02T19:54:23.005Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Tryndamere","timestamp":"2017-03-02T19:54:23.029Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Trundle","timestamp":"2017-03-02T19:54:23.037Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Tristana","timestamp":"2017-03-02T19:54:23.459Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Thresh","timestamp":"2017-03-02T19:54:23.475Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Teemo","timestamp":"2017-03-02T19:54:23.491Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Taric","timestamp":"2017-03-02T19:54:23.896Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Talon","timestamp":"2017-03-02T19:54:23.912Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Taliyah","timestamp":"2017-03-02T19:54:23.922Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Tahm Kench","timestamp":"2017-03-02T19:54:24.306Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Syndra","timestamp":"2017-03-02T19:54:24.343Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Swain","timestamp":"2017-03-02T19:54:24.355Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Soraka","timestamp":"2017-03-02T19:54:24.729Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Sona","timestamp":"2017-03-02T19:54:24.779Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Skarner","timestamp":"2017-03-02T19:54:24.793Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Sivir","timestamp":"2017-03-02T19:54:25.187Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Sion","timestamp":"2017-03-02T19:54:25.215Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Singed","timestamp":"2017-03-02T19:54:25.225Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Shyvana","timestamp":"2017-03-02T19:54:25.636Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Shen","timestamp":"2017-03-02T19:54:25.651Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Shaco","timestamp":"2017-03-02T19:54:25.659Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Sejuani","timestamp":"2017-03-02T19:54:26.090Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Ryze","timestamp":"2017-03-02T19:54:26.115Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Rumble","timestamp":"2017-03-02T19:54:26.121Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Riven","timestamp":"2017-03-02T19:54:26.520Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Rengar","timestamp":"2017-03-02T19:54:26.547Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Renekton","timestamp":"2017-03-02T19:54:26.569Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Rek'Sai","timestamp":"2017-03-02T19:54:26.963Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Rammus","timestamp":"2017-03-02T19:54:26.994Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Quinn","timestamp":"2017-03-02T19:54:27.017Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Poppy","timestamp":"2017-03-02T19:54:27.391Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Pantheon","timestamp":"2017-03-02T19:54:27.448Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Orianna","timestamp":"2017-03-02T19:54:27.479Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Olaf","timestamp":"2017-03-02T19:54:27.824Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Nunu","timestamp":"2017-03-02T19:54:27.876Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Nocturne","timestamp":"2017-03-02T19:54:27.904Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Nidalee","timestamp":"2017-03-02T19:54:28.253Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Nautilus","timestamp":"2017-03-02T19:54:28.331Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Nasus","timestamp":"2017-03-02T19:54:28.350Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Nami","timestamp":"2017-03-02T19:54:28.689Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Morgana","timestamp":"2017-03-02T19:54:28.759Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Mordekaiser","timestamp":"2017-03-02T19:54:28.775Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Wukong","timestamp":"2017-03-02T19:54:29.124Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Miss Fortune","timestamp":"2017-03-02T19:54:29.189Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Master Yi","timestamp":"2017-03-02T19:54:29.208Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Maokai","timestamp":"2017-03-02T19:54:29.566Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Malzahar","timestamp":"2017-03-02T19:54:29.722Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Malphite","timestamp":"2017-03-02T19:54:29.753Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Lux","timestamp":"2017-03-02T19:54:30.016Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Lulu","timestamp":"2017-03-02T19:54:30.194Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Lucian","timestamp":"2017-03-02T19:54:30.203Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Lissandra","timestamp":"2017-03-02T19:54:30.461Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Leona","timestamp":"2017-03-02T19:54:30.623Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Lee Sin","timestamp":"2017-03-02T19:54:30.653Z"}
{"level":"info","message":"Processing Lolflavor ARAM: LeBlanc","timestamp":"2017-03-02T19:54:30.903Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Kog'Maw","timestamp":"2017-03-02T19:54:31.090Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Kled","timestamp":"2017-03-02T19:54:31.100Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Kindred","timestamp":"2017-03-02T19:54:31.343Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Kha'Zix","timestamp":"2017-03-02T19:54:31.546Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Kennen","timestamp":"2017-03-02T19:54:31.571Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Kayle","timestamp":"2017-03-02T19:54:31.817Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Katarina","timestamp":"2017-03-02T19:54:32.013Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Kassadin","timestamp":"2017-03-02T19:54:32.035Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Karthus","timestamp":"2017-03-02T19:54:32.287Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Karma","timestamp":"2017-03-02T19:54:32.478Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Kalista","timestamp":"2017-03-02T19:54:32.510Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Jinx","timestamp":"2017-03-02T19:54:32.735Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Jhin","timestamp":"2017-03-02T19:54:32.934Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Jayce","timestamp":"2017-03-02T19:54:32.965Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Jax","timestamp":"2017-03-02T19:54:33.192Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Jarvan IV","timestamp":"2017-03-02T19:54:33.391Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Janna","timestamp":"2017-03-02T19:54:33.480Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Ivern","timestamp":"2017-03-02T19:54:33.676Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Irelia","timestamp":"2017-03-02T19:54:33.818Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Illaoi","timestamp":"2017-03-02T19:54:33.912Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Heimerdinger","timestamp":"2017-03-02T19:54:34.110Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Hecarim","timestamp":"2017-03-02T19:54:34.236Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Graves","timestamp":"2017-03-02T19:54:34.330Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Gragas","timestamp":"2017-03-02T19:54:34.543Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Gnar","timestamp":"2017-03-02T19:54:34.649Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Garen","timestamp":"2017-03-02T19:54:34.775Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Gangplank","timestamp":"2017-03-02T19:54:34.984Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Galio","timestamp":"2017-03-02T19:54:35.074Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Fizz","timestamp":"2017-03-02T19:54:35.212Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Fiora","timestamp":"2017-03-02T19:54:35.411Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Fiddlesticks","timestamp":"2017-03-02T19:54:35.512Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Ezreal","timestamp":"2017-03-02T19:54:35.659Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Evelynn","timestamp":"2017-03-02T19:54:35.853Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Elise","timestamp":"2017-03-02T19:54:35.942Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Ekko","timestamp":"2017-03-02T19:54:36.108Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Draven","timestamp":"2017-03-02T19:54:36.294Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Dr. Mundo","timestamp":"2017-03-02T19:54:36.375Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Diana","timestamp":"2017-03-02T19:54:36.547Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Darius","timestamp":"2017-03-02T19:54:36.723Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Corki","timestamp":"2017-03-02T19:54:36.808Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Cho'Gath","timestamp":"2017-03-02T19:54:36.981Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Cassiopeia","timestamp":"2017-03-02T19:54:37.152Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Camille","timestamp":"2017-03-02T19:54:37.267Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Caitlyn","timestamp":"2017-03-02T19:54:37.431Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Braum","timestamp":"2017-03-02T19:54:37.600Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Brand","timestamp":"2017-03-02T19:54:37.691Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Blitzcrank","timestamp":"2017-03-02T19:54:37.881Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Bard","timestamp":"2017-03-02T19:54:38.069Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Azir","timestamp":"2017-03-02T19:54:38.129Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Aurelion Sol","timestamp":"2017-03-02T19:54:38.337Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Ashe","timestamp":"2017-03-02T19:54:38.504Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Annie","timestamp":"2017-03-02T19:54:38.561Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Anivia","timestamp":"2017-03-02T19:54:38.798Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Amumu","timestamp":"2017-03-02T19:54:38.939Z"}
{"level":"info","message":"Processing Lolflavor ARAM: Alistar","timestamp":"2017-03-02T19:54:39.001Z"}
{"message":"Can't get Champion.GG Version","stack":"RequestError: Can't get Champion.GG Version\n    at then.catch.err (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\js\\sources\\championgg.js:80:11)\n    at tryCatcher (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)\n    at process._tickCallback (internal/process/next_tick.js:103:7)\nCause: Error: ESOCKETTIMEDOUT\n    at ClientRequest.<anonymous> (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\request\\request.js:779:19)\n    at ClientRequest.g (events.js:286:16)\n    at emitNone (events.js:86:13)\n    at ClientRequest.emit (events.js:185:7)\n    at Socket.emitTimeout (_http_client.js:614:10)\n    at Socket.g (events.js:286:16)\n    at emitNone (events.js:86:13)\n    at Socket.emit (events.js:185:7)\n    at Socket._onTimeout (net.js:334:8)\n    at tryOnTimeout (timers.js:232:11)\n    at Timer.listOnTimeout (timers.js:202:5)","code":"Can't get Champion.GG Version","type":"RequestError","ua":"win32 10.0.14393","locale":"en","cause":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"rootCause":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"ownStack":"RequestError: Can't get Champion.GG Version\n    at then.catch.err (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\js\\sources\\championgg.js:80:11)\n    at tryCatcher (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (C:\\Users\\user\\AppData\\Local\\Championify\\app-2.0.2\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)\n    at process._tickCallback (internal/process/next_tick.js:103:7)","level":"error","timestamp":"2017-03-02T19:54:48.713Z"}

the log after the error.

**Comment by dustinblackman** [comment]
Are you able to access http://champion.gg?

**Comment by MrMisteriousGuy** [comment]
yeah, champion.gg (website) I can. but, champion.gg on championify, I cant.

**Comment by dustinblackman** [comment]
Odd, for some reason the app is having trouble accessing http://champion.gg/faq . There has been cases where your antivirus may be blocking the outbound connections. Have you whitelisted the app?

**Comment by dustinblackman** [comment]
Stale, closing.
