### ISSUE TITLE
Download don't go over 66%

### ISSUE THREAD

**Issue by Devilmiki** [dustinblackman/Championify#280]
I have tried a lot of time to download the build but the donwload won't past 66%.
I have also tried to install the last version of championify but the problem persist!

**Comment by dustinblackman** [comment]
Could you post your log please? You can find it at C:\Users\YOURNAME\AppData\Roaming\Championify\championify.log.txt

**Comment by Devilmiki** [comment]
[championify.log.txt](https://github.com/dustinblackman/Championify/files/814991/championify.log.txt)

**Comment by dustinblackman** [comment]
Odd, there's nothing there to explain why it just stops.

**Comment by Wiary** [comment]
Try to delete Probuilds and import builds again. 
I had choosen probuilds too and didnt work for me.

**Comment by Devilmiki** [comment]
i've deleted Probuilds and now it stop at 50% :/

**Comment by dustinblackman** [comment]
I think it may be related to op.gg. I'm able to repro it locally. Are you using op.gg, and if so can you remove it?

**Comment by Devilmiki** [comment]
If I use only champion.gg it work! The problem are with Probuild ans op.gg.. Thank you! 👍
