### ISSUE TITLE
Champion.gg - ALL not available

### ISSUE THREAD

**Issue by Ionaru** [dustinblackman/Championify#286]
When importing from Champion.gg, no item sets are downloaded.

In the log, this message appears a lot: `TypeError: Cannot read property 'order' of undefined`

[championify.log.txt](https://github.com/dustinblackman/Championify/files/836981/championify.log.txt)

**Comment by dustinblackman** [comment]
Data is missing on Champion.gg's end where all the pages are missing the skills upgrade paths. I can see about writing a patch to ignore skills, but I'm not on an internet connection where I'll be able to do a release quickly.

**Comment by dustinblackman** [comment]
Looks like they've fixed it.

**Comment by Ionaru** [comment]
Nice, glad it wasn't a permanent problem.

Maybe it's a good idea to build something into the application that could have dealt with this? Something like a try/catch that would still try to fetch other data from a website even if some of it isn't available.
That way the item sets wouldn't be entirely broken if the skill order isn't available.

**Comment by dustinblackman** [comment]
I don't want to go in and attempt to handle every possible edge case as that's too time consuming. Instead I atleast make sure imports from the chosen sources completes rather then exiting when one thing goes wrong.
