### ISSUE TITLE
Can't access github package.json

### ISSUE THREAD

**Issue by ResistImpulse** [dustinblackman/Championify#287]
"Something broke..."
"Can't access github package.json"
ran as admin, used to work great pre 7th season, reinstalled, still doesn't work

**Comment by dustinblackman** [comment]
@ResistImpulse Can you post your log please? It's located at C:\Users\YOURNAME\AppData\Roaming\Championify\championify.log.txt

**Comment by ResistImpulse** [comment]
Apologize my version is pre 2.0  I am not very well practiced with working with github (even though I love their editor Atom).  
Would you suggest github newbs like myself download their desktop app?

**Comment by dustinblackman** [comment]
Nah, people just need to go the releases page and hit download. Glad it works!
