### ISSUE TITLE
item sets not showing up in garena lol lcu

### ISSUE THREAD

**Issue by heIlo** [dustinblackman/Championify#291]
hi, championify detects the league client and runs per normal, but when i enter the game i don't see any other item sets other than "recommended". not sure if its an issue on your end?

**Comment by heIlo** [comment]
it's working perfectly fine in the legacy client for garena!

**Comment by dustinblackman** [comment]
Odd, there shouldn't be a difference between the two clients, but Garena does tend to work a little differently than everything else. I'll mark as a bug and take a look.

**Comment by nongnoobjung** [comment]
it work fine for LCU

**Comment by RyZum** [comment]
I just tried on garena and I have the same issue. It detects the game, runs as normal, but in game I can't see the item sets.

**Comment by akashsara** [comment]
I've been using it on Garena for a while now. No issues. Game directory is set as 

> \Garena\GameData\Apps\LoL

**Comment by dustinblackman** [comment]
@akashsara Ah that's right, I had forgotten that Garena has the subdirectory that contains the real game data. I have checks for that in place however, but they could possibly be outdated. I'll have to download the garena client myself when I have time.

@heIlo @RyZum Does @akashsara suggestion work for you?

**Comment by akashsara** [comment]
> Garena\GameData\Apps\LoL\Game\Config\Champions\<champion name>\Recommended

is the exact path to the item sets

**Comment by RyZum** [comment]
Thanks, it works for me if I set the path to `Garena\32771`

`Garena\32771\LeagueClient` is also detected as League of Legends directory but it doesn't work.

**Comment by akashsara** [comment]
Odd. I don't have any folder like that. Which server are you on? I'm on SEA. Maybe the structure is different for each server?

**Comment by Xin1337** [comment]
It was working when the directory is set into GarenaLoL\GameData\Apps\LoLPH but the update screwed it up and doesn't recognize it anymore and forces to set the directory to GarenaLoL\GameData\Apps\LoLPH\LeagueClient

**Comment by sqfreakz** [comment]
on my case, Indonesian Garena server, the directory is [Garena LoL Folder]\GameData\Apps\LoLID\Game

**Comment by heIlo** [comment]
@dustinblackman found the issue, the game directory path that garena users should be pointing to is C:\Program Files (x86)\GarenaLoL\GameData\Apps\LoL\Game but Championify displays a message: You sure that's league? when pointing to it. I think the exe that championify is checking for is not present in the same folder as the item sets, which may be different from other regions. imo to fix this, championify should look for League of Legends.exe instead of lolex.exe on Garena servers.

**Comment by heIlo** [comment]
yup, works fine now. thanks for the fix :)
