### ISSUE TITLE
"Can't get champs" Error

### ISSUE THREAD

**Issue by LordVenomancer** [dustinblackman/Championify#294]
I get this error whenever it tried to download champs from Riot.
I'm running as Admin
My firewalls are off
my internet connection is fine.
Not sure what is going on. HELP PLS

**Comment by LordVenomancer** [comment]
{"level":"info","message":"Version: 2.0.4","timestamp":"2017-04-26T20:27:17.256Z"}
{"level":"info","message":"Checking for updates","timestamp":"2017-04-26T20:27:18.498Z"}
{"level":"info","message":"No updates found","timestamp":"2017-04-26T20:27:19.259Z"}
{"message":"Cannot read property 'split' of undefined","stack":"TypeError: Cannot read property 'split' of undefined\n    at getCache.then.then.version (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\js\\sources\\lolalytics.js:48:26)\n    at tryCatcher (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:691:18)\n    at Promise._fulfill (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:636:18)\n    at Promise._resolveCallback (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:431:57)\n    at Promise._settlePromiseFromHandler (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:522:17)\n    at Promise._settlePromise (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:691:18)\n    at Promise._fulfill (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:636:18)\n    at Promise._settlePromise (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:580:21)\n    at Promise._settlePromise0 (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:691:18)","level":"warn","timestamp":"2017-04-26T20:27:20.041Z"}
{"level":"info","message":"Locale: en","timestamp":"2017-04-26T20:27:26.535Z"}
{"level":"info","message":"Saved preference file to C:\\Users\\Administrator\\AppData\\Roaming\\Championify\\prefs.json","timestamp":"2017-04-26T20:27:26.540Z"}
{"level":"info","message":"Getting LoL Version","timestamp":"2017-04-26T20:27:26.792Z"}
{"level":"info","message":"Downloading Champs from Riot","timestamp":"2017-04-26T20:27:27.092Z"}
{"message":"Can't get Champs","stack":"RequestError: Can't get Champs\n    at then.tap.data (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\js\\championify.js:100:22)\n    at PassThroughHandlerContext.finallyHandler (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\finally.js:56:23)\n    at PassThroughHandlerContext.tryCatcher (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:691:18)\n    at Promise._fulfill (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:636:18)\n    at Promise._resolveCallback (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:431:57)\n    at Promise._settlePromiseFromHandler (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:522:17)\n    at Promise._settlePromise (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:691:18)\n    at Promise._fulfill (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:636:18)\n    at Promise._settlePromise (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:580:21)\n    at Promise._settlePromise0 (C:\\Users\\Administrator\\AppData\\Local\\Championify\\app-2.0.4\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)","code":"Can't get Champs","type":"RequestError","ua":"win32 6.1.7601","locale":"en","level":"error","timestamp":"2017-04-26T20:27:30.402Z"}


 log for reference

**Comment by dustinblackman** [comment]
@LordVenomancer They've been making changes to their API. If you were to try now does it work?

**Comment by dustinblackman** [comment]
Marking as stale.
