### ISSUE TITLE
failed to write item set json file

### ISSUE THREAD

**Issue by ralausem** [dustinblackman/Championify#295]
{"level":"info","message":"Version: 2.0.4","timestamp":"2017-05-02T19:44:45.047Z"}
{"level":"info","message":"Checking for updates","timestamp":"2017-05-02T19:44:46.812Z"}
{"level":"info","message":"No updates found","timestamp":"2017-05-02T19:44:47.530Z"}
{"level":"info","message":"Locale: pt-BR","timestamp":"2017-05-02T19:44:47.558Z"}
{"level":"info","message":"Saved preference file to C:\\Users\\Junior\\AppData\\Roaming\\Championify\\prefs.json","timestamp":"2017-05-02T19:44:47.573Z"}
{"level":"info","message":"Obtendo a versão do LoL","timestamp":"2017-05-02T19:44:47.576Z"}
{"level":"info","message":"Baixando os campeões da Riot","timestamp":"2017-05-02T19:44:47.799Z"}
{"level":"info","message":"Processando Lolmasters: Aatrox","timestamp":"2017-05-02T19:44:48.259Z"}
{"level":"info","message":"Processando Lolmasters: Ahri","timestamp":"2017-05-02T19:44:48.302Z"}
{"level":"info","message":"Processando Lolmasters: Zyra","timestamp":"2017-05-02T19:44:48.823Z"}
{"level":"info","message":"Processando Lolmasters: Zilean","timestamp":"2017-05-02T19:44:48.871Z"}
{"level":"info","message":"Processando Lolmasters: Ziggs","timestamp":"2017-05-02T19:44:49.357Z"}
{"level":"info","message":"Processando Lolmasters: Zed","timestamp":"2017-05-02T19:44:49.380Z"}
{"level":"info","message":"Processando Lolmasters: Zac","timestamp":"2017-05-02T19:44:49.901Z"}
{"level":"info","message":"Processando Lolmasters: Yorick","timestamp":"2017-05-02T19:44:49.906Z"}
{"level":"info","message":"Processando Lolmasters: Yasuo","timestamp":"2017-05-02T19:44:50.441Z"}
{"level":"info","message":"Processando Lolmasters: Xin Zhao","timestamp":"2017-05-02T19:44:50.449Z"}
{"level":"info","message":"Processando Lolmasters: Xerath","timestamp":"2017-05-02T19:44:50.976Z"}
{"level":"info","message":"Processando Lolmasters: Xayah","timestamp":"2017-05-02T19:44:50.982Z"}
{"level":"info","message":"Processando Lolmasters: Warwick","timestamp":"2017-05-02T19:44:52.037Z"}
{"level":"info","message":"Processando Lolmasters: Volibear","timestamp":"2017-05-02T19:44:52.043Z"}
{"level":"info","message":"Processando Lolmasters: Vladimir","timestamp":"2017-05-02T19:44:52.534Z"}
{"level":"info","message":"Processando Lolmasters: Viktor","timestamp":"2017-05-02T19:44:52.558Z"}
{"level":"info","message":"Processando Lolmasters: Vi","timestamp":"2017-05-02T19:44:53.037Z"}
{"level":"info","message":"Processando Lolmasters: Vel'Koz","timestamp":"2017-05-02T19:44:53.056Z"}
{"level":"info","message":"Processando Lolmasters: Veigar","timestamp":"2017-05-02T19:44:53.600Z"}
{"level":"info","message":"Processando Lolmasters: Vayne","timestamp":"2017-05-02T19:44:53.612Z"}
{"level":"info","message":"Processando Lolmasters: Varus","timestamp":"2017-05-02T19:44:54.121Z"}
{"level":"info","message":"Processando Lolmasters: Urgot","timestamp":"2017-05-02T19:44:54.126Z"}
{"level":"info","message":"Processando Lolmasters: Udyr","timestamp":"2017-05-02T19:44:54.644Z"}
{"level":"info","message":"Processando Lolmasters: Twitch","timestamp":"2017-05-02T19:44:54.649Z"}
{"level":"info","message":"Processando Lolmasters: Twisted Fate","timestamp":"2017-05-02T19:44:55.160Z"}
{"level":"info","message":"Processando Lolmasters: Tryndamere","timestamp":"2017-05-02T19:44:55.170Z"}
{"level":"info","message":"Processando Lolmasters: Trundle","timestamp":"2017-05-02T19:44:55.704Z"}
{"level":"info","message":"Processando Lolmasters: Tristana","timestamp":"2017-05-02T19:44:55.708Z"}
{"level":"info","message":"Processando Lolmasters: Thresh","timestamp":"2017-05-02T19:44:56.207Z"}
{"level":"info","message":"Processando Lolmasters: Teemo","timestamp":"2017-05-02T19:44:56.226Z"}
{"level":"info","message":"Processando Lolmasters: Taric","timestamp":"2017-05-02T19:44:56.709Z"}
{"level":"info","message":"Processando Lolmasters: Talon","timestamp":"2017-05-02T19:44:56.728Z"}
{"level":"info","message":"Processando Lolmasters: Taliyah","timestamp":"2017-05-02T19:44:57.229Z"}
{"level":"info","message":"Processando Lolmasters: Tahm Kench","timestamp":"2017-05-02T19:44:57.235Z"}
{"level":"info","message":"Processando Lolmasters: Syndra","timestamp":"2017-05-02T19:44:57.727Z"}
{"level":"info","message":"Processando Lolmasters: Swain","timestamp":"2017-05-02T19:44:57.750Z"}
{"level":"info","message":"Processando Lolmasters: Soraka","timestamp":"2017-05-02T19:44:58.245Z"}
{"level":"info","message":"Processando Lolmasters: Sona","timestamp":"2017-05-02T19:44:58.748Z"}
{"level":"info","message":"Processando Lolmasters: Skarner","timestamp":"2017-05-02T19:44:59.249Z"}
{"level":"info","message":"Processando Lolmasters: Sivir","timestamp":"2017-05-02T19:44:59.745Z"}
{"level":"info","message":"Processando Lolmasters: Sion","timestamp":"2017-05-02T19:45:00.255Z"}
{"level":"info","message":"Processando Lolmasters: Singed","timestamp":"2017-05-02T19:45:00.757Z"}
{"level":"info","message":"Processando Lolmasters: Shyvana","timestamp":"2017-05-02T19:45:01.206Z"}
{"level":"info","message":"Processando Lolmasters: Shen","timestamp":"2017-05-02T19:45:01.253Z"}
{"level":"info","message":"Processando Lolmasters: Shaco","timestamp":"2017-05-02T19:45:01.708Z"}
{"level":"info","message":"Processando Lolmasters: Sejuani","timestamp":"2017-05-02T19:45:01.764Z"}
{"level":"info","message":"Processando Lolmasters: Ryze","timestamp":"2017-05-02T19:45:02.210Z"}
{"level":"info","message":"Processando Lolmasters: Rumble","timestamp":"2017-05-02T19:45:02.258Z"}
{"level":"info","message":"Processando Lolmasters: Riven","timestamp":"2017-05-02T19:45:02.706Z"}
{"level":"info","message":"Processando Lolmasters: Rengar","timestamp":"2017-05-02T19:45:02.749Z"}
{"level":"info","message":"Processando Lolmasters: Renekton","timestamp":"2017-05-02T19:45:03.205Z"}
{"level":"info","message":"Processando Lolmasters: Rek'Sai","timestamp":"2017-05-02T19:45:04.289Z"}
{"level":"info","message":"Processando Lolmasters: Rammus","timestamp":"2017-05-02T19:45:04.296Z"}
{"level":"info","message":"Processando Lolmasters: Rakan","timestamp":"2017-05-02T19:45:04.796Z"}
{"level":"info","message":"Processando Lolmasters: Quinn","timestamp":"2017-05-02T19:45:04.819Z"}
{"level":"info","message":"Processando Lolmasters: Poppy","timestamp":"2017-05-02T19:45:05.326Z"}
{"level":"info","message":"Processando Lolmasters: Pantheon","timestamp":"2017-05-02T19:45:05.332Z"}
{"level":"info","message":"Processando Lolmasters: Orianna","timestamp":"2017-05-02T19:45:05.840Z"}
{"level":"info","message":"Processando Lolmasters: Olaf","timestamp":"2017-05-02T19:45:05.844Z"}
{"level":"info","message":"Processando Lolmasters: Nunu","timestamp":"2017-05-02T19:45:06.337Z"}
{"level":"info","message":"Processando Lolmasters: Nocturne","timestamp":"2017-05-02T19:45:06.357Z"}
{"level":"info","message":"Processando Lolmasters: Nidalee","timestamp":"2017-05-02T19:45:06.836Z"}
{"level":"info","message":"Processando Lolmasters: Nautilus","timestamp":"2017-05-02T19:45:06.865Z"}
{"level":"info","message":"Processando Lolmasters: Nasus","timestamp":"2017-05-02T19:45:07.351Z"}
{"level":"info","message":"Processando Lolmasters: Nami","timestamp":"2017-05-02T19:45:07.370Z"}
{"level":"info","message":"Processando Lolmasters: Morgana","timestamp":"2017-05-02T19:45:07.861Z"}
{"level":"info","message":"Processando Lolmasters: Mordekaiser","timestamp":"2017-05-02T19:45:07.874Z"}
{"level":"info","message":"Processando Lolmasters: Wukong","timestamp":"2017-05-02T19:45:08.362Z"}
{"level":"info","message":"Processando Lolmasters: Miss Fortune","timestamp":"2017-05-02T19:45:08.887Z"}
{"level":"info","message":"Processando Lolmasters: Master Yi","timestamp":"2017-05-02T19:45:09.382Z"}
{"level":"info","message":"Processando Lolmasters: Maokai","timestamp":"2017-05-02T19:45:09.875Z"}
{"level":"info","message":"Processando Lolmasters: Malzahar","timestamp":"2017-05-02T19:45:10.371Z"}
{"level":"info","message":"Processando Lolmasters: Malphite","timestamp":"2017-05-02T19:45:10.888Z"}
{"level":"info","message":"Processando Lolmasters: Lux","timestamp":"2017-05-02T19:45:11.385Z"}
{"level":"info","message":"Processando Lolmasters: Lulu","timestamp":"2017-05-02T19:45:11.404Z"}
{"level":"info","message":"Processando Lolmasters: Lucian","timestamp":"2017-05-02T19:45:11.894Z"}
{"level":"info","message":"Processando Lolmasters: Lissandra","timestamp":"2017-05-02T19:45:11.912Z"}
{"level":"info","message":"Processando Lolmasters: Leona","timestamp":"2017-05-02T19:45:12.398Z"}
{"level":"info","message":"Processando Lolmasters: Lee Sin","timestamp":"2017-05-02T19:45:12.443Z"}
{"level":"info","message":"Processando Lolmasters: LeBlanc","timestamp":"2017-05-02T19:45:12.906Z"}
{"level":"info","message":"Processando Lolmasters: Kog'Maw","timestamp":"2017-05-02T19:45:12.951Z"}
{"level":"info","message":"Processando Lolmasters: Kled","timestamp":"2017-05-02T19:45:13.417Z"}
{"level":"info","message":"Processando Lolmasters: Kindred","timestamp":"2017-05-02T19:45:13.460Z"}
{"level":"info","message":"Processando Lolmasters: Kha'Zix","timestamp":"2017-05-02T19:45:13.911Z"}
{"level":"info","message":"Processando Lolmasters: Kennen","timestamp":"2017-05-02T19:45:13.964Z"}
{"level":"info","message":"Processando Lolmasters: Kayle","timestamp":"2017-05-02T19:45:14.410Z"}
{"level":"info","message":"Processando Lolmasters: Katarina","timestamp":"2017-05-02T19:45:14.460Z"}
{"level":"info","message":"Processando Lolmasters: Kassadin","timestamp":"2017-05-02T19:45:14.920Z"}
{"level":"info","message":"Processando Lolmasters: Karthus","timestamp":"2017-05-02T19:45:14.953Z"}
{"level":"info","message":"Processando Lolmasters: Karma","timestamp":"2017-05-02T19:45:15.423Z"}
{"level":"info","message":"Processando Lolmasters: Kalista","timestamp":"2017-05-02T19:45:15.454Z"}
{"level":"info","message":"Processando Lolmasters: Jinx","timestamp":"2017-05-02T19:45:15.922Z"}
{"level":"info","message":"Processando Lolmasters: Jhin","timestamp":"2017-05-02T19:45:15.952Z"}
{"level":"info","message":"Processando Lolmasters: Jayce","timestamp":"2017-05-02T19:45:16.442Z"}
{"level":"info","message":"Processando Lolmasters: Jax","timestamp":"2017-05-02T19:45:16.450Z"}
{"level":"info","message":"Processando Lolmasters: Jarvan IV","timestamp":"2017-05-02T19:45:16.950Z"}
{"level":"info","message":"Processando Lolmasters: Janna","timestamp":"2017-05-02T19:45:16.973Z"}
{"level":"info","message":"Processando Lolmasters: Ivern","timestamp":"2017-05-02T19:45:17.450Z"}
{"level":"info","message":"Processando Lolmasters: Irelia","timestamp":"2017-05-02T19:45:17.478Z"}
{"level":"info","message":"Processando Lolmasters: Illaoi","timestamp":"2017-05-02T19:45:17.943Z"}
{"level":"info","message":"Processando Lolmasters: Heimerdinger","timestamp":"2017-05-02T19:45:17.975Z"}
{"level":"info","message":"Processando Lolmasters: Hecarim","timestamp":"2017-05-02T19:45:18.451Z"}
{"level":"info","message":"Processando Lolmasters: Graves","timestamp":"2017-05-02T19:45:18.475Z"}
{"level":"info","message":"Processando Lolmasters: Gragas","timestamp":"2017-05-02T19:45:18.962Z"}
{"level":"info","message":"Processando Lolmasters: Gnar","timestamp":"2017-05-02T19:45:18.978Z"}
{"level":"info","message":"Processando Lolmasters: Garen","timestamp":"2017-05-02T19:45:19.472Z"}
{"level":"info","message":"Processando Lolmasters: Gangplank","timestamp":"2017-05-02T19:45:19.491Z"}
{"level":"info","message":"Processando Lolmasters: Galio","timestamp":"2017-05-02T19:45:19.972Z"}
{"level":"info","message":"Processando Lolmasters: Fizz","timestamp":"2017-05-02T19:45:19.999Z"}
{"level":"info","message":"Processando Lolmasters: Fiora","timestamp":"2017-05-02T19:45:20.479Z"}
{"level":"info","message":"Processando Lolmasters: Fiddlesticks","timestamp":"2017-05-02T19:45:20.494Z"}
{"level":"info","message":"Processando Lolmasters: Ezreal","timestamp":"2017-05-02T19:45:20.968Z"}
{"level":"info","message":"Processando Lolmasters: Evelynn","timestamp":"2017-05-02T19:45:20.992Z"}
{"level":"info","message":"Processando Lolmasters: Elise","timestamp":"2017-05-02T19:45:21.470Z"}
{"level":"info","message":"Processando Lolmasters: Ekko","timestamp":"2017-05-02T19:45:21.494Z"}
{"level":"info","message":"Processando Lolmasters: Draven","timestamp":"2017-05-02T19:45:21.973Z"}
{"level":"info","message":"Processando Lolmasters: Dr. Mundo","timestamp":"2017-05-02T19:45:21.994Z"}
{"level":"info","message":"Processando Lolmasters: Diana","timestamp":"2017-05-02T19:45:22.482Z"}
{"level":"info","message":"Processando Lolmasters: Darius","timestamp":"2017-05-02T19:45:22.503Z"}
{"level":"info","message":"Processando Lolmasters: Corki","timestamp":"2017-05-02T19:45:23.002Z"}
{"level":"info","message":"Processando Lolmasters: Cho'Gath","timestamp":"2017-05-02T19:45:23.022Z"}
{"level":"info","message":"Processando Lolmasters: Cassiopeia","timestamp":"2017-05-02T19:45:23.506Z"}
{"level":"info","message":"Processando Lolmasters: Camille","timestamp":"2017-05-02T19:45:23.527Z"}
{"level":"info","message":"Processando Lolmasters: Caitlyn","timestamp":"2017-05-02T19:45:24.018Z"}
{"level":"info","message":"Processando Lolmasters: Braum","timestamp":"2017-05-02T19:45:24.047Z"}
{"level":"info","message":"Processando Lolmasters: Brand","timestamp":"2017-05-02T19:45:24.530Z"}
{"level":"info","message":"Processando Lolmasters: Blitzcrank","timestamp":"2017-05-02T19:45:24.553Z"}
{"level":"info","message":"Processando Lolmasters: Bardo","timestamp":"2017-05-02T19:45:25.035Z"}
{"level":"info","message":"Processando Lolmasters: Azir","timestamp":"2017-05-02T19:45:25.062Z"}
{"level":"info","message":"Processando Lolmasters: Aurelion Sol","timestamp":"2017-05-02T19:45:25.548Z"}
{"level":"info","message":"Processando Lolmasters: Ashe","timestamp":"2017-05-02T19:45:25.578Z"}
{"level":"info","message":"Processando Lolmasters: Annie","timestamp":"2017-05-02T19:45:26.095Z"}
{"level":"info","message":"Processando Lolmasters: Anivia","timestamp":"2017-05-02T19:45:26.107Z"}
{"level":"info","message":"Processando Lolmasters: Amumu","timestamp":"2017-05-02T19:45:26.611Z"}
{"level":"info","message":"Processando Lolmasters: Alistar","timestamp":"2017-05-02T19:45:26.633Z"}
{"level":"info","message":"Processando Lolmasters: Akali","timestamp":"2017-05-02T19:45:27.119Z"}
{"level":"info","message":"Apagando builds antigas","timestamp":"2017-05-02T19:45:27.633Z"}
{"message":"Failed to write item set json file","stack":"FileWriteError: Failed to write item set json file\n    at fs.mkdirsAsync.catch.then.catch.err (C:\\Users\\Junior\\Downloads\\Championify-WIN-2.0.4\\Championify\\resources\\app.asar\\js\\championify.js:161:13)\n    at tryCatcher (C:\\Users\\Junior\\Downloads\\Championify-WIN-2.0.4\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\Junior\\Downloads\\Championify-WIN-2.0.4\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\Junior\\Downloads\\Championify-WIN-2.0.4\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\Junior\\Downloads\\Championify-WIN-2.0.4\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\Junior\\Downloads\\Championify-WIN-2.0.4\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (C:\\Users\\Junior\\Downloads\\Championify-WIN-2.0.4\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\Junior\\Downloads\\Championify-WIN-2.0.4\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (C:\\Users\\Junior\\Downloads\\Championify-WIN-2.0.4\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)\nCause: Error: UNKNOWN: unknown error, open 'C:\\Riot Games\\League of Legends\\Config\\Champions\\Fizz\\Recommended\\CIFY_Fizz_lolmasters_Top.json'\n    at Error (native)","type":"FileWriteError","ua":"win32 6.1.7600","locale":"pt-BR","cause":{"cause":{"errno":-4094,"code":"UNKNOWN","syscall":"open","path":"C:\\Riot Games\\League of Legends\\Config\\Champions\\Fizz\\Recommended\\CIFY_Fizz_lolmasters_Top.json"},"isOperational":true,"errno":-4094,"code":"UNKNOWN","syscall":"open","path":"C:\\Riot Games\\League of Legends\\Config\\Champions\\Fizz\\Recommended\\CIFY_Fizz_lolmasters_Top.json"},"rootCause":{"cause":{"errno":-4094,"code":"UNKNOWN","syscall":"open","path":"C:\\Riot Games\\League of Legends\\Config\\Champions\\Fizz\\Recommended\\CIFY_Fizz_lolmasters_Top.json"},"isOperational":true,"errno":-4094,"code":"UNKNOWN","syscall":"open","path":"C:\\Riot Games\\League of Legends\\Config\\Champions\\Fizz\\Recommended\\CIFY_Fizz_lolmasters_Top.json"},"ownStack":"FileWriteError: Failed to write item set json file\n    at fs.mkdirsAsync.catch.then.catch.err (C:\\Users\\Junior\\Downloads\\Championify-WIN-2.0.4\\Championify\\resources\\app.asar\\js\\championify.js:161:13)\n    at tryCatcher (C:\\Users\\Junior\\Downloads\\Championify-WIN-2.0.4\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\Junior\\Downloads\\Championify-WIN-2.0.4\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\Junior\\Downloads\\Championify-WIN-2.0.4\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\Junior\\Downloads\\Championify-WIN-2.0.4\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\Junior\\Downloads\\Championify-WIN-2.0.4\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (C:\\Users\\Junior\\Downloads\\Championify-WIN-2.0.4\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\Junior\\Downloads\\Championify-WIN-2.0.4\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (C:\\Users\\Junior\\Downloads\\Championify-WIN-2.0.4\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)","level":"error","timestamp":"2017-05-02T19:45:28.019Z"}

**Comment by dustinblackman** [comment]
Never seen Node's filesystem modules throw `UNKNOWN` before. What OS and Antivirus are you running?

**Comment by ralausem** [comment]
Not ever seen, windows defender, no antivirus on my pc, Windows 10 64 bit

**Comment by dustinblackman** [comment]
And if you were to run as admin?

**Comment by ralausem** [comment]
I managed to solve thanks for your attention. I noticed that some folders called: Recommended in the directory: C: \ Riot Games \ League of Legends \ Config was corrupted and illegible would be those of 2 champions fizz and gangplanki so I renamed the folders that were corrupted to any name and created another folder with the name Recommended to replace it and worked out

**Comment by dustinblackman** [comment]
Odd. I'm unsure why those are there. Championify only uses the English names for folders and files, I'm assuming it must of been something else. Glad you got it working!
