### ISSUE TITLE
Championify doesn't works on my pc

### ISSUE THREAD

**Issue by DakrXIX** [dustinblackman/Championify#296]
I tried in all ways, but is freezed
![sin titulo](https://cloud.githubusercontent.com/assets/28656242/26007576/25007fd6-370f-11e7-9798-4bc84f908454.png)

**Comment by dustinblackman** [comment]
Could you submit your logs, please? The file can be found at C:/Users/YOURNAME/AppData/Roaming/Championify/championify.log.txt

**Comment by DakrXIX** [comment]
The file isn't there

**Comment by DakrXIX** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/28656242/26023770/c767fb5a-3791-11e7-8ecb-aa41abfb7e0d.png)

**Comment by dustinblackman** [comment]
Odd. What happens if you run as an admin?

**Comment by DakrXIX** [comment]
Happen the same, even I turn off the antivirus and nothing

**Comment by dustinblackman** [comment]
To confirm, you do have 2.0.4 installed correct? https://github.com/dustinblackman/Championify/releases/tag/2.0.4

**Comment by DakrXIX** [comment]
Yes, Tried to download in Zip and same thing, isn't working

**Comment by DakrXIX** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/28656242/26042196/43aa1f0c-3901-11e7-850f-af4b60df763a.png)

**Comment by DakrXIX** [comment]
My apologies, wasn't your pc my usser was failed some kinds of this programs, is working ok, thanks!

**Comment by dustinblackman** [comment]
Good stuff!
