### ISSUE TITLE
Retrieving item sets from op.gg doesn't seem to work anymore

### ISSUE THREAD

**Issue by AlexEndris** [dustinblackman/Championify#297]
It doesn't show the current version nor does it reliably download the item sets. Sometimes it does some, but most of the time I end up with no item sets at all. Also, when finished downloading, the window looks like this: 
![image](https://cloud.githubusercontent.com/assets/5750795/26034376/12c680be-38bc-11e7-8a5b-d1c496275435.png)
Might be, because of that.

**Comment by dustinblackman** [comment]
Just did a full import with op.gg and didn't see a problem. If you see it break again, could you pass me your log before running another import, please? C:/Users/YOURNAME/AppData/Roaming/Championify/championify.log.txt

**Comment by AlexEndris** [comment]
Funny enough, now it works for me too... I can only imagine that op.gg had some difficulties. Even the blank screen is "fixed". Well, if I experience that again, I'll give you the log. Thanks!
