### ISSUE TITLE
It doens't start on my Mac Os X last version

### ISSUE THREAD

**Issue by AGPazed** [dustinblackman/Championify#299]
I just installed championify but when i run it, appear an issue message who say "Cannot read property 'winPercent' of undefined"
Next it ask if i tryed to run it in amministration mode or maybe my antivirus/firewall is blocking it..also i can read that he ask to me to press on "upload" for check in my log file for see what going wrong but if i do it, it says to me that is impossible. What can i do? My Mac Os X have thr last version of the program as i already wrote in the title..please help me i really need it

**Comment by dustinblackman** [comment]
It could of been that Championgg was down. Give it a shot again.

**Comment by AGPazed** [comment]
![img-20170519-wa0118](https://cloud.githubusercontent.com/assets/28819822/26409377/b965c092-40a0-11e7-93f0-f8043267dd10.jpg)
This is the problem that appear. Even if i start it again

**Comment by dustinblackman** [comment]
This had been fixed in the past, and the issue not closed.
