### ISSUE TITLE
Garena check #1 does not work if not running in SG region

### ISSUE THREAD

**Issue by secretdataz** [dustinblackman/Championify#3]
Because Garena appends region name after "LoL" in directory name (for example LoLTH instead of only LoL for Thai server). Checking "/GameData/Apps/LoL/Game/Config/Champions" won't detect anything except SG region (the only region without suffix in directory name).

Please see https://github.com/dustinblackman/Championify/blob/master/app.coffee#L124 for reference.

**Comment by dustinblackman** [comment]
https://github.com/dustinblackman/Championify/commit/1e9e835a2fa45eab8f502006c21b0c03dec0d3f4
