### ISSUE TITLE
Championify launch issues 

### ISSUE THREAD

**Issue by kaze514** [dustinblackman/Championify#300]
Hi,

When i launch championify this come up on my screen.
![7be862df332d469aaa446f89bbe46cd2](https://cloud.githubusercontent.com/assets/28839036/26283208/7f63d7dc-3e23-11e7-9de9-abaf91cb0603.png)

Thanks for the answer.

**Comment by dustinblackman** [comment]
Could you submit your logs, please? The file can be found at C:/Users/YOURNAME/AppData/Roaming/Championify/championify.log.txt

**Comment by kaze514** [comment]
Thanks for the answer,
but i can't find it.
![c248f1a6275e4eeb8c617dca81ae6dba](https://cloud.githubusercontent.com/assets/28839036/26359508/f3ece5e0-3fd5-11e7-996b-da71fa07b43b.png)

**Comment by dustinblackman** [comment]
Did you use the ZIP or run the Installer?

**Comment by kaze514** [comment]
I used the installer

**Comment by KilogramHours** [comment]
I've had this issue for over 5 Months now and no matter how many times Championify updates nothing seems to work.

**Comment by dustinblackman** [comment]
Issue is stale and lacks details, closing. Feel free to open a new one if the issue persists.
