### ISSUE TITLE
Help with download placement

### ISSUE THREAD

**Issue by WildfireGriffin** [dustinblackman/Championify#303]
When I click the download button it pulls up my folders and asks me to choose a file to download it under. If you can just tell me step by step how to get to the file that would be great. (^.^)

**Comment by dustinblackman** [comment]
You can pick from the quick downloads at the top of the [latest release](https://github.com/dustinblackman/Championify/releases), if on Windows I'd suggest the `Setup.exe`.

**Comment by WildfireGriffin** [comment]
Yeah, it still asks me where I want it to be downloaded. Is it just an app that opens when I open league because I wasn't sure if it was something like Minecraft when you download texture packs and they go into a specific folder.
