### ISSUE TITLE
Does not work anymore after Patch 7.11

### ISSUE THREAD

**Issue by FraggerDaddy** [dustinblackman/Championify#304]
Hi,

since the latest patch (7.11) championify processes all the sites, but it does not download anything anymore.

Hope you can fix it, really love the program.

**Comment by dustinblackman** [comment]
I'm not seeing a problem, works fine for me. Could you post your log please? You can find it at C:\Users\YOURNAME\AppData\Roaming\Championify\championify.log.txt

**Comment by Asgardiian** [comment]
Same here, my log:

[championify.log.txt](https://github.com/dustinblackman/Championify/files/1051067/championify.log.txt)

**Comment by FraggerDaddy** [comment]
[championify.log.txt](https://github.com/dustinblackman/Championify/files/1052596/championify.log.txt)

Here is mine, tried again today, but no change.

**Comment by dustinblackman** [comment]
@Asgardiian Seeing a weird error code with yours. Tried running it as admin?

@FraggerDaddy I see nothing wrong in your logs. Item sets don't exist in game?

**Comment by FraggerDaddy** [comment]
Hmm i cant login right now thanks to the euw log in problems, but i went to check the itemsets, and they say that they are for patch 7.11, but championify still says that all itemsets are not available.

It is also a lot quicker than normally, so i am still not sure if its right or not?! 

I will check ingame when i am finally able to log back in.

**Comment by dustinblackman** [comment]
@FraggerDaddy Wait, the issue that Probuilds had a lot of items missing? That's because they are missing on Probuilds and aren't yet available.

**Comment by FraggerDaddy** [comment]
oh fuck me xD i apparently cant read it seems. It showed so many not available that i miss read/interpreted it as the different hosters and not champions on the same hoster.

I feel stupid now, i guess atleast @Asgardiian could mention his problem here.

Sorry to bother you, thanks again for this great program.

**Comment by dustinblackman** [comment]
No worries! Glad that's worked out.
