### ISSUE TITLE
what does the skill lists mean?

### ISSUE THREAD

**Issue by murray0** [dustinblackman/Championify#306]
when I create new game after downloading items, the skill lists is different, and  I don't know what mean about the last three items, any description?

**Comment by dustinblackman** [comment]
You mean your upgrade paths for your skills? It's different as the data is [aggregated](http://champion.gg/champion/Malzahar/Middle) and has potential to change over time depending on overall player preference. The last three items (`Q >W > E` are the short hand to define the priority you should upgrade your skills. In the example `Q > E >W`, you max Q, then E, then W.

**Comment by murray0** [comment]
yeah, the item title show right now, perfect thx
