### ISSUE TITLE
Banned from League

### ISSUE THREAD

**Issue by NyneTeaNyne** [dustinblackman/Championify#310]
I have just received a message telling me that I just got banned from League of Legends, telling myself that I used third-party programs to improve my performance, I tried to explain to them that the only software I used was Championify and he only created builds, but he did not agree to remove the ban, I just wanted to ask you if you could not do anything ?

**Comment by dustinblackman** [comment]
Sorry to hear you've been banned, however he isn't speaking about Championify. Championify has been approved by countless Rioters and follows the [item set docs](https://developer.riotgames.com/item-sets.html).  Riot most likely detected something else whether you were using other software or not.
