### ISSUE TITLE
Problem after load build - ''Failed to write item set json file''

### ISSUE THREAD

**Issue by Asgardiian** [dustinblackman/Championify#311]
![problem](https://user-images.githubusercontent.com/29190216/27763279-f9385242-5e56-11e7-8ddf-fbf691b90aa1.png)

Already deactivated Antivirus and running as admin

here the log:
[championify.log.txt](https://github.com/dustinblackman/Championify/files/1117196/championify.log.txt)

**Comment by dustinblackman** [comment]
Dup. https://github.com/dustinblackman/Championify/issues/256
