### ISSUE TITLE
Can't get the items to show after import

### ISSUE THREAD

**Issue by sonnyd19** [dustinblackman/Championify#314]
After installing using both .zip and .exe files I can't get the item sets to show in game. I can't get it to open League after importing either. It auto-detects my league folder but the issues still persist.

**Comment by dustinblackman** [comment]
Could you submit your logs, please? The file can be found at C:/Users/YOURNAME/AppData/Roaming/Championify/championify.log.txt

**Comment by sonnyd19** [comment]
[championify.log.txt](https://github.com/dustinblackman/Championify/files/1204163/championify.log.txt)

**Comment by dustinblackman** [comment]
Looks like you don't have your league directory selected correctly. It can't find the league executable either.

**Comment by sonnyd19** [comment]
Do you have any ideas that could help? It's on my C:/ and I can find the execute file in the league of legends folder i selected but nothing happens after importing. It doesn't launch league

**Comment by sonnyd19** [comment]
The itemsets are showing up in the champions folder but I can't access them game.

**Comment by dustinblackman** [comment]
Where do you have League installed?

**Comment by sonnyd19** [comment]
The same spot as where I select the Championify install file. C:\Riot Games\League of Legends the client.exe is there

**Comment by sonnyd19** [comment]
Ah got it to work! Thanks for answering ma boosted ass questions lol

**Comment by dustinblackman** [comment]
No worries, glad it works!
