### ISSUE TITLE
Can't Get riot version

### ISSUE THREAD

**Issue by Seko1337** [dustinblackman/Championify#319]
In the main interface i noticed that all the info under import button is unknow or loading , screenshot : 
[http://imgur.com/Z3ZwDlp](http://imgur.com/Z3ZwDlp)
and when i tried to click import it shows an error : can't get riot version .
[http://imgur.com/a/BrqmK](http://imgur.com/a/BrqmK)
btw i just installed a fresh windows 7 sp1 32 bit 2 days ago , also checked riot api status and seems like its the problem isn't from there  .
logs : [https://pastebin.com/raw/22bzAxay](https://pastebin.com/raw/22bzAxay)

**Comment by dustinblackman** [comment]
@Seko1337 Something on your system is preventing Championify from accessing the internet.

**Comment by Seko1337** [comment]
i tried turning off my firewall , i have a question can internet exporer settings cause something like this ?
[http://imgur.com/a/AYhMm](http://imgur.com/a/AYhMm)

**Comment by dustinblackman** [comment]
I rarely use Windows so I'm unsure. With your firewall off, something still remains to be blocking it. What Antivirus are you using?

**Comment by GijonDev** [comment]
Starting it as administrator should fix it.

**Comment by Seko1337** [comment]
Well i had to change hard drive , and after installing a fresh copy of Windows 7 32 bit on it , everything is working fine , thanks for your time .
