### ISSUE TITLE
Shortened skill orders don't have full accuracy for first 3-4 skills

### ISSUE THREAD

**Issue by mpcomplete** [dustinblackman/Championify#32]
A skill order like http://champion.gg/champion/Quinn is shortened to "Q>E>W" in both the Most Frequent and Highest Win Rate builds. But one starts with "QEWQ" and the other starts with "QEQW". I recommend you separate the first 3-4 skills and list them in addition to the shortened order.

I mentioned this in the reddit thread but I'm not sure if I was clear about what I meant. See https://github.com/mpcomplete/lisa/blob/master/lib/js/outputFormat.js#L84 for the way I handle this (there's no need to sort the skills - you know if a skill is finished by level 9 that it is maxed, and by level 13 that it is second-to-max.)

**Comment by dustinblackman** [comment]
Trinkets | Q.E.W.Q - Q>E>W ?

**Comment by mpcomplete** [comment]
Perfect!
