### ISSUE TITLE
Champion.gg has become unusable.

### ISSUE THREAD

**Issue by GijonDev** [dustinblackman/Championify#322]
Maybe they changed their API? Or maybe its just me... Pretty annoying however.

**Comment by dustinblackman** [comment]
I'll need more of a description that that. I don't have any problems on my end. What is wrong exactly? Importing the data? The item sets ingame itself?

**Comment by dustinblackman** [comment]
Yep looks like something is wrong with their routing on their pages. I'll hit them up. Thanks.

**Comment by GijonDev** [comment]
Working as of 23:34 CET
