### ISSUE TITLE
I got banned for using championify

### ISSUE THREAD

**Issue by WenaWena** [dustinblackman/Championify#328]
Title. A rioter said me that championify is a cause of ban. Got permabanned.  I know that this is not the correct place to post, but I don't know where to post it.

_Sent from my Xiaomi MI 5s using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by michalwidera** [comment]
This is second report of such issue. Worth to check.
I've found following thread on reddit.
https://www.reddit.com/r/leagueoflegends/comments/47i2rx/so_is_championify_bannable_now/

Look's like there could be some issues with some Rioters that do not strictly follow politics or there is ?
Did you use championify while client works ?
Main reason is there that no files are changed during game.

Dustin, Is it worth to implement such functionality to close championify where lol client or game works?

**Comment by dustinblackman** [comment]
Send screenshots if Riot support is telling you that you've been banned for Championify and I'll see what's up. Otherwise Championfiy is used by many Rioters themselves, Support is aware of what it does, the code is open source, and is most likely __not__ the reason you've been banned.

**Comment by WenaWena** [comment]
@dustinblackman they didn't told me why I got banned, but they said "the software can be detected as advantage even if you don't know about it" or something like that (I'm not so good at English so that wasn't textual, but it was something like that) about the screenshot, how do I post that with fasthub? (Newbie xd)

_Sent from my Xiaomi MI 5s using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dustinblackman** [comment]
So then nothing to do with Championify, you've just assumed.

**Comment by WenaWena** [comment]
@dustinblackman i mean they said that before I said that I just used championify

_Sent from my Xiaomi MI 5s using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
