### ISSUE TITLE
Lolmasters and Lolalytics aren't updating, I dnt know if it is only me?

### ISSUE THREAD

**Issue by AgileCoon666** [dustinblackman/Championify#329]
Basically, Lolaytics version is still 7.15, and I am used to their item sets being first. Secondly, lol master version is saying "loading...", for like the past two weeks maybe longer...  
I do think it is only me because I haven't seen anything about it, and I do not know where else to report it, so pls excuse me if this is the wrong place.  Is there something I am missing? I have seen the two in question have had their sites updated and so on.  lastly, is it just me? If so may I be advised on how to fix it pls

**Comment by dustinblackman** [comment]
Lolalaytics have to update themselves first, it looks like their API is still returning 7.15. Lolmasters does seem to have changed their pages a bit. I'll get that fixed up.

**Comment by AgileCoon666** [comment]
Thank you, for that that was quick I will wait on Lolalytics

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
