### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by dustinblackman** [dustinblackman/Championify#33]

**Comment by AlexanderOtavka** [comment]
I may be able to do that for you.  What are you thinking for the icon?  I can make it match the color scheme of the GUI, but I don't know if you have any sort of mascot that you want portrayed.

**Comment by dustinblackman** [comment]
I'm honestly lost when it comes to an icon, I'm a terrible designer (cough cough, the GUI). Do anything you think is best, but avoid following the color scheme as I have a redesign in the works.

**Comment by AlexanderOtavka** [comment]
Ok, I would like to make the icon to match with the look and feel of the app, do you know by any chance what the primary theme color for the redesigned version will be in RGB?

**Comment by dustinblackman** [comment]
Not yet, still in the thinking process.

**Comment by AlexanderOtavka** [comment]
That's fine, let me know when you know and I'll get right on it.  In the mean time, I'll do some brainstorming for the content of the icon.  I'm thinking maybe a stylized tri force or something.
