### ISSUE TITLE
Rare bug, cosmetic things and Koreanbuilds.

### ISSUE THREAD

**Issue by itsHardStyl3r** [dustinblackman/Championify#330]
Sometimes there's a bug with empty information after downloading item sets. Here's a photo:
http://i.imgur.com/tqXEkL4.png
Koreanbuilds are not downloading (@latest version 2.0.7):
http://i.imgur.com/9QyIH3q.png
Also, I think that strings shouldn't be capital on every word.
Example (just because my english is so bad):
Don't Delete Outdated Item Sets->Don't delete outdated item sets
or maybe it would look better if there won't be any capital letters, just sayin'.
There's a bad translation in Polish. It should be "Wybierz katalog League of Legends" instead of "Wybierz League of Legends katalog".

I don't know how to say it:
If there's no Warwick on KoreanBuilds@7.16 then it should download Warwick from KoreanBuilds@7.15 or even lower if there was no builds and if user wants to do so.

Sorry for bad english. Have a nice day :)

**Comment by dustinblackman** [comment]
For the first issue, I'll need logs please. C:/Users/YOURNAME/AppData/Roaming/Championify/championify.log.txt

For KoreanBuilds it works just fine for me. Are you able to access koreanbuilds.net in a browser?

Getting item sets from older patches is not possible. No source Championify has keeps old builds.

**Comment by HardStyl3rTV** [comment]
I guess the log won't help you, because I used Championify about 4-5 times after reporting the issue and I got it fully working without anything disappearing at all. Koreanbuilds now work. I meant to use KoreanBuilds for older patches, because they store them.

**Comment by dustinblackman** [comment]
Ah you're right, I had missed they do in fact keep them. Cool, I can add it to a feature list. Thanks!

**Comment by jehosua** [comment]
again its not working with korean builds, anyone knows how to fix it? or just wait for update?
