### ISSUE TITLE
ARAM LolFlavor

### ISSUE THREAD

**Issue by thorsammer** [dustinblackman/Championify#333]
All summoners item sets are working properly but on three different computers and setups The ARAM item sets are not downloading.  Not sure what the issue is, but I'm happy to provide any additional documentation you might need.  Not sure how to get a log of everything it processes, but with the settings on the below screenshot it definitely ONLY processes the champion.gg champs makes no mention of LolFlavor.

![screenshot 2017-08-29 12 18 18](https://user-images.githubusercontent.com/20046758/29831858-76b93d40-8cb4-11e7-8ecc-57f85c6ca736.png)

**Comment by Darkrai87** [comment]
I can confirm having this problem as well.

**Comment by dustinblackman** [comment]
Looks like Lolflavor is no long recording ARAM games. I'll investigate deeper, but I'll likely remove/replace the feature if they no longer support. http://www.lolflavor.com/data/statsARAM.json

**Comment by arrabas** [comment]
from http://www.aram-ranked.info/ it says 

> ARAM game acquisition has not worked since July 24th. please wait for our follow up...
so it probably is some problem on riot side

**Comment by Gorthezar** [comment]
Same problem as well just noticed it today.

**Comment by bayu01** [comment]
@dustinblackman The link you posted http://www.lolflavor.com/data/statsARAM.json is now working. At this moment is returning something like:
`
{"champions":[{"Id":185,"champID":222,"totalGames":260,"buildType":"ARAM","winPercent":60.0,"name":"Jinx"},{"Id":110,"champID":9,"totalGames":241,"buildType":"ARAM","winPercent":61.0,"name":"Fiddlesticks"},
...
{"Id":396,"champID":72,"totalGames":29,"buildType":"ARAM","winPercent":66.0,"name":"Skarner"},{"Id":4,"champID":266,"totalGames":20,"buildType":"ARAM","winPercent":35.0,"name":"Aatrox"}]}
`
whereas before it was returning just empty brackets.  Does that mean that all we need to do is just re-import?

Also, the direct download link for their recommended item set for specific champions is working as well. i.e. http://www.lolflavor.com/champions/Jinx/Recommended/Jinx_aram_scrape.json returns:
`
{"isGlobalForChampions":false,"associatedChampions":[],"mode":"any","blocks":[{"items":[{"count":1,"id":"2003"},{"count":1,"id":"2031"},{"count":1,"id":"2032"},{"count":1,"id":"2033"},{"count":1,"id":"2055"},{"count":1,"id":"2047"},{"count":1,"id":"2138"},{"count":1,"id":"2139"},{"count":1,"id":"2140"}],"type":"Consumable"},{"items":[{"count":1,"id":"1036"},{"count":1,"id":"1029"}],"type":"Starter"},{"items":[{"count":1,"id":"3031"},{"count":1,"id":"3085"},{"count":1,"id":"3184"},{"count":1,"id":"1001"}],"type":"Core Items - Max Skill: Q>W>E"},{"items":[{"count":1,"id":"3094"},{"count":1,"id":"3087"},{"count":1,"id":"3072"},{"count":1,"id":"3036"},{"count":1,"id":"3033"},{"count":1,"id":"3508"},{"count":1,"id":"3046"}],"type":"Core Alternatives - Endgame Items "},{"items":[{"count":1,"id":"3006"}],"type":"Boots"},{"items":[{"count":1,"id":"3153"},{"count":1,"id":"3139"},{"count":1,"id":"3035"},{"count":1,"id":"3022"},{"count":1,"id":"3156"},{"count":1,"id":"3008"},{"count":1,"id":"3034"}],"type":"Situational Items"}],"associatedMaps":[],"map":"any","title":"ARAM FOTM - 9/17/2017","isGlobalForMaps":true,"sortrank":4,"type":"custom","champion":"Jinx","priority":false}
`

**Comment by thorsammer** [comment]
Resolved.  Just downloaded item sets.  Seems likely to have been a LoL issue.

**Comment by dustinblackman** [comment]
Can confirm it's working again. Thanks for the help guys. 👍

**Comment by alterlove** [comment]
Please, remove lolflavor, no longer available anymore.
