### ISSUE TITLE
Can't get Riot Version

### ISSUE THREAD

**Issue by TutioPalkia** [dustinblackman/Championify#335]
I was trying to update the item sets and got this error, I assumed that was my firewall so I turned off and retried to update but I always get the same error.

**Comment by TutioPalkia** [comment]
this is what i see

![sdfas](https://user-images.githubusercontent.com/31644494/30047246-f3cddb78-91c4-11e7-987a-317974385e21.jpg)
![sin titulo](https://user-images.githubusercontent.com/31644494/30047249-f51e7d20-91c4-11e7-8b98-0d1093133542.jpg)

**Comment by dustinblackman** [comment]
I have a feeling Riot's API may of been having trouble. If you were to try now would it work?

**Comment by njql007** [comment]
Looks like some temporary issue with Riot's "ddragon" endpoint...

**Comment by tomioueda** [comment]
I'm also getting this too. Seems like the same ddragon endpoint problem as well

**Comment by dustinblackman** [comment]
Yeah retrying is built in but only within a short period.
