### ISSUE TITLE
somebody help me

### ISSUE THREAD

**Issue by feiren200** [dustinblackman/Championify#336]
I am a player from China , my English is very bad . so look the picture.
![61 h itpdn euuvgsu5k f](https://user-images.githubusercontent.com/28645656/30355890-a447eef4-9868-11e7-91fa-74c606c066ec.png)
this is my championify setting.
![x5hn3t 0x gxzr dqb](https://user-images.githubusercontent.com/28645656/30355909-bf89c2a0-9868-11e7-9e2c-5e4f527286ad.png)
I don't know when it happened. It may have been the latest update.
help me

**Comment by feiren200** [comment]
Always lose one of the recommended equipment. I think

**Comment by dustinblackman** [comment]
The last item is supposed to be Molten's Edge. This is the same bug as https://github.com/dustinblackman/Championify/issues/238, closing as it's a dup.
