### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by simonfly80** [dustinblackman/Championify#338]
Championify 2.0.8
macOS Sierra 10.12.6
League Of Legends 7.18 (but also 7.14-15-16-17)
After LOL introduced the ITEM CARD, I cant see in game the set created from Champioinify.
But Championify at open control what is imported and say LOCAL ITEM VERSION 7.18
I've tried to cancel lol and re-install it, but nothing.

**Comment by dustinblackman** [comment]
You have your league Application selected correctly? Usually it's `/Applications/League Of Legends.app`

**Comment by dustinblackman** [comment]
Stale, closing.
