### ISSUE TITLE
Downloading champion updates freezes the internet connection

### ISSUE THREAD

**Issue by gerriet-hinrichs** [dustinblackman/Championify#339]
When I'm updating champion builds, after a short time the download stops and completely freezes my internet: I can't even open the Google front-page in my browser and ping reports 100% package loss, but as far as I know other devices in the same network are not affected by that.
After a while the download slowly continues, recovers its initial speed after a few processed champions to then freeze again after a short time.

Despite the internet freeze, Championify seems to work correctly: Builds are updated and are available in game.

[championify.log.txt](https://github.com/dustinblackman/Championify/files/1326529/championify.log.txt)

**Comment by adrian-helberg** [comment]
Had the same issue. After restartung Championify it continued downloading as expected and finished properly.

**Comment by dustinblackman** [comment]
Are you on some kind of school/corporate network? Your log shows a lot of timeout errors. Championify is making quite a lot of concurrent calls at a time, especially when using more than one source. If your entire internet connection on your system is slowing down, it sounds like something external is limiting the amount of concurrent connections.

**Comment by gerriet-hinrichs** [comment]
I'm at home, not in any school/corporate network. As far as I know my local network configuration does not limit the number of concurrent downloads, so it's most likely my network provider.

My suggestion on this issue: Add a configuration option to limit the number of concurrent downloads.

**Comment by dustinblackman** [comment]
Fixed in https://github.com/dustinblackman/Championify/pull/342
