### ISSUE TITLE
Add a 'Skip' or 'Start League' button to the main screen

### ISSUE THREAD

**Issue by rauscheb12** [dustinblackman/Championify#343]
Adding a 'Launch' button to the main screen would let users set their League shortcuts to Championify without having to update their builds every time to start the game. My Rainmeter skin currently launches Championify instead of LoL directly (I'd forget to update regularly otherwise), so it'd be nice to not have to sit through the update every single time (op.gg takes forever to update).

**Comment by dustinblackman** [comment]
This sounds a tad silly. Championify isn't mean to be a "portal" that's used before you launch League, but a tool you run every so often. If you'd like to automate to keep your builds up to date, consider using the [command line parameters](https://github.com/dustinblackman/Championify#command-line-parameters).
