### ISSUE TITLE
stuck on updating

### ISSUE THREAD

**Issue by Fearboy1** [dustinblackman/Championify#345]
stuck on 73% after Alistar.

**Comment by dustinblackman** [comment]
I'll need logs please. C:/Users/YOURNAME/AppData/Roaming/Championify/championify.log.txt

**Comment by nbbsn** [comment]
I have the same issue and it seems related to op.gg. When I deselect op.gg as a source the update goes through without an issue. Also op.gg does not return a version in the main screen.

[Here's a log from when I had op.gg enabled](https://gist.github.com/nbbsn/55a22bd9c8708bbbf113c14f626371a4)

**Comment by AlexEndris** [comment]
op.gg has changed the layout. Maybe that's it?

**Comment by dustinblackman** [comment]
op.gg has reverted to their previous layout, and the source now works again.
