### ISSUE TITLE
KoreanBuilds does not have an item set despite being selected

### ISSUE THREAD

**Issue by dhdeanha** [dustinblackman/Championify#346]
Even though KoreanBuilds is selected, it is not appearing when I start up league, or when I look inside the Champions folder in Riot Games
[championify.log.txt](https://github.com/dustinblackman/Championify/files/1380679/championify.log.txt)
{
  "prefs_version": "2.0.9",
  "locale": "en",
  "install_path": "C:/Riot Games/League Of Legends/",
  "champ_path": "Config/Champions/",
  "local_is_version": "7.20",
  "options": {
    "splititems": true,
    "skillsformat": true,
    "consumables": true,
    "consumables_position": "beginning",
    "trinkets": true,
    "trinkets_position": "beginning",
    "locksr": false,
    "sr_source": [
      "koreanbuilds",
      "lolflavor"
    ],
    "dontdeleteold": false,
    "aram": false
  }
}

**Comment by dustinblackman** [comment]
Fixed in 2.0.10
