### ISSUE TITLE
KoreanBuilds not updating

### ISSUE THREAD

**Issue by dhdeanha** [dustinblackman/Championify#349]
It don't work
[championify.log.txt](https://github.com/dustinblackman/Championify/files/1384887/championify.log.txt)
{
  "prefs_version": "2.0.9",
  "locale": "en",
  "install_path": "C:/Riot Games/League Of Legends/",
  "champ_path": "Config/Champions/",
  "local_is_version": "7.20",
  "options": {
    "splititems": true,
    "skillsformat": true,
    "consumables": true,
    "consumables_position": "beginning",
    "trinkets": true,
    "trinkets_position": "beginning",
    "locksr": false,
    "sr_source": [
      "koreanbuilds",
      "lolflavor"
    ],
    "dontdeleteold": false,
    "aram": false
  }
}

**Comment by ProDread** [comment]
Confirmed. Still not working as of lastest build (2.0.10)

**Comment by dustinblackman** [comment]
I've just run a full import on 2.0.10 for KoreanBuilds and it works just fine. Try again and if there's still an issue I'll reopen this.
