### ISSUE TITLE
Championify does not complete after "patch"

### ISSUE THREAD

**Issue by dhdeanha** [dustinblackman/Championify#352]
[championify.log.txt](https://github.com/dustinblackman/Championify/files/1404569/championify.log.txt)

-------------------------------------
{
  "prefs_version": "2.0.11",
  "locale": "en",
  "install_path": "C:/Riot Games/League Of Legends/",
  "champ_path": "Config/Champions/",
  "local_is_version": "7.20",
  "options": {
    "splititems": true,
    "skillsformat": true,
    "consumables": true,
    "consumables_position": "beginning",
    "trinkets": true,
    "trinkets_position": "beginning",
    "locksr": false,
    "sr_source": [
      "koreanbuilds",
      "lolflavor"
    ],
    "dontdeleteold": false,
    "aram": false
  }
}

**Comment by dustinblackman** [comment]
Gonna need more of a description for this one.

**Comment by dhdeanha** [comment]
![capture](https://user-images.githubusercontent.com/8054498/31975578-2ac220c8-b900-11e7-861f-937db409fc9f.JPG)
Shows this around 96% it's probably done maybe just a visual error who knows

**Comment by dustinblackman** [comment]
Dup. https://github.com/dustinblackman/Championify/issues/354
