### ISSUE TITLE
[Windows] After the import there is nothing

### ISSUE THREAD

**Issue by Soraph** [dustinblackman/Championify#354]
![image](https://user-images.githubusercontent.com/1741291/31897331-4e400334-b816-11e7-9f11-02b7e1857161.png)

**Comment by dustinblackman** [comment]
Could you submit your logs, please? The file can be found at C:/Users/YOURNAME/AppData/Roaming/Championify/championify.log.txt

**Comment by Soraph** [comment]
[championify.log.txt](https://github.com/dustinblackman/Championify/files/1407858/championify.log.txt)

**Comment by dustinblackman** [comment]
Does the blank page happen when you boot the app or during import?

**Comment by Soraph** [comment]
After the import, in-game the builds are correctly displayed

**Comment by johnsaucier** [comment]
i have this problem as well.

**Comment by elpace** [comment]
i have this same thing - import works and all sets are there, but i need to close the program and launch league manually

**Comment by lav0s** [comment]
{"level":"info","message":"Processing Koreanbuilds: Varus","timestamp":"2017-10-26T00:11:57.975Z"}
{"message":"","stack":"RequestError\n    at requester.then.res (C:\\Users\\Lav0s\\AppData\\Local\\Championify\\app-2.0.11\\resources\\app.asar\\js\\helpers\\request.js:150:20)\n    at tryCatcher (C:\\Users\\Lav0s\\AppData\\Local\\Championify\\app-2.0.11\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\Lav0s\\AppData\\Local\\Championify\\app-2.0.11\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\Lav0s\\AppData\\Local\\Championify\\app-2.0.11\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\Lav0s\\AppData\\Local\\Championify\\app-2.0.11\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\Lav0s\\AppData\\Local\\Championify\\app-2.0.11\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:691:18)\n    at Promise._fulfill (C:\\Users\\Lav0s\\AppData\\Local\\Championify\\app-2.0.11\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:636:18)\n    at Request._callback (C:\\Users\\Lav0s\\AppData\\Local\\Championify\\app-2.0.11\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\nodeback.js:42:21)\n    at Request.self.callback (C:\\Users\\Lav0s\\AppData\\Local\\Championify\\app-2.0.11\\resources\\app.asar\\node_modules\\request\\request.js:199:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (C:\\Users\\Lav0s\\AppData\\Local\\Championify\\app-2.0.11\\resources\\app.asar\\node_modules\\request\\request.js:1036:10)\n    at emitOne (events.js:101:20)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (C:\\Users\\Lav0s\\AppData\\Local\\Championify\\app-2.0.11\\resources\\app.asar\\node_modules\\request\\request.js:963:12)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)","code":500,"url":"http://koreanbuilds.net/champion/Thresh/Mid/7.20/-1","body":"\n\n<!DOCTYPE html>\n<html lang=\"en\">\n    <head>\n        <title>Error</title>\n        <link rel=\"shortcut icon\" href=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAlFJREFUeNqUU8tOFEEUPVVdNV3dPe8xYRBnjGhmBgKjKzCIiQvBoIaNbly5Z+PSv3Aj7DSiP2B0rwkLGVdGgxITSCRIJGSMEQWZR3eVt5sEFBgTb/dN1yvnnHtPNTPG4PqdHgCMXnPRSZrpSuH8vUJu4DE4rYHDGAZDX62BZttHqTiIayM3gGiXQsgYLEvATaqxU+dy1U13YXapXptpNHY8iwn8KyIAzm1KBdtRZWErpI5lEWTXp5Z/vHpZ3/wyKKwYGGOdAYwR0EZwoezTYApBEIObyELl/aE1/83cp40Pt5mxqCKrE4Ck+mVWKKcI5tA8BLEhRBKJLjez6a7MLq7XZtp+yyOawwCBtkiBVZDKzRk4NN7NQBMYPHiZDFhXY+p9ff7F961vVcnl4R5I2ykJ5XFN7Ab7Gc61VoipNBKF+PDyztu5lfrSLT/wIwCxq0CAGtXHZTzqR2jtwQiXONma6hHpj9sLT7YaPxfTXuZdBGA02Wi7FS48YiTfj+i2NhqtdhP5RC8mh2/Op7y0v6eAcWVLFT8D7kWX5S9mepp+C450MV6aWL1cGnvkxbwHtLW2B9AOkLeUd9KEDuh9fl/7CEj7YH5g+3r/lWfF9In7tPz6T4IIwBJOr1SJyIGQMZQbsh5P9uBq5VJtqHh2mo49pdw5WFoEwKWqWHacaWOjQXWGcifKo6vj5RGS6zykI587XeUIQDqJSmAp+lE4qt19W5P9o8+Lma5DcjsC8JiT607lMVkdqQ0Vyh3lHhmh52tfNy78ajXv0rgYzv8nfwswANuk+7sD/Q0aAAAAAElFTkSuQmCC\">\n        <style>\n            html, body, pre {\n                margin: 0;\n                padding: 0;\n                font-family: Monaco, 'Lucida Console', monospace;\n                background: #ECECEC;\n            }\n            h1 {\n                margin: 0;\n                background: #A31012;\n                padding: 20px 45px;\n                color: #fff;\n                text-shadow: 1px 1px 1px rgba(0,0,0,.3);\n                border-bottom: 1px solid #690000;\n                font-size: 28px;\n            }\n            p#detail {\n                margin: 0;\n                padding: 15px 45px;\n                background: #F5A0A0;\n                border-top: 4px solid #D36D6D;\n                color: #730000;\n                text-shadow: 1px 1px 1px rgba(255,255,255,.3);\n                font-size: 14px;\n                border-bottom: 1px solid #BA7A7A;\n            }\n        </style>\n    </head>\n    <body>\n        <h1>Oops, an error occurred</h1>\n\n        <p id=\"detail\">\n            This exception has been logged with id <strong>75mje27ga</strong>.\n        </p>\n\n    </body>\n</html>\n\n\n\n\n\n\n\n","type":"RequestError","ua":"win32 10.0.15063","locale":"en","level":"warn","timestamp":"2017-10-26T00:11:58.302Z"}
{"level":"info","message":"Processing Koreanbuilds: Vayne","timestamp":"2017-10-26T00:11:58.303Z"}

**Comment by Soraph** [comment]
After the recent update I no longer see the error.

**Comment by dustinblackman** [comment]
This shouldn't be a problem anymore.
