### ISSUE TITLE
Nothing happens when i click on"Start league of legends"

### ISSUE THREAD

**Issue by lalamuerte** [dustinblackman/Championify#356]
Everything seems to be alright but it doesn't impact in the game, any solutions?

**Comment by dustinblackman** [comment]
What OS? What's your install path? Are you using Garena or the native client?

**Comment by lalamuerte** [comment]
I have windows 10, I have the last patch and I’m using the native client


Enviado desde Yahoo Mail para iPhone


El martes, octubre 31, 2017, 12:09 p. m., Dustin Blackman <notifications@github.com> escribió:


What OS? What's your install path? Are you using Garena or the native client?

**Comment by hollowsxd** [comment]
Does the build appear in game or it just the game that doesnt start from the app?

**Comment by dustinblackman** [comment]
Stale, closing. Feel free to ping me if the issue persists and I'll reopen.

**Comment by lalamuerte** [comment]
They game didn’t start and even if I opone up the game nothing happens 


Enviado desde Yahoo Mail para iPhone


El lunes, noviembre 20, 2017, 2:12 p. m., HollowsxD <notifications@github.com> escribió:


Does the build appear in game or it just the game that doesnt start from the app?
