### ISSUE TITLE
Championify freezes during processing of item builds (op.gg)

### ISSUE THREAD

**Issue by dertrutinator** [dustinblackman/Championify#361]
When installing item builds, Championify freezes during import at 66%. This only started happenig after the 7.22 patch, which had already caused all item builds to disappear. Re-installing Championify did nothing.

OS is Windows 10, newest Java version.

[championify.log.txt](https://github.com/dustinblackman/Championify/files/1454069/championify.log.txt)

**Comment by dustinblackman** [comment]
Championify doesn't use Java, no worries there. Could you copy/paste your preferences please? `C:\Users\schmi\AppData\Roaming\Championify\prefs.json`

**Comment by dertrutinator** [comment]
Oops, thought someone had talked about Java in a feature request.
[prefs.json.txt](https://github.com/dustinblackman/Championify/files/1454256/prefs.json.txt)
Uploading as txt because json seems to be not allowed.

**Comment by dustinblackman** [comment]
Looks like op.gg changed their website again. I'll see if I can look in to it this week.

**Comment by dertrutinator** [comment]
So not using op.gg for now should fix it? Thanks alot for the help!

**Comment by dertrutinator** [comment]
Tried another combination, probuilds.net seems to not work as well.

**Comment by dustinblackman** [comment]
Probuilds looks to be having connections problems.

**Comment by tance77** [comment]
@dustinblackman a lot of the websites are going to be changing. The new season just dropped and all Runes and Masteries have changed.
