### ISSUE TITLE
championify download stuck

### ISSUE THREAD

**Issue by 976-EVIL** [dustinblackman/Championify#363]
![image](https://user-images.githubusercontent.com/30190930/32629067-37f091c4-c555-11e7-9516-6970de664e43.png)
Hi i try to update the builds for the patch 7.22 and the app got stuck at 74% i tought that probably the problem could be my pc but y try it in a different one and is the same result, also i reinstalled championify but it was pretty much the same result.

**Comment by dustinblackman** [comment]
Do you have op.gg selected as a source?

**Comment by dustinblackman** [comment]
Stale, and I believe was fixed in the last few patches. Closing.
