### ISSUE TITLE
Black window

### ISSUE THREAD

**Issue by kabasta** [dustinblackman/Championify#364]
For a while now every time I open Championify the window is completely black and I can't update or delete my builds (stuck with 7.19 patch builds)
I tried uninstalling and reinstalling but nothing changes. Help please?
https://i.imgur.com/IrnOjsG.png

**Comment by hollowsxd** [comment]
Post your log

**Comment by dustinblackman** [comment]
Could you submit your logs, please? The file can be found at C:/Users/YOURNAME/AppData/Roaming/Championify/championify.log.txt

**Comment by kabasta** [comment]
I just reinstalled it

2017-11-20T20:35:20.868Z - info: Version: 2.0.0
2017-11-20T20:35:22.283Z - info: Checking for updates
2017-11-20T20:35:22.576Z - info: Update found, 2.0.0 to 2.1.1
2017-11-20T20:35:22.615Z - debug: Downloading https://github.com/dustinblackman/Championify/releases/download/2.1.1/Championify-2.1.1-full.nupkg to C:\Users\kabas\AppData\Local\Temp\tmp-4020AIYWRCWio1Hu\Championify-2.1.1-full.nupkg
2017-11-20T20:35:22.617Z - debug: Downloading https://github.com/dustinblackman/Championify/releases/download/2.1.1/RELEASES to C:\Users\kabas\AppData\Local\Temp\tmp-4020AIYWRCWio1Hu\RELEASES

But I think it might be problem unrelated to championify now. Similar thing happens when I open Microsoft word for example.

**Comment by dustinblackman** [comment]
It doesn't look like you've reinstalled from the latest version available in the downloads section, however that shouldn't have anything to do with it as 2.0.0 should upgrade to 2.1.1 just fine. Does the application restart after the update? Do you have a screenshot of the actual window after the updaet?

**Comment by kabasta** [comment]
Still just blank window. Here https://i.imgur.com/T5beR7K.png also similar thing happens with word at certain size window (when I change it, its visible again https://i.imgur.com/Plur7Gd.png)

**Comment by dustinblackman** [comment]
After you've run it and it's a black screen, is there anything different in your logs?

**Comment by kabasta** [comment]
Just this

{"level":"info","message":"Version: 2.1.1","timestamp":"2017-11-21T00:59:00.358Z"}
{"level":"info","message":"Checking for updates","timestamp":"2017-11-21T00:59:01.736Z"}
{"level":"info","message":"No updates found","timestamp":"2017-11-21T00:59:02.082Z"}

I think it's just some visual bug though (when I click in top left corner program closes down normally)

**Comment by dustinblackman** [comment]
Do you experience these issues when using Chrome?

I'm going to close this as it doesn't seem to be Championify related, but let me know for the question above.

**Comment by kabasta** [comment]
No, noticed it with only few programs I use. 
Mainly all Microsoft products (Office, Excel, PowerPoint) and also GeForce Experience.

**Comment by dustinblackman** [comment]
That's really weird. There must be some underlaying tech they share you're having trouble with, but I'm unsure on what.
