### ISSUE TITLE
Champion GG 6.24 while beiing on 7.22

### ISSUE THREAD

**Issue by matcourrier** [dustinblackman/Championify#365]
Hello !

I dont know if it's just about the Version Name in Lol or the actual Champion GG version but when i download the 7.22 version i get builds in Lol having a 6.24 Label.

I only selected Champion GG. split up items, deleted old builds. skill shortcut

Thx for all your work, you do a fab job !! <3

Mathieu

**Comment by dustinblackman** [comment]
Do you get two sets? 7.22 and 6.24?

**Comment by matcourrier** [comment]
Hey Dustin !

I just did some research and found where the issue came from.
In the past (before new launcher i used to have League installed on my C).
Since then i installed it on my G.

I think last time i got an update of you application, the default location
has been reset to the C ( where a League of Legend folder was still
available).

So obviously the 6.24 was from the last time i updated your application
before the new launcher.

I guess it's not a bug and more my PC configuration creating the issue.

Thx for your time !

I'm a fan of your work

Mat


2017-11-16 20:55 GMT+01:00 Dustin Blackman <notifications@github.com>:

**Comment by dustinblackman** [comment]
Ah, that explains it. Glad you figured it out. Thanks! :)
