### ISSUE TITLE
Setup "failed", but still works.

### ISSUE THREAD

**Issue by brianj64** [dustinblackman/Championify#366]
Something's wrong with the current installer, faulty stating that setup failed due to some exception, yet the program still works fine without any problems.

This is on a fresh Windows 10 Pro x64 version 1709(FCU)

Never had this issue on version 1703(CU)

Setup log: 
https://pastebin.com/ZSXL35LQ

**Comment by hollowsxd** [comment]
did you run it with admin access?

**Comment by brianj64** [comment]
Yes i did, both get the same error.

**Comment by dustinblackman** [comment]
Odd, it looks like something broke with the squirrels installer. Championify is currently a few versions behind, I can look in to updating it if it won't cause any issues.

**Comment by brianj64** [comment]
Well, the tool works fine, it's just the installer that seems to think the program failed installing when after a second clicking away "Setup Failed" opens just fine, and the uninstaller still works fine too.

**Comment by brianj64** [comment]
What i do not understand is this: "---> (Inner Exception #0) System.IO.IOException: The process cannot access the file 'C:\Users\notcy\AppData\Local\Championify\app-2.1.1\icudtl.dat' because it is being used by another process."

I made sure to delete this file prior to re-installation and it was gone, but after trying to install the program again this exception happens again.

What i think is the problem here is that Championify.exe is initialized too early and causes the file to lock-up before installation is finished.

**Comment by brianj64** [comment]
Seems like Discord also uses Squirrel so i made a fresh log: https://pastebin.com/hkQm9g1A

It seems that literally nothing is out of the ordinary and it should never have popped the Setup Failed log.
