### ISSUE TITLE
Files imported and still no items?

### ISSUE THREAD

**Issue by ImJustTooHigh** [dustinblackman/Championify#368]
Hi. I installed and imported everything correctly. But after importing is done, i try to press "Start League of Legends"- button. And there reads, "Can't start league". When in-game, there is no item sets.

**Comment by ImJustTooHigh** [comment]
![lol](https://user-images.githubusercontent.com/33851611/33051513-ee3d6990-ce72-11e7-89ed-a18543d10b36.png)

**Comment by dustinblackman** [comment]
What directory did you have selected? Also could you please upload your configs/logs?

_Config and file locations:_
_- Log: C:/Users/YOURNAME/AppData/Roaming/Championify/championify.log.txt_
_- Config: C:/Users/YOURNAME/AppData/Roaming/Championify/prefs.json_

**Comment by ImJustTooHigh** [comment]
Directory: C:\Riot Games\League of Legends

And i dont know why, but there is no directory for "Championify", in appdata. I deleted those files yesterday and imported item sets again, but now there is nothing :/

**Comment by ImJustTooHigh** [comment]
Now they suddenly show up again...
[championify.log.txt](https://github.com/dustinblackman/Championify/files/1491718/championify.log.txt)

![ddd](https://user-images.githubusercontent.com/33851611/33078051-33416a70-ceda-11e7-8912-783479b3d995.png)

**Comment by ImJustTooHigh** [comment]
LOL. It was installed to my D: drive and the old files were still on C: drive. Fixed my problem. Sorry for this, but thanks for answer <3
