### ISSUE TITLE
Some spec Not Available

### ISSUE THREAD

**Issue by adramelek** [dustinblackman/Championify#37]
As of may 31, i can't get those following build: Zyra Middle, XinZhao Top, Warwick Top, Trundle Jungle, Sion Jungle, Shen Jungle, Poppy Jungle and maybe more since i can't scroll down. All those have there build up on Champion.gg don't know why they don't get imported.

**Comment by dustinblackman** [comment]
As for 11am EST May 31st, all builds you listed currently are not available on Champion.GG (builds undefined). When the builds are available, Championify will be able to import them. :)

http://champion.gg/champion/Zyra/Middle
http://champion.gg/champion/XinZhao/Top
http://champion.gg/champion/Warwick/Top
http://champion.gg/champion/Trundle/Jungle
http://champion.gg/champion/Sion/Jungle
http://champion.gg/champion/Shen/Jungle
http://champion.gg/champion/Poppy/Jungle
