### ISSUE TITLE
Stuck at Vi and Jinx, Won't Open

### ISSUE THREAD

**Issue by KilogramHours** [dustinblackman/Championify#370]
What operating system: Windows 10
What version of Championify: 2.1.2
Please explain the issue you're encountering: Championify Stuck at Image of Vi and Jinx
Also, when I go into Task Manager it shows that multiple instances of Championify are running and I'm not sure why. 
Screenshots: https://i.imgur.com/MgWaWTO.png
Logs:

`{"message":"","stack":"UncaughtException\n    at Log.exitOnError (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify\\resources\\app.asar\\js\\logger.js:57:9)\n    at Logger._uncaughtException (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify\\resources\\app.asar\\node_modules\\winston\\lib\\winston\\logger.js:645:12)\n    at emitOne (events.js:96:13)\n    at process.emit (events.js:188:7)\n    at window.onerror (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify\\resources\\electron.asar\\renderer\\init.js:120:22)\nCause: Error: ENOENT, node_modules\\runas\\build\\Release\\runas.node not found in C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify\\resources\\app.asar\n    at notFoundError (ELECTRON_ASAR.js:115:19)\n    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:183:9)\n    at Module.load (module.js:473:32)\n    at tryModuleLoad (module.js:432:12)\n    at Function.Module._load (module.js:424:3)\n    at Module.require (module.js:483:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js:4:11)\n    at Object.<anonymous> (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js:47:4)\n    at Module._compile (module.js:556:32)\n    at Object.Module._extensions..js (module.js:565:10)\n    at Module.load (module.js:473:32)\n    at tryModuleLoad (module.js:432:12)\n    at Function.Module._load (module.js:424:3)\n    at Module.require (module.js:483:17)\n    at require (internal/module.js:20:19)","type":"UncaughtException","ua":"win32 10.0.14393","locale":"en","cause":{"code":"ENOENT","errno":-2},"rootCause":{"code":"ENOENT","errno":-2},"ownStack":"UncaughtException\n    at Log.exitOnError (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify\\resources\\app.asar\\js\\logger.js:57:9)\n    at Logger._uncaughtException (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify\\resources\\app.asar\\node_modules\\winston\\lib\\winston\\logger.js:645:12)\n    at emitOne (events.js:96:13)\n    at process.emit (events.js:188:7)\n    at window.onerror (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify\\resources\\electron.asar\\renderer\\init.js:120:22)","level":"error","timestamp":"2017-11-22T19:18:49.287Z"}
{"date":"Wed Nov 22 2017 13:18:49 GMT-0600 (Central Standard Time)","process":{"pid":6124,"uid":null,"gid":null,"cwd":"C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify","execPath":"C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify\\championify.exe","version":"v6.5.0","argv":["C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify\\championify.exe","--type=renderer","--no-sandbox","--primordial-pipe-token=6596E3B7C111D7C5A5FCCBF0B7A41475","--lang=en-US","--node-integration=true","--hidden-page","--enable-pinch","--device-scale-factor=1","--num-raster-threads=3","--content-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553","--video-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553","--mojo-channel-token=7C25A1011938E84932992D0680A3DE50","--mojo-application-channel-token=6596E3B7C111D7C5A5FCCBF0B7A41475","--channel=27708.1.1006219375\\1353137597","--mojo-platform-channel-handle=1772","/prefetch:1"],"memoryUsage":{"rss":84590592,"heapTotal":43737088,"heapUsed":29711916}},"os":{"loadavg":[0,0,0],"uptime":620668.5135595},"trace":[{"column":19,"file":"ELECTRON_ASAR.js","function":"notFoundError","line":115,"method":null,"native":false},{"column":9,"file":"ELECTRON_ASAR.js","function":"Object.module.(anonymous function) [as .node]","line":183,"method":"node]","native":false},{"column":32,"file":"module.js","function":"Module.load","line":473,"method":"load","native":false},{"column":12,"file":"module.js","function":"tryModuleLoad","line":432,"method":null,"native":false},{"column":3,"file":"module.js","function":"Module._load","line":424,"method":"_load","native":false},{"column":17,"file":"module.js","function":"Module.require","line":483,"method":"require","native":false},{"column":19,"file":"internal/module.js","function":"require","line":20,"method":null,"native":false},{"column":11,"file":"C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js","function":null,"line":4,"method":null,"native":false},{"column":4,"file":"C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js","function":null,"line":47,"method":null,"native":false},{"column":32,"file":"module.js","function":"Module._compile","line":556,"method":"_compile","native":false},{"column":10,"file":"module.js","function":"Module._extensions..js","line":565,"method":".js","native":false},{"column":32,"file":"module.js","function":"Module.load","line":473,"method":"load","native":false},{"column":12,"file":"module.js","function":"tryModuleLoad","line":432,"method":null,"native":false},{"column":3,"file":"module.js","function":"Module._load","line":424,"method":"_load","native":false},{"column":17,"file":"module.js","function":"Module.require","line":483,"method":"require","native":false},{"column":19,"file":"internal/module.js","function":"require","line":20,"method":null,"native":false}],"stack":["Error: ENOENT, node_modules\\runas\\build\\Release\\runas.node not found in C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify\\resources\\app.asar","    at notFoundError (ELECTRON_ASAR.js:115:19)","    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:183:9)","    at Module.load (module.js:473:32)","    at tryModuleLoad (module.js:432:12)","    at Function.Module._load (module.js:424:3)","    at Module.require (module.js:483:17)","    at require (internal/module.js:20:19)","    at Object.<anonymous> (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js:4:11)","    at Object.<anonymous> (C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify\\resources\\app.asar\\node_modules\\runas\\lib\\runas.js:47:4)","    at Module._compile (module.js:556:32)","    at Object.Module._extensions..js (module.js:565:10)","    at Module.load (module.js:473:32)","    at tryModuleLoad (module.js:432:12)","    at Function.Module._load (module.js:424:3)","    at Module.require (module.js:483:17)","    at require (internal/module.js:20:19)"],"level":"error","message":"uncaughtException: ENOENT, node_modules\\runas\\build\\Release\\runas.node not found in C:\\Users\\Kegan Huntley\\Desktop\\Kegan's Folder\\Kegan's Downloads\\Championify\\resources\\app.asar","timestamp":"2017-11-22T19:18:49.293Z"}`

**Comment by dustinblackman** [comment]
The error makes it look like a file was missing in my latest release, however I just did a fresh install and made that the file was used and everything worked fine. It could potentially me your antivirus blocking it as it's meant to elevate privileges. What AV are you running?

**Comment by KilogramHours** [comment]
Just Windows Defender

**Comment by KilogramHours** [comment]
Sadly, I'm still having this issue after the update.

This has been going on since March and I haven't been able to use the app. I want to say it has something to do with Cookies being stored and causing the problem, or some type of bug within the computer that remembers Championify and keeps replicating the bug.

I keep reinstalling it, but alas nothing happens. I think I'm going to give up, it's been like 7 or 8 months.

**Comment by dustinblackman** [comment]
Nothing to do with cookies, something is removing a file that Championify needs in order to boot. The file exists on the release but not after the install.

**Comment by KilogramHours** [comment]
Strange, because I know for sure I only have Windows Defender as an Anti-Virus. Thanks for trying to help, guess it just isn't in the cards for me.

**Comment by dustinblackman** [comment]
Any other kind of cleaner services or malware services running?

**Comment by KilogramHours** [comment]
Nope, none. It doesn't make any sense. I have the worst luck with this stuff. I hope that anyone else who has had this bug comments a solution, because I would be extremely grateful for that.
