### ISSUE TITLE
[Windows] I can not do it Nothing happens

### ISSUE THREAD

**Issue by nelooooo** [dustinblackman/Championify#376]
![untitled](https://user-images.githubusercontent.com/34597136/34070297-3deacb72-e296-11e7-8089-14d6ec97076d.png)

**Comment by hollowsxd** [comment]
Please provide your logs

**Comment by nelooooo** [comment]
_Config and file locations:_
Log: C:/Users/YOURNAME/AppData/Roaming/Championify 
 Config: C:/Users/YOURNAME/AppData/Roaming/Championify
Windows 7
Version 2.1.3
Garena 
Issue:I can not use the image, and I have no file location. championify.log.txt_ prefs.json_

**Comment by dustinblackman** [comment]
No, the actual log files please.

**Comment by dustinblackman** [comment]
Issue template wasn't followed. Please open a new issue with the correct information.
