### ISSUE TITLE
Version for ubuntu 17.10

### ISSUE THREAD

**Issue by aledevil** [dustinblackman/Championify#377]
Hi, 
could you explain me how i can run championify on my ubuntu 17.10?
i play at LoL with Lutris! there is a way to install Championify?

Thank you a lot :)

**Comment by dustinblackman** [comment]
You can attempt using the OSX setup for [building from source](https://github.com/dustinblackman/Championify#build-from-source), that should work just fine on Linux. Some people have used Wine in the past, but unsure of the configs. I have Linux versions [planned](https://github.com/dustinblackman/Championify/issues/217) but my time has been limited. Good luck!
