### ISSUE TITLE
How to remove builds?

### ISSUE THREAD

**Issue by KoopaTheTurtle** [dustinblackman/Championify#378]
Just wondering how to remove the builds? I did a fresh install of windows (cause of different reasons) so it shouldn't have the builds but it does :/

**Comment by dustinblackman** [comment]
Fresh install and the builds are still there? That doesn't sound right. You sure their from Championify?

**Comment by surajmandalcell** [comment]
You can manually delete the builds by going to the lol_folder/config and delete the "Champions" folder.

**Comment by dustinblackman** [comment]
The delete button is __supposed__ to handle that for you. I have a feeling at some point in time Riot took builds from the config folder and synced them with their cloud setup initially. If that's the case I'm unsure how to remove them.

The above answer is correct if the delete button doesn't work. Closing.
