### ISSUE TITLE
Could Not Recognize Any Valid Item Sets

### ISSUE THREAD

**Issue by Valyon** [dustinblackman/Championify#381]
_Config and file locations:_
[championify.log.txt](https://github.com/dustinblackman/Championify/files/1664250/championify.log.txt)

Config Pref: {
  "prefs_version": "2.1.3",
  "locale": "en",
  "install_path": "C:/Riot Games/League Of Legends/",
  "champ_path": "Config/Champions/",
  "local_is_version": "8.2",
  "options": {
    "splititems": false,
    "skillsformat": false,
    "consumables": true,
    "consumables_position": "end",
    "trinkets": true,
    "trinkets_position": "end",
    "locksr": false,
    "sr_source": [
      "koreanbuilds",
      "lolalytics",
      "probuilds"
    ],
    "dontdeleteold": false,
    "aram": true
  }
}

__What operating system: Win 10 64 Bit
__What version of Championify: v. 2.1.3
__What distribution of the league client are you using (NA, EUW, KR, Garena, ect)? NA
__Please explain the issue you're encountering: Hello, 
First off I'm looking forward to being able to use this properly, but I guess maybe I'm missing something. I downloaded the latest version, ran as admin, and imported item sets. However, when I go to import them, it gives me the following: 
![no items](https://user-images.githubusercontent.com/35806431/35392286-04def436-01a7-11e8-9c73-a9ed9a9dad06.png)

__Logs: None I can find?

---

_Please fill in the following for feature requests:_

__Description of feature:__
__Mocks/screenshots of ideas:__

**Comment by dustinblackman** [comment]
League currently has two places where item sets are stored. One is the new item sets where are stored on their remote servers and are accessible in the league client in the same tab from your screenshot. The second place is an older directory that only exists for applications like Championify, it isn't used anywhere else in the game or client. 

The item sets from Championify are not accessible from the client as they use that old directory. They don't cross. Championify item sets are only available once you get in to a game.

I'm unsure why you're getting that error in the screenshot, but Championify doesn't attempt to modify any of the new clients directories or configs. It just uses the older directory that's documented in the [API](https://developer.riotgames.com/item-sets.html).
