### ISSUE TITLE
Probuilds not working

### ISSUE THREAD

**Issue by eco999** [dustinblackman/Championify#382]
_Please fill in the following when reporting an issue/bug and remove this line. Please include all logs, configs, and
screenshots if possible._

_Config and file locations:_
_- Log: https://puu.sh/zbho1/150497c388.txt
_- Config: https://puu.sh/zbhoy/3410a8a4a3.json

__What operating system:_ Win 10 64-bit
__What version of Championify: v2.1.3
__What distribution of the league client are you using (NA, EUW, KR, Garena, ect)?: EUW
__Please explain the issue you're encountering: Probuilds are not being added. It says there are no issues but the only build that shows up for every champion is the recommended items and champion.gg (which I have enabled. When the builds are being added, I'm only seeing Champion.GG builds being added. Nothing about Probuilds. This has been happening since the 8.2 update.
__Screenshots: https://puu.sh/zbhr2/650cbfc347.png
https://puu.sh/zbhrW/a608df3ed0.png

**Comment by elken** [comment]
+1 also having this issue.

**Comment by hollowsxd** [comment]
The log shows nothing, are you sure that is the correct one?
Try to delete all of it and try again.

**Comment by eco999** [comment]
Deleted log and cleared Champions folder in league.
New log when trying to download only Probuilds: https://puu.sh/zc6ep/911801e68a.txt
Install ends immediately. Says there are no unavailable builds. https://puu.sh/zc6g6/04a71ef9a1.png

**Comment by hollowsxd** [comment]
seems like there is no internet connection?
have you try to allow it on firewall or maybe disable you AVs?

**Comment by Dyzson** [comment]
Probuilds.net have refreshed page. Maybe API needs a refresh too?

**Comment by elken** [comment]
Not OP but mine is a fresh install and log shows the same. 

⁣Regards,
Ellis Kenyő

GitLab | GitHub | Keybase | elken.me​
