### ISSUE TITLE
Something broke error

### ISSUE THREAD

**Issue by frsbrzgt86fan** [dustinblackman/Championify#389]
__What operating system: Windows 10 64 Bit
__What version of Championify: 2.1.5
__What distribution of the league client are you using (NA, EUW, KR, Garena, ect)?: NA
__Please explain the issue you're encountering: Something broke error and getting stuck on updating
__Screenshots: https://i.imgur.com/39479Vu.jpg
__Logs: https://pastebin.com/B2WssBax

**Comment by hollowsxd** [comment]
Did you try all the above?

**Comment by dustinblackman** [comment]
Something is blocking outbound connections from Championify on your system.

**Comment by frsbrzgt86fan** [comment]
Thanks guys I figured it out. To answer @hollowsxd yes I tried all methods above. I however incorrectly believed that malwarebytes was handling the championify exclusion properly as it has for over a year, I believe a recent windows update or malwarebytes effected it. After turning off web protection on malwarebytes it works!
