### ISSUE TITLE
Make a Windows Installer

### ISSUE THREAD

**Issue by AlexanderOtavka** [dustinblackman/Championify#39]
Dragging the files from the .zip is fine, but it would be easier if you just had an installer that put all of the stuff in C:\Program Files (x86)\Championify with a single click.

**Comment by dustinblackman** [comment]
I think NSIS would be my best bet for setting this up as they have a command line setup. I'll see about creating a gulp module in another repo sometime soon, and then integrate it with Championify release flow.
