### ISSUE TITLE
Championify install bug babel-register

### ISSUE THREAD

**Issue by dagonar** [dustinblackman/Championify#390]
Config and file locations:
Log: No log available, empty folder.
Config: No config available, empty folder.

What operating system: Windows 10
What version of Championify: 2.1.5
What distribution of the league client are you using (NA, EUW, KR, Garena, ect)?: LAN
Please explain the issue you're encountering: After installing latest update, chrome dev tool window opens and specifies that babe-register issues. Championify screen opens but only background is visible. Tried full uninstall and reinstall but same issue comes around.
Screenshots: ![IIssue](https://i.imgur.com/jgxx5cs.png)
Logs: No logs available.

**Comment by dustinblackman** [comment]
The only way that triggers is if you have environment variable `NODE_ENV=development` and you're launching Championify from a terminal.

**Comment by dagonar** [comment]
I didn't knew about this. Working now. LUL

Thanks a lot. 👍
