### ISSUE TITLE
cant get op.gg  builds

### ISSUE THREAD

**Issue by donotvan** [dustinblackman/Championify#393]
_Please fill in the following when reporting an issue/bug and remove this line. Please include all logs, configs, and
screenshots if possible._

_Config and file locations:_
_- Log: C:/Users/YOURNAME/AppData/Roaming/Championify/championify.log.txt_
_- Config: C:/Users/YOURNAME/AppData/Roaming/Championify/prefs.json_

__What operating system:Windows 10
__What version of Championify:2.1.5
__What distribution of the league client are you using (NA, EUW, KR, Garena, ect)?:NA
__Please explain the issue you're encountering:Cant import op.gg builds
__Screenshots:__
__Logs:
{"level":"info","message":"Version: 2.1.5","timestamp":"2018-03-27T00:52:46.815Z"}
{"level":"info","message":"Checking for updates","timestamp":"2018-03-27T00:52:48.107Z"}
{"level":"info","message":"No updates found","timestamp":"2018-03-27T00:52:48.195Z"}
{"message":"","stack":"RequestError\n    at requester.then.res (C:\\Users\\viet\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\js\\helpers\\request.js:150:20)\n    at tryCatcher (C:\\Users\\viet\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\viet\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\viet\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\viet\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\viet\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:691:18)\n    at Promise._fulfill (C:\\Users\\viet\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:636:18)\n    at Request._callback (C:\\Users\\viet\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\nodeback.js:42:21)\n    at Request.self.callback (C:\\Users\\viet\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\request\\request.js:199:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (C:\\Users\\viet\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\request\\request.js:1036:10)\n    at emitOne (events.js:101:20)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (C:\\Users\\viet\\AppData\\Local\\Championify\\app-2.1.5\\resources\\app.asar\\node_modules\\request\\request.js:963:12)\n    at emitNone (events.js:91:20)","code":503,"url":"https://www.op.gg/champion/ahri/statistics/mid","body":"<html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle this request.\n</body></html>\n","type":"RequestError","ua":"win32 10.0.14393","locale":"en","level":"warn","timestamp":"2018-03-27T00:52:51.642Z"}

**Comment by dustinblackman** [comment]
I'm going to assume op.gg was down as I just did a full import and everything worked. Can you try again please?

**Comment by dustinblackman** [comment]
Going to call this a dup of https://github.com/dustinblackman/Championify/issues/391
