### ISSUE TITLE
Not downloading itemsests

### ISSUE THREAD

**Issue by spavezv** [dustinblackman/Championify#4]
I have LoL installed in the default location: C:\Riot Games. I run the file in admin mode, it says that it is selecting the right folder, but when it ends, the Champions folder is empty. I even copied the exe to the folder where the LoL launcher is. 

Something that I notice is a bit weird is the separators for the location of Champions folder . If I run the exe from any location it separates the folders with "/". 

![lol 1](https://cloud.githubusercontent.com/assets/1225927/7442260/3bdd0188-f0e0-11e4-8c89-7eddba61a31e.png)

But if I use the exe in the LoL folder it uses "\" till the LoL folder.

![lol 2](https://cloud.githubusercontent.com/assets/1225927/7442261/3d109272-f0e0-11e4-9ca4-8e3b125b68a1.png)

**Comment by dustinblackman** [comment]
The direction of the slashes don't matter as Node fixes it, it's just what I have consoling out as I develop on Mac and am used to the habit of '/'.

As for the folder being empty is odd. It's the actual folder being empty, correct? Not the list of item sets in the launcher? Cause the item sets don't show up in the launcher, only in the game.

**Comment by spavezv** [comment]
The folder was empty and tested in game, no item sets.

I rerun the program and now it donwloaded all the files and the folder is full with the champions item sets. The weird part is that before the console closed it self and know it waited till I press enter. Maybe it was a conection problem. 

Sorry for creating this issue. Nice job with this program.

**Comment by dustinblackman** [comment]
Oh no, the issue is actually very appreciated! It means I need to actually get around to handling errors like connection problems. I'll get on it as soon as I can.
