### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by obdz** [dustinblackman/Championify#405]
First of all thanks for the effort of making such useful tool and god bless you.
Second I have a request of a feature
__Description of feature:__
It would help a lot to include LoLalytics ARAM builds into ARAM mode/map. As well as metasrc.com for both ranked 5v5 and aram.
Thank you

**Comment by dustinblackman** [comment]
Dup. 
https://github.com/dustinblackman/Championify/issues/233
https://github.com/dustinblackman/Championify/issues/358
