### ISSUE TITLE
Unable to download champion builds.

### ISSUE THREAD

**Issue by Shammy92** [dustinblackman/Championify#410]
_Please fill in the following when reporting an issue/bug and remove this line. Please include all logs, configs, and
screenshots if possible._
https://i.imgur.com/EqKyjo4.png

https://i.imgur.com/h3v8Pyg.png

__What operating system:_Win10
__What version of Championify:_2.15
__What distribution of the league client are you using (NA, EUW, KR, Garena, ect)?:_EUW
__Please explain the issue you're encountering: States that something is broken. Tried importing the builds with admin on and still the same issue. Malwarebytes isn't triggered by the software so I am not sure why it isn't working.
__Screenshots:__
__Logs:__

{"level":"info","message":"Version: 2.1.5","timestamp":"2018-06-11T16:29:41.303Z"}
{"level":"info","message":"Checking for updates","timestamp":"2018-06-11T16:29:42.418Z"}
{"level":"info","message":"No updates found","timestamp":"2018-06-11T16:29:42.637Z"}
{"level":"info","message":"Locale: en","timestamp":"2018-06-11T16:29:43.708Z"}
{"level":"info","message":"Saved preference file to C:\\Users\\Simon\\AppData\\Roaming\\Championify\\prefs.json","timestamp":"2018-06-11T16:29:43.714Z"}
{"level":"info","message":"Getting LoL Version","timestamp":"2018-06-11T16:29:44.051Z"}
{"level":"info","message":"Downloading Champs from Riot","timestamp":"2018-06-11T16:29:44.125Z"}
{"message":"Can't get Champion.gg version","stack":"RequestError: Can't get Champion.gg version\n    at then.catch.err (E:\\Championify\\resources\\app.asar\\js\\sources\\championgg.js:110:11)\n    at tryCatcher (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)\nCause: RequestError: Error\n    at requester.then.catch.err (E:\\Championify\\resources\\app.asar\\js\\helpers\\request.js:156:18)\n    at tryCatcher (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)","code":"Can't get Champion.gg version","type":"RequestError","ua":"win32 10.0.17134","locale":"en","cause":{"message":"Error","code":"Error","url":"http://champion.gg/faq/","body":{"cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"code":"ETIMEDOUT","connect":false},"type":"RequestError","ua":"win32 10.0.17134","locale":"en"},"rootCause":{"message":"Error","code":"Error","url":"http://champion.gg/faq/","body":{"cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"code":"ETIMEDOUT","connect":false},"type":"RequestError","ua":"win32 10.0.17134","locale":"en"},"ownStack":"RequestError: Can't get Champion.gg version\n    at then.catch.err (E:\\Championify\\resources\\app.asar\\js\\sources\\championgg.js:110:11)\n    at tryCatcher (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)","level":"warn","timestamp":"2018-06-11T16:30:12.402Z"}
{"message":"Error","stack":"RequestError: Error\n    at requester.then.catch.err (E:\\Championify\\resources\\app.asar\\js\\helpers\\request.js:156:18)\n    at tryCatcher (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)","code":"Error","url":"http://koreanbuilds.net/","body":{"cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"code":"ETIMEDOUT","connect":false},"type":"RequestError","ua":"win32 10.0.17134","locale":"en","level":"warn","timestamp":"2018-06-11T16:30:12.403Z"}
{"message":"Error","stack":"RequestError: Error\n    at requester.then.catch.err (E:\\Championify\\resources\\app.asar\\js\\helpers\\request.js:156:18)\n    at tryCatcher (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)","code":"Error","url":"http://championify.lolalytics.com/data/1.0/ranked.json","body":{"cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"code":"ETIMEDOUT","connect":false},"type":"RequestError","ua":"win32 10.0.17134","locale":"en","level":"warn","timestamp":"2018-06-11T16:30:12.404Z"}
{"message":"Error","stack":"RequestError: Error\n    at requester.then.catch.err (E:\\Championify\\resources\\app.asar\\js\\helpers\\request.js:156:18)\n    at tryCatcher (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)","code":"Error","url":"http://www.lolflavor.com/champions/Ahri/Recommended/Ahri_mid_scrape.json","body":{"cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"code":"ETIMEDOUT","connect":false},"type":"RequestError","ua":"win32 10.0.17134","locale":"en","level":"warn","timestamp":"2018-06-11T16:30:12.406Z"}
{"message":"Error","stack":"RequestError: Error\n    at requester.then.catch.err (E:\\Championify\\resources\\app.asar\\js\\helpers\\request.js:156:18)\n    at tryCatcher (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)","code":"Error","url":"http://lolmasters.net/about","body":{"cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"code":"ETIMEDOUT","connect":false},"type":"RequestError","ua":"win32 10.0.17134","locale":"en","level":"warn","timestamp":"2018-06-11T16:30:12.409Z"}
{"message":"Error","stack":"RequestError: Error\n    at requester.then.catch.err (E:\\Championify\\resources\\app.asar\\js\\helpers\\request.js:156:18)\n    at tryCatcher (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Async.drainQueues (E:\\Championify\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)","code":"Error","url":"http://ddragon.leagueoflegends.com/cdn/8.11.1/data/en_US/champion.json","body":{"cause":{"code":"ETIMEDOUT","connect":false},"isOperational":true,"code":"ETIMEDOUT","connect":false},"type":"RequestError","ua":"win32 10.0.17134","locale":"en","level":"error","timestamp":"2018-06-11T16:30:14.133Z"}

**Comment by dustinblackman** [comment]
Dup. https://github.com/dustinblackman/Championify/issues/408
