### ISSUE TITLE
Championift can't get any builds

### ISSUE THREAD

**Issue by mlax99** [dustinblackman/Championify#412]
When running the app, I suddenly can't get any updates from any of the sources. When I press update, its times out eventually and says "Did you try running as an admin? Or your anti/virus/firewall is blocking Championify? Internet on?"

I've ran in admin, firewall is off, Antivirus excluded from scanning the folder.

[championify.log.txt](https://github.com/dustinblackman/Championify/files/2113505/championify.log.txt)
![championify error](https://user-images.githubusercontent.com/40375141/41570787-0fab6e9a-7325-11e8-8f49-83b7d75458eb.jpg)

**Comment by dustinblackman** [comment]
Dup. https://github.com/dustinblackman/Championify/issues/408
