### ISSUE TITLE
Championify cannot fetch builds from op.gg specifically

### ISSUE THREAD

**Issue by EcoReck** [dustinblackman/Championify#413]
I cannot download builds from op.gg for some reason, is there a reasoning behind this?
![opgg](https://user-images.githubusercontent.com/17102208/41669209-4645498e-747f-11e8-8a0d-c3620264e8c9.png)
![opgg2](https://user-images.githubusercontent.com/17102208/41669232-58c2480a-747f-11e8-931d-396eca43f438.png)

**Comment by dustinblackman** [comment]
op.gg was down. Seems fine now.

**Comment by EcoReck** [comment]
@dustinblackman to this day it still will not let me fetch from op.gg
