### ISSUE TITLE
Add Oracle's Extract to ARAM consumables

### ISSUE THREAD

**Issue by rafaeldamasceno** [dustinblackman/Championify#42]

**Comment by rafaeldamasceno** [comment]
@dustinblackman I see you didn't assign this yet, perhaps you missed it. Would be nice of you to add Oracle's Extract to consumables when you are playing ARAM.

**Comment by dustinblackman** [comment]
Will add in next version, just need to set it up to look nice.

**Comment by guykisel** [comment]
Instead of manually maintaining the list of prebuilt items, you could probably parse all the trinkets and consumables out of http://ddragon.leagueoflegends.com/cdn/5.13.1/data/en_US/item.json

**Comment by dustinblackman** [comment]
For ARAM it's not manual, it's just coming in from whatever lolflavor has. I have yet to customize it. Though you're right that can be done. :)
