### ISSUE TITLE
AutoUpdate Error - Unable to find valid app

### ISSUE THREAD

**Issue by bunnis** [dustinblackman/Championify#43]
Fresh zip from reddit post(i saved it) Championify.WIN.0-1-0 always does the same. Run as admin, still same prob.i5 8gb x64 lenovo win 7 enterprise
included screenshot of error. tried to pinpoint the origin in the source code but the file does not exist. and also my knowledge of asar and js is limited so i didnt tried further, also no sdk for this. 
http://imgur.com/2BefnUB

let me know if you need more info

**Comment by dustinblackman** [comment]
Now you tested with 0.1.0. What about 0.3.1?

**Comment by bunnis** [comment]
my bad im stupid. didnt try the good version. ty

**Comment by dustinblackman** [comment]
It's all good, thanks buddy. :)
