### ISSUE TITLE
Infected web resource detected

### ISSUE THREAD

**Issue by michalwidera** [dustinblackman/Championify#47]
Hi,
My bitdefender found following set of simillar issues (about 60) on championify run:
"The we resource http://www.lolflavor.com/champions/Zielan/Recommended/Zielan_aram_scrape.jscon has been detected as infected. The web resource has been successfully blocked and your PC is now safe."

I assume false positive - but worht to check what happend.

Regards,
Michal

**Comment by dustinblackman** [comment]
It's a false positive, Bitdefender has lol flavor marked as a malware site when it's not. I have the readme updated in my dev branch, will be pushing it on the next release. 

https://github.com/dustinblackman/Championify/blob/dev/README.md#why-is-my-antivirus-complaining-about-lolflavor
