### ISSUE TITLE
Download of itemsets blocking

### ISSUE THREAD

**Issue by miofferg** [dustinblackman/Championify#49]
When trying to download the newest itemsets, the download stops at "Processing Rift: zyra" (which is the last champ to be downloaded) then the program just hangs up! 
Are there any logs with which i could give u some further info`?

**Comment by janssenb** [comment]
same here

**Comment by reddevil18** [comment]
Same thing here :(

**Comment by reddevil18** [comment]
Run it near 5 hours after in case it was due to bring done too close to the patch, same issue :(

**Comment by dustinblackman** [comment]
Sorry about that, missed a function when I was doing a cleanup. New version fixes the problem!
