### ISSUE TITLE
Stuck at ARAM Zyra

### ISSUE THREAD

**Issue by tanjo3** [dustinblackman/Championify#51]
Similar to issue #36, program stops processing after ARAM Zyra.
Screenshot: http://imgur.com/Di2C00S

**Comment by roman770** [comment]
i've got the same problem , using windows 10

**Comment by dustinblackman** [comment]
Will see about writing a logger this evening that you both can send me. I'm not having the issue here locally.

**Comment by tanjo3** [comment]
Reran the program today and it worked so it might be an issue on champ.gg's end.

**Comment by dustinblackman** [comment]
@roman770 Do you still have the problem?

**Comment by dustinblackman** [comment]
Fixed in https://github.com/dustinblackman/Championify/tree/0.4.0
