### ISSUE TITLE
Updated official ItemSet documentaion for League

### ISSUE THREAD

**Issue by sargonas** [dustinblackman/Championify#53]
Hey Dustin! Not really an issue, but I figured you would (potentially) find this handy! We just got done making some changes to clean up how league handles custom item sets better, and also put together some new official documentation on our developer portal about it. Your stuff works great (I'm a huge fan an user myself!), but I thought I'd share the updates early before we officially announce them, just in case there is anything here that can help you improve things!

https://developer.riotgames.com/docs/item-sets

Keep up the awesome work!

J. aka "Riot Sargonas"
ThirdParty Developer Relations Manager

**Comment by dustinblackman** [comment]
@sargonas This is fantastic, thanks so much for the update! Is this currently live in production? And do item sets now appear in the launcher as well?

**Comment by sargonas** [comment]
Yup it went live in patch 5.13 last week! As to the launcher however, I don't believe so. That requires a whole different set of tech changes, though it's something that's been backlogged.

**Comment by dustinblackman** [comment]
Good to know! I'll see if I can take advantage of anything in the docs and add it to this issue. Thanks again!
