### ISSUE TITLE
Installer version doesn't work with no-english locale

### ISSUE THREAD

**Issue by AirisLuna** [dustinblackman/Championify#58]
Hi, I have my computer with Chinese, Japanese and Korean languages, and in all three the installer version didn't work. I had to download the zip version of the program in order to use it. It would be nice have a universal installer that work with all locale, especially since League is a known game worldwide.

**Comment by dustinblackman** [comment]
What's the error?

**Comment by dustinblackman** [comment]
The following languages have been added to the installer, and will be available on the next release. https://github.com/dustinblackman/Championify/blob/762456bba54044ef31b706ef3ba063f19fcf7013/resources/win/inno_script.iss#L25-L57
