### ISSUE TITLE
Automate manaless champion list

### ISSUE THREAD

**Issue by guykisel** [dustinblackman/Championify#60]
I could be wrong, but it looks like `data/manaless.json` is maintained manually. I think in `getChamps` you're already downloading all the champ info ( http://ddragon.leagueoflegends.com/cdn/5.13.1/data/en_US/champion.json for example), and you should be able to determine from a champ's `partype` if they're manaless because it will be something other than `Mana`.

**Comment by dustinblackman** [comment]
Ah well isn't that a great find! Thanks, I'll add that to next version. :)
