### ISSUE TITLE
Selecting your folder

### ISSUE THREAD

**Issue by Kakarifers** [dustinblackman/Championify#62]
I have League downloaded to my G drive, so it isn't automatically detecting it. However, if I use the search function and open the file location, it gives me the proper folder. When pasting that into the area, it does not change anything; it simply states I need to select my folder still. If I go through the browsing function, and go to the same area, the launcher file is not present in the same folder I'm directed to via opening the file location.

**Comment by Kakarifers** [comment]
I have figured out the issue. Apparently it does not like the folder location being pasted in, nor manually typed. It seems you must select the folder via the browse option in order for it to work.

**Comment by dustinblackman** [comment]
Id still consider that an issue. Thanks for the report, I'll look in to it.
