### ISSUE TITLE
Garena detection #1 only detects Garena Singapore

### ISSUE THREAD

**Issue by secretdataz** [dustinblackman/Championify#63]
tl;dr Return of #3 (The #3 fix doesn't actually work because you didn't add wildcard in the file name.)

Due to file naming Garena uses. It suffix "LoL" in file and folder name with subregion name with exception of Singapore which is why it's the only detected region.
For example, TH server launcher become LoLTHLauncher.exe and its folder become LoLTH.

IMO, this bug can be easily fixed with use of wildcard. But, I'm not a CoffeeScript guy so I'll leave all the works for you.
Pics
![EXE](http://i.imgur.com/cj0bAAU.png)
![Folder](
![image](http://i.imgur.com/fihbUEL.png)

**Comment by dustinblackman** [comment]
Ah, the pictures will defiantly help. Thanks! I'll get on it.

**Comment by dustinblackman** [comment]
Issue is also with the launcher.exe as well.
