### ISSUE TITLE
Import issue?

### ISSUE THREAD

**Issue by Kakarifers** [dustinblackman/Championify#64]
Well, thought the program seemed to work and run as intended, as soon as I load League, there are no item sets seen. Unless only my own made item sets would show up, which I highly doubt is the case. 

The program: http://i.imgur.com/CtNoFwp.png

Item sets: http://i.imgur.com/8oNPiHG.png

**Comment by secretdataz** [comment]
You can only see Championified item sets in game. Not in lobby client.

**Comment by Kakarifers** [comment]
Oh? I would've thought it would display in the item sets section as well. I'm rather surprised that isn't the case, and rather intrigued on how it accomplishes creating item sets to be used in game, yet they aren't physically there on the item sets tab.

**Comment by dustinblackman** [comment]
It's a Riot restriction, you can find more in my FAQ. :)
