### ISSUE TITLE
After installing the app. Client crashes

### ISSUE THREAD

**Issue by jpkontreras** [dustinblackman/Championify#66]
like the title says. After i log in to my  lol account the client freezes all my pc 
I already clicked in the delete button , i repaired my client and i even had to reinstall but nothing works
i managed to save a log that was in a folder called " Championify crashes"  i can send you that file
since there is not an option for upload it 

Excuse my english ,not my native lenguaje
Thank you for reading

**Comment by dustinblackman** [comment]
The launcher or game freezes? That's where things get specific.
If the launcher freezes, then it's not Championify related.

The delete button takes care of removing Championifyt item sets for you, but if you want to be safe go to your League installation directly, usually "C:\Riot Games\League of Legends\Config" and delete the Champions folder.

If that doesn't fix the problem, then it's definitely not Championify related.

**Comment by jpkontreras** [comment]
ok but isnt suspicious that when  i installed the app , the client stopped working and the app itself created a crash log ??
but thank you for reading .

**Comment by dustinblackman** [comment]
I need to see the crash log, cause what you're referring to doesn't like a log I created. Throw it up on a gist and I'll check it out. :)

**Comment by jpkontreras** [comment]
https://gist.github.com/jpkontreras/b19671fad7859ec0eb58

**Comment by dustinblackman** [comment]
Oh, that's an Electron crash log. That's explains why I was lost, however the log isn't saying any special. What operating system? And did the fix I mention earlier work to fix your client?

**Comment by jpkontreras** [comment]
nope i clicked the delete button and with the reinstall all the files were erased

**Comment by jpkontreras** [comment]
windows 8.1 64 bits

**Comment by dustinblackman** [comment]
Thanks for the report, I have a theory on why this may of happened. I think there may of been an EPERM error thrown and it wrote an empty JSON file. Will try on my system and see if it crashes my game.

**Comment by jpkontreras** [comment]
ok let me know i really want to install this app keep up with the good work :+1:

**Comment by dustinblackman** [comment]
Turns out this is a dup of #59. It'll be fixed next version.
