### ISSUE TITLE
What exactly is required to build from source?

### ISSUE THREAD

**Issue by Xerrion** [dustinblackman/Championify#70]
Hey, I am quite new to all this NodeJS, iojs, Bower and Grunt etc. What do I need exactly to compile the source? The npm build told me that msbuild.exe is missing, could you please clarify it for me? the iojs doc is very poorly written.

I am trying to compile it to educate my self, to speed up my own development workflow.

**Comment by dustinblackman** [comment]
I don't compile on Windows ever, so I'm not exactly sure. Off the top of my head I believe you need Visual Studios 2010 minimum and that'll include everything needed to npm install.

**Comment by Xerrion** [comment]
Do you then compile on Mac?


2015-07-23 21:16 GMT+02:00 Dustin Blackman <notifications@github.com>:

**Comment by dustinblackman** [comment]
Yes I usually compile on Mac, must easier.

If I'm reading it right, it's actually asking for Visual Studio 2015 (Buildtools 14.0). I'm guessing asar archives got updated and require the latest to work.

**Comment by Xerrion** [comment]
Now it seems that some deprecated feature in 2015 is giving me problems, and I know nothing about C++, I am now giving 2013 a go, and if that doesn't work and I'll just give up.

**Comment by dustinblackman** [comment]
I'll see about compiling on a Windows system over the weekend if you can't figure it out. :)

**Comment by Xerrion** [comment]
Seems, like 2013 did the trick, I am currently running build.
