### ISSUE TITLE
Builds do not show up

### ISSUE THREAD

**Issue by TheBanjo34** [dustinblackman/Championify#71]
On my desktop, I run league of legends and championify as administrator, however my the builds do not show up at all. I downloaded championify for my laptop and ran the program and the builds did show up. I've tried reinstalling championify, but it didn't work. I've looked through my League of Legends directory in the folder where are the builds are stored and it seems that the builds are download, seeing that they have the "CGG" format, but for whatever reason when I play I only receive the recommended builds from riot. I love the app and was wondering if I could get help to get it working on my desktop.

**Comment by dustinblackman** [comment]
Open up a CGG file in Notepad, is there data?
If there is, try clicking on the menu where it says recommended builds once it's game, and see if they pop up in the list.

**Comment by dustinblackman** [comment]
@TheBanjo34 Did it fix the issue?
