### ISSUE TITLE
Create tutorial on how to use

### ISSUE THREAD

**Issue by dustinblackman** [dustinblackman/Championify#72]

**Comment by josevill** [comment]
How do you want this tutorial? Some video or just images? I could help you with either.

**Comment by dustinblackman** [comment]
Possibly images and videos (though I'd wait for 1.0), but I was more thinking on how Android apps give off a first initial tutorial when the app is opened for the first time. Sort of how it highlights areas and gives a description. I'm sure there's a Javascript library somewhere that'll help me accomplish this.

**Comment by josevill** [comment]
http://usablica.github.io/intro.js/
You could use that lib. I just searched for it. There should be many more :p

**Comment by dustinblackman** [comment]
Hey that's pretty! :D Good find, thanks for that.
