### ISSUE TITLE
Something Broke!

### ISSUE THREAD

**Issue by ObeyGods** [dustinblackman/Championify#85]
Used to work then all of a sudden stopped working. Just uploaded log

**Comment by dustinblackman** [comment]
@ObeyGods Github has been having connection issues. Try again and let me know.

**Comment by ObeyGods** [comment]
Still have that error how would i give you the log?

**Comment by dustinblackman** [comment]
@ObeyGods C:\Users\USER\AppData\Roaming\Championify\championify.log

You'll also see a prefs.json file in there. Send me that too, as I'm seeing an error in the logger relating to it and I'm wondering if it's you.

**Comment by ObeyGods** [comment]
How would i send you those files? Cant threw here

**Comment by dustinblackman** [comment]
@ObeyGods http://gist.github.com

**Comment by ObeyGods** [comment]
I can add the log but not prefs.json

**Comment by dustinblackman** [comment]
Open it in notepad and copy the contents.

**Comment by ObeyGods** [comment]
How can i PM you link?

**Comment by ObeyGods** [comment]
Got it fixed. Just had to delete prefs.json
